(function(root){'use strict';
const NS=root.InkDOS2Spreadsheets=root.InkDOS2Spreadsheets||{};
// Date/time formats and formats with sections or literals (accounting, "(#,##0)", m"月"d"日" ...) use the
// workbook number formatter; built-in date ids carry no format string in a package, so they map here.
const BUILTIN_NUMBERS={1:'0',2:'0.00',37:'#,##0 ;(#,##0)',38:'#,##0 ;[Red](#,##0)',39:'#,##0.00;(#,##0.00)',40:'#,##0.00;[Red](#,##0.00)',41:'_(* #,##0_);_(* (#,##0);_(* "-"_);_(@_)',42:'_($* #,##0_);_($* (#,##0);_($* "-"_);_(@_)',43:'_(* #,##0.00_);_(* (#,##0.00);_(* "-"??_);_(@_)',44:'_($* #,##0.00_);_($* (#,##0.00);_($* "-"??_);_(@_)'};
const BUILTIN_DATES={14:'m/d/yy',15:'d-mmm-yy',16:'d-mmm',17:'mmm-yy',18:'h:mm AM/PM',19:'h:mm:ss AM/PM',20:'h:mm',21:'h:mm:ss',22:'m/d/yy h:mm',45:'mm:ss',46:'[h]:mm:ss',47:'mmss.0'};
function patternNumber(value,st,fmt){const bare=fmt.replace(/"[^"]*"|\\.|\[[^\]]*\]/g,''),date=/(^|[^a-z])[dmyhs]+/i.test(bare)&&!/[#0]\s*[Ee]/.test(bare);if(!date&&(!/[;"_*\\]/.test(fmt)||fmt.includes('%')))return null;const fn=root.LocalXLS?.formatNumber;if(typeof fn!=='function')return null;const out=fn(value,{...st,numberFormat:fmt},!!root.__inkdosSpreadsheetsS1?.session?.book?.date1904);return out==null?null:String(out)}
function formattedNumber(value,style){if(typeof value!=='number'||!Number.isFinite(value))return null;const st=style||{},id=Number(st.numFmtId||0),builtin=id===9?'0%':id===10?'0.00%':id===3?'#,##0':id===4?'#,##0.00':id>=5&&id<=8?(id===5||id===6?'$#,##0':'$#,##0.00'):BUILTIN_DATES[id]||BUILTIN_NUMBERS[id]||'',fmt=String(st.numberFormat||builtin);if(!fmt)return null;const patterned=patternNumber(value,st,fmt);if(patterned!=null)return patterned;if(fmt.includes('%')){const decimals=(fmt.match(/0\.(0+)/)||[])[1]?.length||0;return(value*100).toFixed(decimals)+'%'}const decimals=(fmt.match(/0\.(0+)/)||[])[1]?.length||0,grouped=/#,##0/.test(fmt),symbol=(fmt.match(/[$€£¥₹]/)||[])[0]||'';return symbol+value.toLocaleString(undefined,{useGrouping:grouped,minimumFractionDigits:decimals,maximumFractionDigits:decimals})}
function display(cell){if(!cell)return'';const effective=cell.calculated!==undefined&&cell.calculated!==null?cell.calculated:cell.v;if(cell.style?.hideZero&&typeof effective==='number'&&Number.isFinite(effective)&&effective===0)return'';const formatted=formattedNumber(effective,cell.style);if(formatted!=null)return formatted;if(cell.calculated!==undefined&&cell.calculated!==null)return String(cell.calculated);if(cell.f){const cached=cell.display;if(cached!==undefined&&cached!==null&&cached!==''&&String(cached)!=='='+cell.f)return String(cached);return'='+cell.f}return String(cell.display??cell.v??'')}
function borderCss(side){if(!side)return'';const widths={hair:1,thin:1,medium:2,thick:3,double:3,dashed:1,dotted:1,mediumDashed:2,mediumDashDot:2},styles={dashed:'dashed',dotted:'dotted',double:'double'};return`${widths[side.style]||1}px ${styles[side.style]||'solid'} ${side.color||'#70757d'}`}
let measureCtx=null;
// Excel-style overflow: unwrapped left/general text continues over following empty, unmerged cells.
function overflowExtent(sheet,merges,r,c,cell,text,scale,el){const st=cell?.style||{};if(!text||st.wrap||st.rotation||(st.align&&st.align!=='general'&&st.align!=='left'))return 0;const value=cell.calculated!==undefined&&cell.calculated!==null?cell.calculated:cell.v;if(typeof value==='number'||typeof value==='boolean')return 0;const key=root.LocalXLSX.encodeRef(r,c);if(merges?.top?.has(key))return 0;const G=NS.GridGeometry,z=Math.max(.01,Number(scale)||1),width=G.colWidth(sheet,c)*z;if(!measureCtx)measureCtx=document.createElement('canvas').getContext('2d');const f=st.font||{};measureCtx.font=`${f.italic?'italic ':''}${f.bold?'700 ':''}${Math.max(4,(Number(f.size)||11)*1.333*z)}px ${f.name?`"${f.name}",`:''}Calibri,"InkDOS Sans",Arial,sans-serif`;const need=measureCtx.measureText(text).width+Math.max(1,4*z)*2+1;if(need<=width)return 0;const vb=(rr,cc,side)=>!!sheet.cells.get(root.LocalXLSX.encodeRef(rr,cc))?.style?.border?.[side];let ext=0;for(let cc=c+1;cc<c+80;cc++){const k=root.LocalXLSX.encodeRef(r,cc);if(merges?.covered?.has(k)||merges?.top?.has(k))break;if(display(sheet.cells.get(k))!=='')break;if(vb(r,cc-1,'right')||vb(r,cc,'left'))break;ext+=G.colWidth(sheet,cc)*z;if(width+ext>=need)break}return Math.ceil(ext)}
function applyStyle(el,cell,scale=1){for(const property of['fontSize','fontFamily','fontWeight','fontStyle','textDecoration','color','backgroundColor','textAlign','transform','borderLeft','borderRight','borderTop','borderBottom','justifyContent','alignItems','padding'])el.style[property]='';const st=cell?.style||{},f=st.font||{},z=Math.max(.25,Math.min(4,Number(scale)||1));el.style.fontSize=Math.max(4,(Number(f.size)||11)*1.333*z)+'px';el.style.padding=`${Math.max(.5,2*z)}px ${Math.max(1,4*z)}px`;if(f.name)el.style.fontFamily=`"${f.name}",Calibri,"InkDOS Sans",Arial,sans-serif`;if(f.bold)el.style.fontWeight='700';if(f.italic)el.style.fontStyle='italic';const dec=[];if(f.underline)dec.push('underline');if(f.strike)dec.push('line-through');if(dec.length)el.style.textDecoration=dec.join(' ');if(f.color)el.style.color=f.color;if(st.fill)el.style.backgroundColor=st.fill;if(st.align&&st.align!=='general'){el.dataset.halign=st.align;el.style.textAlign=st.align}else delete el.dataset.halign;if(st.vertical==='top')el.style.alignItems='flex-start';else if(st.vertical==='bottom')el.style.alignItems='flex-end';else if(st.vertical==='center')el.style.alignItems='center';if(st.wrap)el.dataset.wrap='1';else delete el.dataset.wrap;if(st.rotation)el.style.transform=`rotate(${st.rotation>90?st.rotation-180:st.rotation}deg)`;for(const side of['left','right','top','bottom']){const v=borderCss(st.border?.[side]);if(v)el.style['border'+side[0].toUpperCase()+side.slice(1)]=v}}
function fillPreviewPlan(source,target){const down=Math.max(0,target.r-source.r2),up=Math.max(0,source.r1-target.r),right=Math.max(0,target.c-source.c2),left=Math.max(0,source.c1-target.c),vertical=Math.max(down,up),horizontal=Math.max(right,left);if(!vertical&&!horizontal)return null;if(vertical>=horizontal)return{axis:'row',direction:down?1:-1,range:{r1:Math.min(source.r1,target.r),c1:source.c1,r2:Math.max(source.r2,target.r),c2:source.c2}};return{axis:'column',direction:right?1:-1,range:{r1:source.r1,c1:Math.min(source.c1,target.c),r2:source.r2,c2:Math.max(source.c2,target.c)}}}
function mergeMaps(sheet){const top=new Map(),covered=new Set();for(const m of sheet.merges||[]){try{const q=root.LocalXLSX.decodeRange(m),key=root.LocalXLSX.encodeRef(q.r1,q.c1);top.set(key,q);for(let r=q.r1;r<=q.r2;r++)for(let c=q.c1;c<=q.c2;c++)if(r!==q.r1||c!==q.c1)covered.add(root.LocalXLSX.encodeRef(r,c))}catch(_){}}return{top,covered}}
function drawingPoint(marker,g){if(!marker)return null;const c=Math.max(0,Math.min(g.columns-1,Number(marker.c)||0)),r=Math.max(0,Math.min(g.rows-1,Number(marker.r)||0));return{x:g.rowHeader+g.x[c]+(Number(marker.x)||0)*g.scale,y:g.columnHeader+g.y[r]+(Number(marker.y)||0)*g.scale}}
function renderDrawings(stage,sheet,g){stage.querySelector('.drawing-layer')?.remove();const drawings=sheet?.drawings||[];if(!drawings.length||!g)return;const layer=document.createElement('div');layer.className='drawing-layer';for(const drawing of drawings){const a=drawingPoint(drawing.from,g),b=drawingPoint(drawing.to,g);if(!a)continue;const item=drawing.kind==='image'?document.createElement('img'):document.createElement('div');item.className='sheet-drawing '+(drawing.kind||'shape');item.style.left=a.x+'px';item.style.top=a.y+'px';let width=Number(drawing.size?.w)||((b?.x||a.x+120)-a.x),height=Number(drawing.size?.h)||((b?.y||a.y+60)-a.y);if(drawing.size){width*=g.scale;height*=g.scale}item.style.width=Math.max(1,width)+'px';item.style.height=Math.max(1,height)+'px';if(drawing.kind==='image'){item.src=drawing.url||'';item.alt=drawing.name||'';item.draggable=false}else if(drawing.kind==='chart'){item.setAttribute('role','img');item.setAttribute('aria-label',drawing.title||'Chart');const title=document.createElement('strong');title.textContent=drawing.title||'Chart';item.appendChild(title);const plot=document.createElement('div');plot.className='chart-preview';const values=(drawing.series||[]).flatMap(x=>x.values||[]).map(Number).filter(Number.isFinite),max=Math.max(1,...values.map(Math.abs));for(const series of drawing.series||[]){const row=document.createElement('div');row.className='chart-series';for(const value of series.values||[]){const bar=document.createElement('i');bar.style.height=Math.max(2,Math.abs(Number(value)||0)/max*70)+'%';bar.title=String(value);row.appendChild(bar)}plot.appendChild(row)}item.appendChild(plot)}else{item.textContent=drawing.text||'';item.style.fontSize=Math.max(7,(Number(drawing.fontSize)||10)*g.scale)+'px';item.style.fontWeight=drawing.bold?'700':'400';item.style.background=drawing.fill&&drawing.fill!=='transparent'?drawing.fill:'transparent';if(drawing.line&&drawing.line!=='#00000000'&&drawing.lineWidth!==0)item.style.border=`${Math.max(1,(Number(drawing.lineWidth)||1)*g.scale)}px solid ${drawing.line}`}layer.appendChild(item)}stage.appendChild(layer)}
class GridSurface{
 constructor({viewport,stage,selection,onSelectionChange,onCommit,onResizeColumn,onResizeRow,onFill}={}){this.viewport=viewport;this.stage=stage;this.selection=selection;this.onSelectionChange=onSelectionChange;this.onCommit=onCommit;this.onResizeColumn=onResizeColumn;this.onResizeRow=onResizeRow;this.onFill=onFill;this.sheet=null;this.geometry=null;this.signature='';this.drag=false;this.fillDrag=null;this.editing=null;window.addEventListener('pointermove',e=>this.trackFillPointer(e));window.addEventListener('pointerup',e=>this.finishPointer(e));window.addEventListener('pointercancel',()=>this.cancelPointer());viewport?.addEventListener('scroll',()=>this.updateWindow(),{passive:true});window.addEventListener('resize',()=>this.updateWindow(),{passive:true})}
 beginFill(e){if(!this.sheet||this.editing)return;e.preventDefault();e.stopPropagation();const q={...this.selection.range};this.drag=false;this.fillDrag={source:q,target:{r:q.r2,c:q.c2},ctrlKey:!!e.ctrlKey};this.stage.classList.add('fill-dragging');this.refreshFillPreview()}
 updateFillTarget(r,c,e){if(!this.fillDrag)return false;this.fillDrag.target={r,c};this.fillDrag.ctrlKey=!!(e?.ctrlKey||this.fillDrag.ctrlKey);this.refreshFillPreview();return true}
 trackFillPointer(e){if(!this.fillDrag||!Number.isFinite(e?.clientX)||!Number.isFinite(e?.clientY))return false;const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest?.('.cell');if(!hit||!this.stage.contains(hit))return false;const r=Number(hit.dataset.r),c=Number(hit.dataset.c);if(!Number.isInteger(r)||!Number.isInteger(c))return false;return this.updateFillTarget(r,c,e)}
 clearFillPreview(){this.stage.querySelectorAll('.cell.fill-preview').forEach(x=>x.classList.remove('fill-preview'))}
 refreshFillPreview(){this.clearFillPreview();const state=this.fillDrag;if(!state)return;const q=state.source,plan=fillPreviewPlan(q,state.target);if(!plan)return;const range=plan.range;for(const el of this.stage.querySelectorAll('.cell')){const r=+el.dataset.r,c=+el.dataset.c;if(r>=range.r1&&r<=range.r2&&c>=range.c1&&c<=range.c2&&!(r>=q.r1&&r<=q.r2&&c>=q.c1&&c<=q.c2))el.classList.add('fill-preview')}}
 finishPointer(e){if(this.fillDrag){const state=this.fillDrag;this.fillDrag=null;this.stage.classList.remove('fill-dragging');this.clearFillPreview();const q=state.source,t=state.target,outside=t.r<q.r1||t.r>q.r2||t.c<q.c1||t.c>q.c2;if(outside)this.onFill?.(q,t,{ctrlKey:!!(e?.ctrlKey||state.ctrlKey)});else this.refreshSelection()}this.drag=false}
 cancelPointer(){this.fillDrag=null;this.drag=false;this.stage.classList.remove('fill-dragging');this.clearFillPreview();this.refreshSelection()}
 setSheet(sheet,geometry){this.sheet=sheet;this.geometry=geometry;const sig=[sheet.name,sheet.maxR,sheet.maxC,(sheet.merges||[]).join('|')].join('::');if(sig!==this.signature){this.build();this.signature=sig}else this.applyGeometry();this.refreshCells();this.refreshSelection()}
 applyGeometry(){const g=this.geometry,s=this.sheet;if(!g||!s)return;const tracks=(first,axis,count)=>{const out=[`${first}px`];let size='',run=0;const flush=()=>{if(run)out.push(run>1?`repeat(${run},${size})`:size)};for(let i=0;i<count;i++){const next=`${(axis[i+1]-axis[i]).toFixed(3)}px`;if(next===size)run++;else{flush();size=next;run=1}}flush();return out.join(' ')};this.stage.style.gridTemplateColumns=tracks(g.rowHeader,g.x,g.columns);this.stage.style.gridTemplateRows=tracks(g.columnHeader,g.y,g.rows);this.stage.style.setProperty('--sheet-header-font',Math.max(5,12*g.scale)+'px');renderDrawings(this.stage,s,g);this.updateWindow(true)}
 build(){const s=this.sheet;if(!s)return;this.stage.replaceChildren();this.cellEls=new Map();this.colEls=new Map();this.rowEls=new Map();this.marked=[];this.windowSig='';this.merges=mergeMaps(s);const corner=document.createElement('div');corner.className='corner';corner.style.gridColumn='1';corner.style.gridRow='1';this.stage.appendChild(corner);this.applyGeometry()}
 createColHeader(c){const s=this.sheet,h=document.createElement('div');h.className='col-header';h.dataset.c=c;h.textContent=root.LocalXLSX.colName(c);h.style.gridColumn=String(c+2);h.style.gridRow='1';const rz=document.createElement('span');rz.className='resize-handle';rz.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();this.onResizeColumn?.(c,e)});h.appendChild(rz);h.addEventListener('pointerdown',e=>{if(e.target===rz)return;this.selection.selectColumn(c,s,e.shiftKey);this.refreshSelection();this.onSelectionChange?.()});return h}
 createRowHeader(r){const s=this.sheet,rh=document.createElement('div');rh.className='row-header';rh.dataset.r=r;rh.textContent=r+1;rh.style.gridColumn='1';rh.style.gridRow=String(r+2);const rz=document.createElement('span');rz.className='resize-handle';rz.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();this.onResizeRow?.(r,e)});rh.appendChild(rz);rh.addEventListener('pointerdown',e=>{if(e.target===rz)return;this.selection.selectRow(r,s,e.shiftKey);this.refreshSelection();this.onSelectionChange?.()});return rh}
 createCell(r,c,key){const s=this.sheet,el=document.createElement('div');el.className='cell';el._r=r;el._c=c;el.dataset.r=r;el.dataset.c=c;el.dataset.ref=key;const m=this.merges.top.get(key);el.style.gridColumn=m?`${c+2} / span ${m.c2-c+1}`:String(c+2);el.style.gridRow=m?`${r+2} / span ${m.r2-r+1}`:String(r+2);el.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;if(e.shiftKey)this.selection.select(r,c,s,true);else this.selection.select(r,c,s,false);this.drag=true;this.refreshSelection();this.onSelectionChange?.();this.viewport.focus({preventScroll:true});e.preventDefault()});el.addEventListener('pointerenter',e=>{if(this.updateFillTarget(r,c,e))return;if(!this.drag)return;this.selection.select(r,c,s,true);this.refreshSelection();this.onSelectionChange?.()});el.addEventListener('dblclick',()=>this.beginEdit(el));return el}
 // Visible rows/columns in the scroll viewport, plus a margin. Only these exist in the DOM: a full grid of
 // cells made every selection, edit and scroll restyle, relayout and hit-test thousands of elements.
 visibleWindow(){const s=this.sheet,g=this.geometry,vp=this.viewport,find=(axis,v)=>{let lo=0,hi=axis.length-2;while(lo<hi){const mid=(lo+hi+1)>>1;if(axis[mid]<=v)lo=mid;else hi=mid-1}return Math.max(0,lo)};let sx=0,sy=0,vw=1600,vh=1200;if(vp&&vp.clientWidth&&vp.clientHeight){const vr=vp.getBoundingClientRect(),sr=this.stage.getBoundingClientRect();sx=vr.left+vp.clientLeft-sr.left;sy=vr.top+vp.clientTop-sr.top;vw=vp.clientWidth;vh=vp.clientHeight}return{c0:Math.max(0,find(g.x,sx-g.rowHeader)-3),c1:Math.min(s.maxC,find(g.x,Math.max(0,sx+vw-g.rowHeader))+3),r0:Math.max(0,find(g.y,sy-g.columnHeader)-8),r1:Math.min(s.maxR,find(g.y,Math.max(0,sy+vh-g.columnHeader))+8)}}
 updateWindow(force){const s=this.sheet;if(!s||!this.geometry||!this.cellEls)return false;const w=this.visibleWindow(),sig=[w.r0,w.r1,w.c0,w.c1].join(':');if(!force&&sig===this.windowSig)return false;this.windowSig=sig;const enc=root.LocalXLSX.encodeRef,mm=this.merges,want=new Map();for(let r=w.r0;r<=w.r1;r++)for(let c=w.c0;c<=w.c1;c++){const key=enc(r,c);if(!mm.covered.has(key))want.set(key,[r,c])}for(const[key,q]of mm.top)if(q.r1<=w.r1&&q.r2>=w.r0&&q.c1<=w.c1&&q.c2>=w.c0)want.set(key,[q.r1,q.c1]);for(const[key,el]of this.cellEls)if(!want.has(key)&&el!==this.editing){el.remove();this.cellEls.delete(key)}for(const[c,h]of this.colEls)if(c<w.c0||c>w.c1){h.remove();this.colEls.delete(c)}for(const[r,h]of this.rowEls)if(r<w.r0||r>w.r1){h.remove();this.rowEls.delete(r)}const frag=document.createDocumentFragment(),scale=this.geometry.scale||1;for(let c=w.c0;c<=w.c1;c++)if(!this.colEls.has(c)){const h=this.createColHeader(c);this.colEls.set(c,h);frag.appendChild(h)}for(let r=w.r0;r<=w.r1;r++)if(!this.rowEls.has(r)){const h=this.createRowHeader(r);this.rowEls.set(r,h);frag.appendChild(h)}for(const[key,[r,c]]of want)if(!this.cellEls.has(key)){const el=this.createCell(r,c,key);this.renderCell(el,scale);this.cellEls.set(key,el);frag.appendChild(el)}this.stage.appendChild(frag);this.refreshSelection();if(this.fillDrag)this.refreshFillPreview();return true}
 renderCell(el,scale){const cell=this.sheet.cells.get(el.dataset.ref),text=display(cell),first=el.firstChild;if(!(el._shownText===text&&(text===''?!first||first.nodeType!==3:first===el._shownNode&&first.nodeValue===text))){el.textContent=text;el._shownText=text;el._shownNode=el.firstChild}const key=scale+'|'+(cell?JSON.stringify(cell.style||null):'-');if(el._shownStyle!==key){applyStyle(el,cell,scale);el._shownStyle=key}const ext=el===this.editing?0:overflowExtent(this.sheet,this.merges,el._r,el._c,cell,text,scale);if(ext>0){el.classList.add('overflowing');el.style.clipPath=`inset(0 -${ext}px 0 0)`}else if(el.classList.contains('overflowing')){el.classList.remove('overflowing');el.style.clipPath=''}}
 refreshCells(){if(!this.sheet||!this.cellEls)return;const scale=this.geometry?.scale||1;for(const el of this.cellEls.values())this.renderCell(el,scale)}
 refreshCell(ref){const el=this.cellEls?.get(ref);if(!el)return;const cell=this.sheet.cells.get(ref),scale=this.geometry?.scale||1;el.textContent=display(cell);el._shownText=el.textContent;el._shownNode=el.firstChild;applyStyle(el,cell,scale);el._shownStyle=scale+'|'+(cell?JSON.stringify(cell.style||null):'-')}
 refreshSelection(){const q=this.selection.range,a=this.selection.active;this.stage.querySelectorAll('.fill-handle').forEach(x=>x.remove());if(!this.cellEls||!this.sheet)return;for(const el of this.marked)el.classList.remove('selected','in-range','axis-active');const marked=this.marked=[],enc=root.LocalXLSX.encodeRef;for(const el of this.cellEls.values()){const r=el._r,c=el._c;if(r>=q.r1&&r<=q.r2&&c>=q.c1&&c<=q.c2){el.classList.add('in-range');marked.push(el)}}const act=this.cellEls.get(enc(a.r,a.c));if(act){act.classList.add('selected');marked.push(act)}for(const h of[this.colEls.get(a.c),this.rowEls.get(a.r)])if(h){h.classList.add('axis-active');marked.push(h)}if(!this.editing&&!this.fillDrag){const corner=this.cellEls.get(enc(q.r2,q.c2));if(corner){const handle=document.createElement('span');handle.className='fill-handle';handle.setAttribute('aria-label','Fill selection');handle.addEventListener('pointerdown',e=>this.beginFill(e));corner.appendChild(handle)}}}
 scrollActive(){const a=this.selection.active,g=this.geometry,vp=this.viewport;if(!g||!vp||!vp.clientWidth)return;const c=Math.max(0,Math.min(a.c,g.columns-1)),r=Math.max(0,Math.min(a.r,g.rows-1)),vr=vp.getBoundingClientRect(),sr=this.stage.getBoundingClientRect(),sx=vr.left+vp.clientLeft-sr.left,sy=vr.top+vp.clientTop-sr.top,left=g.rowHeader+g.x[c],right=g.rowHeader+g.x[c+1],top=g.columnHeader+g.y[r],bottom=g.columnHeader+g.y[r+1];let dx=0,dy=0;if(left<sx+g.rowHeader)dx=left-(sx+g.rowHeader);else if(right>sx+vp.clientWidth)dx=Math.min(right-(sx+vp.clientWidth),left-(sx+g.rowHeader));if(top<sy+g.columnHeader)dy=top-(sy+g.columnHeader);else if(bottom>sy+vp.clientHeight)dy=Math.min(bottom-(sy+vp.clientHeight),top-(sy+g.columnHeader));if(dx)vp.scrollLeft+=dx;if(dy)vp.scrollTop+=dy;this.updateWindow()}
 beginEdit(el,initial){if(this.editing)return;this.editing=el;const original=initial!==undefined?String(initial):display(this.sheet.cells.get(el.dataset.ref));el.contentEditable='true';el.classList.add('editing');el.textContent=original;el.focus({preventScroll:true});const range=document.createRange(),sel=getSelection();range.selectNodeContents(el);range.collapse(false);sel.removeAllRanges();sel.addRange(range);const finish=commit=>{if(this.editing!==el)return;const value=el.innerText,r=+el.dataset.r,c=+el.dataset.c;this.editing=null;el.contentEditable='false';el.classList.remove('editing');el.onblur=null;el.onkeydown=null;if(commit)this.onCommit?.(value,r,c);else{this.refreshCell(el.dataset.ref);this.refreshSelection()}};el.onblur=()=>finish(true);el.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();finish(true)}else if(e.key==='Escape'){e.preventDefault();finish(false)}}}
 startTyping(ch){const a=this.selection.active,el=this.stage.querySelector(`.cell[data-r="${a.r}"][data-c="${a.c}"]`);if(el)this.beginEdit(el,ch)}
}
// Print: the used range of a sheet as a plain table (values as displayed, styles, merges, column widths).
function colIndex(letters){let n=0;for(const ch of letters)n=n*26+ch.charCodeAt(0)-64;return n-1}
function printTable(sheet){if(!sheet?.cells)return null;const mm=mergeMaps(sheet),G=NS.GridGeometry;let maxR=-1,maxC=-1;for(const[ref,cell]of sheet.cells){const m=/^([A-Z]+)(\d+)$/.exec(ref);if(!m)continue;const st=cell?.style||{};if(display(cell)===''&&!st.fill&&!st.border)continue;maxR=Math.max(maxR,Number(m[2])-1);maxC=Math.max(maxC,colIndex(m[1]))}const drawings=sheet.drawings||[];for(const d of drawings)for(const m of[d.from,d.to])if(m){maxR=Math.max(maxR,Number(m.r)||0);maxC=Math.max(maxC,Number(m.c)||0)}if(maxR<0)return null;for(const[key,q]of mm.top){const m=/^([A-Z]+)(\d+)$/.exec(key);if(m&&Number(m[2])-1<=maxR&&colIndex(m[1])<=maxC){maxR=Math.max(maxR,q.r2);maxC=Math.max(maxC,q.c2)}}const table=document.createElement('table'),cg=document.createElement('colgroup'),body=document.createElement('tbody');table.className='ss-print-table'+(sheet.printGridlines?' ss-print-grid':'');let width=0;for(let c=0;c<=maxC;c++){const w=G.colWidth(sheet,c),col=document.createElement('col');width+=w;col.style.width=w+'px';cg.appendChild(col)}table.style.width=width+'px';table.appendChild(cg);for(let r=0;r<=maxR;r++){const tr=document.createElement('tr');tr.style.height=G.rowHeight(sheet,r)+'px';for(let c=0;c<=maxC;c++){const key=root.LocalXLSX.encodeRef(r,c);if(mm.covered.has(key))continue;const td=document.createElement('td'),cell=sheet.cells.get(key),m=mm.top.get(key);if(m){td.colSpan=m.c2-c+1;td.rowSpan=m.r2-r+1}td.textContent=display(cell);applyStyle(td,cell,1);const ext=m?0:overflowExtent(sheet,mm,r,c,cell,td.textContent,1);if(ext>0){const st=cell.style||{},span=document.createElement('span'),pad='2px';span.className='ss-print-overflow';span.textContent=td.textContent;td.textContent='';span.style.left='4px';span.style.maxWidth=Math.max(1,G.colWidth(sheet,c)+ext-4)+'px';if(st.vertical==='top')span.style.top=pad;else if(st.vertical==='center'){span.style.top='50%';span.style.transform='translateY(-50%)'}else span.style.bottom=pad;td.classList.add('ss-print-overflowing');td.appendChild(span)}tr.appendChild(td)}body.appendChild(tr)}table.appendChild(body);let node=table;if(drawings.length){node=document.createElement('div');node.className='ss-print-wrap';node.style.width=width+'px';node.appendChild(table);const g=G.build(sheet,1);renderDrawings(node,sheet,{...g,rowHeader:0,columnHeader:0})}return{table:node,width,rows:maxR+1,columns:maxC+1}}
NS.GridSurface=GridSurface;NS.GridPrintModel=Object.freeze({mergeMaps,display,overflowExtent});NS.GridDisplay=Object.freeze({display,applyStyle});NS.GridPrint=Object.freeze({printTable});
})(globalThis);
