(function(root){'use strict';
const NS=root.InkDOS2Spreadsheets=root.InkDOS2Spreadsheets||{};
function display(cell){if(!cell)return'';const effective=cell.calculated!==undefined&&cell.calculated!==null?cell.calculated:cell.v;if(cell.style?.hideZero&&Number(effective)===0)return'';if(cell.calculated!==undefined&&cell.calculated!==null)return String(cell.calculated);if(cell.f){const cached=cell.display;if(cached!==undefined&&cached!==null&&cached!==''&&String(cached)!=='='+cell.f)return String(cached);return'='+cell.f}return String(cell.display??cell.v??'')}
function borderCss(side){if(!side)return'';const widths={hair:1,thin:1,medium:2,thick:3,double:3,dashed:1,dotted:1,mediumDashed:2,mediumDashDot:2},styles={dashed:'dashed',dotted:'dotted',double:'double'};return`${widths[side.style]||1}px ${styles[side.style]||'solid'} ${side.color||'#70757d'}`}
function applyStyle(el,cell,scale=1){for(const property of['fontSize','fontFamily','fontWeight','fontStyle','textDecoration','color','backgroundColor','textAlign','transform','borderLeft','borderRight','borderTop','borderBottom','justifyContent','alignItems','padding'])el.style[property]='';const st=cell?.style||{},f=st.font||{},z=Math.max(.25,Math.min(4,Number(scale)||1));el.style.fontSize=Math.max(4,(Number(f.size)||11)*1.333*z)+'px';el.style.padding=`${Math.max(.5,2*z)}px ${Math.max(1,4*z)}px`;if(f.name)el.style.fontFamily=`"${f.name}",Calibri,Arial,sans-serif`;if(f.bold)el.style.fontWeight='700';if(f.italic)el.style.fontStyle='italic';const dec=[];if(f.underline)dec.push('underline');if(f.strike)dec.push('line-through');if(dec.length)el.style.textDecoration=dec.join(' ');if(f.color)el.style.color=f.color;if(st.fill)el.style.backgroundColor=st.fill;if(st.align&&st.align!=='general'){el.dataset.halign=st.align;el.style.textAlign=st.align}else delete el.dataset.halign;if(st.vertical==='top')el.style.alignItems='flex-start';else if(st.vertical==='bottom')el.style.alignItems='flex-end';else if(st.vertical==='center')el.style.alignItems='center';if(st.wrap)el.dataset.wrap='1';else delete el.dataset.wrap;if(st.rotation)el.style.transform=`rotate(${st.rotation>90?st.rotation-180:st.rotation}deg)`;for(const side of['left','right','top','bottom']){const v=borderCss(st.border?.[side]);if(v)el.style['border'+side[0].toUpperCase()+side.slice(1)]=v}}
function mergeMaps(sheet){const top=new Map(),covered=new Set();for(const m of sheet.merges||[]){try{const q=root.LocalXLSX.decodeRange(m),key=root.LocalXLSX.encodeRef(q.r1,q.c1);top.set(key,q);for(let r=q.r1;r<=q.r2;r++)for(let c=q.c1;c<=q.c2;c++)if(r!==q.r1||c!==q.c1)covered.add(root.LocalXLSX.encodeRef(r,c))}catch(_){}}return{top,covered}}
function drawingPoint(marker,g){if(!marker)return null;const c=Math.max(0,Math.min(g.columns-1,Number(marker.c)||0)),r=Math.max(0,Math.min(g.rows-1,Number(marker.r)||0));return{x:g.rowHeader+g.x[c]+(Number(marker.x)||0)*g.scale,y:g.columnHeader+g.y[r]+(Number(marker.y)||0)*g.scale}}
function renderDrawings(stage,sheet,g){stage.querySelector('.drawing-layer')?.remove();const drawings=sheet?.drawings||[];if(!drawings.length||!g)return;const layer=document.createElement('div');layer.className='drawing-layer';for(const drawing of drawings){const a=drawingPoint(drawing.from,g),b=drawingPoint(drawing.to,g);if(!a)continue;const item=drawing.kind==='image'?document.createElement('img'):document.createElement('div');item.className='sheet-drawing '+(drawing.kind||'shape');item.style.left=a.x+'px';item.style.top=a.y+'px';let width=Number(drawing.size?.w)||((b?.x||a.x+120)-a.x),height=Number(drawing.size?.h)||((b?.y||a.y+60)-a.y);if(drawing.size){width*=g.scale;height*=g.scale}item.style.width=Math.max(1,width)+'px';item.style.height=Math.max(1,height)+'px';if(drawing.kind==='image'){item.src=drawing.url||'';item.alt=drawing.name||'';item.draggable=false}else{item.textContent=drawing.text||'';item.style.fontSize=Math.max(7,(Number(drawing.fontSize)||10)*g.scale)+'px';item.style.fontWeight=drawing.bold?'700':'400';item.style.background=drawing.fill&&drawing.fill!=='transparent'?drawing.fill:'transparent';if(drawing.line&&drawing.line!=='#00000000'&&drawing.lineWidth!==0)item.style.border=`${Math.max(1,(Number(drawing.lineWidth)||1)*g.scale)}px solid ${drawing.line}`}layer.appendChild(item)}stage.appendChild(layer)}
class GridSurface{
 constructor({viewport,stage,selection,onSelectionChange,onCommit,onResizeColumn,onResizeRow}={}){this.viewport=viewport;this.stage=stage;this.selection=selection;this.onSelectionChange=onSelectionChange;this.onCommit=onCommit;this.onResizeColumn=onResizeColumn;this.onResizeRow=onResizeRow;this.sheet=null;this.geometry=null;this.signature='';this.drag=false;this.editing=null;window.addEventListener('pointerup',()=>{this.drag=false});window.addEventListener('pointercancel',()=>{this.drag=false})}
 setSheet(sheet,geometry){this.sheet=sheet;this.geometry=geometry;const sig=[sheet.name,sheet.maxR,sheet.maxC,(sheet.merges||[]).join('|')].join('::');if(sig!==this.signature){this.build();this.signature=sig}else this.applyGeometry();this.refreshCells();this.refreshSelection()}
 applyGeometry(){const g=this.geometry,s=this.sheet;if(!g||!s)return;const cols=[`${g.rowHeader}px`];for(let c=0;c<g.columns;c++)cols.push(`${(g.x[c+1]-g.x[c]).toFixed(3)}px`);const rows=[`${g.columnHeader}px`];for(let r=0;r<g.rows;r++)rows.push(`${(g.y[r+1]-g.y[r]).toFixed(3)}px`);this.stage.style.gridTemplateColumns=cols.join(' ');this.stage.style.gridTemplateRows=rows.join(' ');this.stage.style.setProperty('--sheet-header-font',Math.max(5,12*g.scale)+'px');renderDrawings(this.stage,s,g)}
 build(){const s=this.sheet;if(!s)return;this.stage.replaceChildren();const frag=document.createDocumentFragment(),mm=mergeMaps(s);const corner=document.createElement('div');corner.className='corner';corner.style.gridColumn='1';corner.style.gridRow='1';frag.appendChild(corner);for(let c=0;c<=s.maxC;c++){const h=document.createElement('div');h.className='col-header';h.dataset.c=c;h.textContent=root.LocalXLSX.colName(c);h.style.gridColumn=String(c+2);h.style.gridRow='1';const rz=document.createElement('span');rz.className='resize-handle';rz.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();this.onResizeColumn?.(c,e)});h.appendChild(rz);h.addEventListener('pointerdown',e=>{if(e.target===rz)return;this.selection.selectColumn(c,s,e.shiftKey);this.refreshSelection();this.onSelectionChange?.()});frag.appendChild(h)}for(let r=0;r<=s.maxR;r++){const rh=document.createElement('div');rh.className='row-header';rh.dataset.r=r;rh.textContent=r+1;rh.style.gridColumn='1';rh.style.gridRow=String(r+2);const rz=document.createElement('span');rz.className='resize-handle';rz.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();this.onResizeRow?.(r,e)});rh.appendChild(rz);rh.addEventListener('pointerdown',e=>{if(e.target===rz)return;this.selection.selectRow(r,s,e.shiftKey);this.refreshSelection();this.onSelectionChange?.()});frag.appendChild(rh);for(let c=0;c<=s.maxC;c++){const key=root.LocalXLSX.encodeRef(r,c);if(mm.covered.has(key))continue;const el=document.createElement('div');el.className='cell';el.dataset.r=r;el.dataset.c=c;el.dataset.ref=key;const m=mm.top.get(key);el.style.gridColumn=m?`${c+2} / span ${m.c2-c+1}`:String(c+2);el.style.gridRow=m?`${r+2} / span ${m.r2-r+1}`:String(r+2);el.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;if(e.shiftKey)this.selection.select(r,c,s,true);else this.selection.select(r,c,s,false);this.drag=true;this.refreshSelection();this.onSelectionChange?.();this.viewport.focus({preventScroll:true});e.preventDefault()});el.addEventListener('pointerenter',()=>{if(!this.drag)return;this.selection.select(r,c,s,true);this.refreshSelection();this.onSelectionChange?.()});el.addEventListener('dblclick',()=>this.beginEdit(el));frag.appendChild(el)}}this.stage.appendChild(frag);this.applyGeometry()}
 refreshCells(){if(!this.sheet)return;const scale=this.geometry?.scale||1;for(const el of this.stage.querySelectorAll('.cell')){const cell=this.sheet.cells.get(el.dataset.ref);el.textContent=display(cell);applyStyle(el,cell,scale)}}
 refreshCell(ref){const el=this.stage.querySelector(`.cell[data-ref="${CSS.escape(ref)}"]`);if(!el)return;const cell=this.sheet.cells.get(ref);el.textContent=display(cell);applyStyle(el,cell,this.geometry?.scale||1)}
 refreshSelection(){const q=this.selection.range,a=this.selection.active;this.stage.querySelectorAll('.cell.selected,.cell.in-range,.col-header.axis-active,.row-header.axis-active').forEach(x=>x.classList.remove('selected','in-range','axis-active'));for(const el of this.stage.querySelectorAll('.cell')){const r=+el.dataset.r,c=+el.dataset.c;if(r>=q.r1&&r<=q.r2&&c>=q.c1&&c<=q.c2)el.classList.add('in-range');if(r===a.r&&c===a.c)el.classList.add('selected')}this.stage.querySelector(`.col-header[data-c="${a.c}"]`)?.classList.add('axis-active');this.stage.querySelector(`.row-header[data-r="${a.r}"]`)?.classList.add('axis-active')}
 scrollActive(){const a=this.selection.active;this.stage.querySelector(`.cell[data-r="${a.r}"][data-c="${a.c}"]`)?.scrollIntoView({block:'nearest',inline:'nearest'})}
 beginEdit(el,initial){if(this.editing)return;this.editing=el;const original=initial!==undefined?String(initial):display(this.sheet.cells.get(el.dataset.ref));el.contentEditable='true';el.classList.add('editing');el.textContent=original;el.focus({preventScroll:true});const range=document.createRange(),sel=getSelection();range.selectNodeContents(el);range.collapse(false);sel.removeAllRanges();sel.addRange(range);const finish=commit=>{if(this.editing!==el)return;const value=el.innerText,r=+el.dataset.r,c=+el.dataset.c;this.editing=null;el.contentEditable='false';el.classList.remove('editing');el.onblur=null;el.onkeydown=null;if(commit)this.onCommit?.(value,r,c);else{this.refreshCell(el.dataset.ref);this.refreshSelection()}};el.onblur=()=>finish(true);el.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();finish(true)}else if(e.key==='Escape'){e.preventDefault();finish(false)}}}
 startTyping(ch){const a=this.selection.active,el=this.stage.querySelector(`.cell[data-r="${a.r}"][data-c="${a.c}"]`);if(el)this.beginEdit(el,ch)}
}
NS.GridSurface=GridSurface;NS.GridDisplay=Object.freeze({display,applyStyle});
})(globalThis);
