(function(g){'use strict';
const NS=g.InkDOS2Epub=g.InkDOS2Epub||{};
const PATH='META-INF/inkdos-annotations.json',SCHEMA=1,MAX_BYTES=2*1024*1024,MAX_HIGHLIGHTS=5000,MAX_SEGMENTS=20000;
function cleanColor(v){const s=String(v||'yellow').toLowerCase();return ['yellow','green','pink','blue'].includes(s)?s:'yellow'}
function normalize(raw){const hs=[];let segCount=0;for(const h of Array.isArray(raw&&raw.highlights)?raw.highlights:[]){if(hs.length>=MAX_HIGHLIGHTS)break;const segs=[];for(const s of Array.isArray(h.segments)?h.segments:[]){if(segCount>=MAX_SEGMENTS)break;const anchor=String(s&&s.anchor||'');const start=Math.max(0,Number(s&&s.start)||0),end=Math.max(start,Number(s&&s.end)||0);if(anchor&&end>start){segs.push(Object.freeze({anchor,start,end}));segCount++}}if(segs.length)hs.push(Object.freeze({id:String(h.id||('h'+hs.length)),color:cleanColor(h.color),segments:Object.freeze(segs)}))}return Object.freeze({schemaVersion:SCHEMA,highlights:Object.freeze(hs)})}
async function readEmbedded(pkg){if(!pkg||!pkg.has(PATH))return normalize({highlights:[]});try{const bytes=await pkg.read(PATH);if(bytes.byteLength>MAX_BYTES)return normalize({highlights:[]});const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes),raw=JSON.parse(text);if(!raw||Number(raw.schemaVersion)!==SCHEMA)return normalize({highlights:[]});return normalize(raw)}catch(_){return normalize({highlights:[]})}}
function serialize(highlights){const data={schemaVersion:SCHEMA,format:'inkdos-epub-annotations',createdAt:new Date().toISOString(),highlights:normalize({highlights}).highlights.map(h=>({id:h.id,color:h.color,segments:h.segments.map(s=>({...s}))}))};return new TextEncoder().encode(JSON.stringify(data,null,2))}
function overlap(a,b){return a.anchor===b.anchor&&a.start<b.end&&b.start<a.end}
function add(highlights,segments,color){const cleanSegs=normalize({highlights:[{id:'tmp',color,segments}]}).highlights[0]?.segments||[];if(!cleanSegs.length)return highlights.slice();const kept=(highlights||[]).filter(h=>!h.segments.some(a=>cleanSegs.some(b=>overlap(a,b))));kept.push({id:'h-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),color:cleanColor(color),segments:cleanSegs.map(s=>({...s}))});return kept}
function removeOverlapping(highlights,segments){const cleanSegs=normalize({highlights:[{id:'tmp',segments}]}).highlights[0]?.segments||[];if(!cleanSegs.length)return highlights.slice();return (highlights||[]).filter(h=>!h.segments.some(a=>cleanSegs.some(b=>overlap(a,b))))}
NS.AnnotationStore={PATH,readEmbedded,serialize,normalize,add,removeOverlapping,cleanColor};
})(globalThis);
