(function(g){'use strict';
const NS=g.InkDOS2Epub=g.InkDOS2Epub||{};
const PATH='META-INF/inkdos-annotations.json',SCHEMA=2,MAX_BYTES=2*1024*1024,MAX_HIGHLIGHTS=5000,MAX_SEGMENTS=20000,MAX_NOTES=1000,MAX_NOTE_CHARS=4000,MAX_QUOTE_CHARS=600;
function cleanColor(v){const s=String(v||'yellow').toLowerCase();return ['yellow','green','pink','blue'].includes(s)?s:'yellow'}
function cleanText(v,max){return String(v||'').replace(/\r\n?/g,'\n').slice(0,max)}
function normalizeHighlightList(raw){const hs=[];let segCount=0;for(const h of Array.isArray(raw&&raw.highlights)?raw.highlights:[]){if(hs.length>=MAX_HIGHLIGHTS)break;const segs=[];for(const s of Array.isArray(h.segments)?h.segments:[]){if(segCount>=MAX_SEGMENTS)break;const anchor=String(s&&s.anchor||'');const start=Math.max(0,Number(s&&s.start)||0),end=Math.max(start,Number(s&&s.end)||0);if(anchor&&end>start){segs.push(Object.freeze({anchor,start,end}));segCount++}}if(segs.length)hs.push(Object.freeze({id:String(h.id||('h'+hs.length)),color:cleanColor(h.color),segments:Object.freeze(segs)}))}return hs}
function normalizeNoteList(raw){const out=[];for(const n of Array.isArray(raw&&raw.notes)?raw.notes:[]){if(out.length>=MAX_NOTES)break;const anchor=String(n&&n.anchor||''),text=cleanText(n&&n.text,MAX_NOTE_CHARS).trim();if(!anchor||!text)continue;const start=Math.max(0,Number(n&&n.start)||0),end=Math.max(start,Number(n&&n.end)||start);out.push(Object.freeze({id:String(n.id||('n'+out.length)),anchor,start,end,chapter:Math.max(1,Number(n.chapter)||1),path:String(n.path||''),fragment:String(n.fragment||''),source:n.source==='bookmark'?'bookmark':'passage',bookmarkId:String(n.bookmarkId||''),quote:cleanText(n.quote,MAX_QUOTE_CHARS),text,createdAt:String(n.createdAt||''),updatedAt:String(n.updatedAt||n.createdAt||'')}))}return out}
function normalize(raw){return Object.freeze({schemaVersion:SCHEMA,highlights:Object.freeze(normalizeHighlightList(raw)),notes:Object.freeze(normalizeNoteList(raw))})}
async function readEmbedded(pkg){if(!pkg||!pkg.has(PATH))return normalize({highlights:[],notes:[]});try{const bytes=await pkg.read(PATH);if(bytes.byteLength>MAX_BYTES)return normalize({highlights:[],notes:[]});const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes),raw=JSON.parse(text),version=Number(raw&&raw.schemaVersion);if(version!==1&&version!==SCHEMA)return normalize({highlights:[],notes:[]});return normalize({highlights:raw.highlights,notes:version>=2?raw.notes:[]})}catch(_){return normalize({highlights:[],notes:[]})}}
function serialize(highlights,notes=[]){const norm=normalize({highlights,notes});const data={schemaVersion:SCHEMA,format:'inkdos-epub-annotations',createdAt:new Date().toISOString(),highlights:norm.highlights.map(h=>({id:h.id,color:h.color,segments:h.segments.map(s=>({...s}))})),notes:norm.notes.map(n=>({...n}))};return new TextEncoder().encode(JSON.stringify(data,null,2))}
function overlap(a,b){return a.anchor===b.anchor&&a.start<b.end&&b.start<a.end}
function add(highlights,segments,color){const cleanSegs=normalize({highlights:[{id:'tmp',color,segments}]}).highlights[0]?.segments||[];if(!cleanSegs.length)return highlights.slice();const kept=(highlights||[]).filter(h=>!h.segments.some(a=>cleanSegs.some(b=>overlap(a,b))));kept.push({id:'h-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),color:cleanColor(color),segments:cleanSegs.map(s=>({...s}))});return kept}
function removeOverlapping(highlights,segments){const cleanSegs=normalize({highlights:[{id:'tmp',segments}]}).highlights[0]?.segments||[];if(!cleanSegs.length)return highlights.slice();return (highlights||[]).filter(h=>!h.segments.some(a=>cleanSegs.some(b=>overlap(a,b))))}
function note(input){return normalize({notes:[Object.assign({id:'n-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},input)]}).notes[0]||null}
NS.AnnotationStore={PATH,SCHEMA,readEmbedded,serialize,normalize,add,removeOverlapping,cleanColor,note,MAX_NOTES,MAX_NOTE_CHARS};
})(globalThis);
