(function(global){'use strict';
const NS=global.InkDOS2PdfP4=global.InkDOS2PdfP4||{};
const MODES=Object.freeze(['none','highlight','note','delete']);
const COLORS=Object.freeze(['#ffd84d','#9fdf9f','#8ec5ff','#ff9ec4']);
function create({extensions,modeController,chrome,root=document.documentElement}={}){let mode='none',highlightColor=COLORS[0],unsubscribe=null,selectionHandler=null;const cleanup=[];let highlightBtn=null,noteBtn=null,deleteBtn=null,palette=null;
 function valid(next){return MODES.includes(next)?next:'none'}
 function status(){if(mode==='highlight')chrome.status('Highlight mode armed');else if(mode==='note')chrome.status('Note mode armed');else if(mode==='delete')chrome.status('Delete annotation mode armed')}
 function syncUi(){root.dataset.pdfPersistentAnnotationMode=mode;for(const [button,name] of [[highlightBtn,'highlight'],[noteBtn,'note'],[deleteBtn,'delete']])if(button){const active=mode===name;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))}if(palette)palette.hidden=mode!=='highlight';if(highlightBtn)highlightBtn.dataset.highlightColor=highlightColor}
 function setMode(next){next=valid(next);if(next===mode&&next!=='none')next='none';mode=next;if(mode==='none'){extensions.setTool('none');syncUi();return mode}if(modeController.mode!=='annotate')modeController.setMode('annotate');modeController.setTool('select');extensions.setTool(mode==='note'?'comment':mode);syncUi();status();return mode}
 function setHighlightColor(color){if(!COLORS.includes(color))return false;highlightColor=color;extensions.setHighlightColor(color);if(mode!=='highlight'){mode='highlight';if(modeController.mode!=='annotate')modeController.setMode('annotate');modeController.setTool('select');extensions.setTool('highlight')}syncUi();chrome.status('Highlight mode armed');return true}
 function openComment(){return extensions.openComment()}
 async function deleteSelectedAnnotations(){const removed=await extensions.deleteSelection();if(!removed)chrome.status('No saved annotation overlaps this selection.');return removed}
 function icon(path){return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${path}"/></svg>`}
 function makeButton(id,label,path){const button=document.createElement('button');button.id=id;button.className='tool-btn';button.type='button';button.setAttribute('aria-label',label);button.setAttribute('aria-pressed','false');button.innerHTML=icon(path)+`<span class="tool-label">${label}</span>`;return button}
 function buildUi(){const oldHighlight=document.getElementById('highlightToolBtn'),oldComment=document.getElementById('commentToolBtn'),oldDelete=document.getElementById('deleteAnnotationBtn'),anchor=oldComment||oldHighlight;if(!anchor)return false;for(const old of [oldHighlight,oldComment,oldDelete])if(old)old.hidden=true;highlightBtn=makeButton('persistentHighlightBtn','Highlight','m5 15 8-8 4 4-8 8H5zM13 7l2-2 4 4-2 2M4 20h8');noteBtn=makeButton('persistentNoteBtn','Note','M5 5h14v11H9l-4 4zM8 9h8M8 12h5');deleteBtn=makeButton('persistentDeleteBtn','Delete','M5 7h14M9 7V4h6v3M8 10v8M12 10v8M16 10v8M7 7l1 13h8l1-13');anchor.insertAdjacentElement('afterend',deleteBtn);anchor.insertAdjacentElement('afterend',noteBtn);anchor.insertAdjacentElement('afterend',highlightBtn);palette=document.createElement('div');palette.className='pdf-annotation-mode-palette';palette.setAttribute('role','group');palette.setAttribute('aria-label','Highlight color');for(const color of COLORS){const swatch=document.createElement('button');swatch.type='button';swatch.className='pdf-highlight-swatch';swatch.dataset.pdfHighlightColor=color;swatch.setAttribute('aria-label',`Highlight ${color}`);swatch.style.background=color;swatch.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setHighlightColor(color)});palette.append(swatch)}highlightBtn.insertAdjacentElement('afterend',palette);const style=document.createElement('style');style.dataset.pdfPersistentAnnotationModes='1';style.textContent='.pdf-annotation-mode-palette{display:flex;align-items:center;gap:5px}.pdf-annotation-mode-palette[hidden]{display:none!important}.pdf-highlight-swatch{width:28px;height:28px;min-width:28px;border:1px solid var(--line-strong);border-radius:50%;padding:0;cursor:pointer}:root[data-pdf-persistent-annotation-mode]:not([data-pdf-persistent-annotation-mode="none"]) #selectToolBtn.active{background:var(--control-bg);border-color:var(--line);color:var(--control-fg)}';document.head.append(style);cleanup.push(()=>style.remove());return true}
 function bind(button,name){const handler=e=>{e.preventDefault();e.stopPropagation();setMode(name)};button?.addEventListener('click',handler,true);cleanup.push(()=>button?.removeEventListener('click',handler,true))}
 function install(){if(!buildUi())return false;extensions.setHighlightColor(highlightColor);bind(highlightBtn,'highlight');bind(noteBtn,'note');bind(deleteBtn,'delete');selectionHandler=()=>{const selection=global.getSelection?.();root.dataset.pdfAnnotationSelection=selection&&!selection.isCollapsed?'1':'0'};document.addEventListener('selectionchange',selectionHandler);cleanup.push(()=>document.removeEventListener('selectionchange',selectionHandler));unsubscribe=modeController.subscribe(snapshot=>{if(snapshot.mode==='view'&&mode!=='none'){mode='none';extensions.setTool('none');syncUi()}});syncUi();return true}
 function destroy(){unsubscribe?.();for(const fn of cleanup.splice(0))fn();for(const node of [highlightBtn,noteBtn,deleteBtn,palette])node?.remove();delete root.dataset.pdfPersistentAnnotationMode;delete root.dataset.pdfAnnotationSelection}
 return Object.freeze({install,destroy,setMode,setHighlightColor,openComment,deleteSelectedAnnotations,get mode(){return mode},get highlightColor(){return highlightColor}})
}
NS.AnnotationModes=Object.freeze({create});
})(globalThis);
