(function(global){'use strict';
const NS=global.InkDOS2PdfP4=global.InkDOS2PdfP4||{},$=id=>document.getElementById(id);
const COMMAND_IDS=Object.freeze(['pdf.pages.panel.toggle','pdf.pages.panel.close','pdf.pages.move','pdf.pages.rotate','pdf.pages.delete','pdf.pages.extract','pdf.pages.split','pdf.pages.merge.choose','pdf.pages.merge.files']);
function create({session,getDocument,fileOpen,editor,chrome,layout,navigation,registry}={}){let panel=null,button=null,mergeInput=null,runtime=null,actions=null;const resize=()=>{if(panel&&!panel.hidden)position()};
 function setPanelStatus(text){const node=$('pageToolsStatus');if(node)node.textContent=text||''}
 function position(){if(!panel||panel.hidden||!button)return;const a=button.getBoundingClientRect(),w=panel.offsetWidth||360,h=panel.offsetHeight||420;panel.style.left=Math.max(8,Math.min(innerWidth-w-8,a.left))+'px';panel.style.top=Math.max(8,Math.min(innerHeight-h-8,a.bottom+6))+'px'}
 function open(){if(!session.active||runtime?.state().busy)return false;navigation?.close();panel.hidden=false;syncEnabled();position();return true}
 function close(){if(panel)panel.hidden=true;registry?.sync('pdf.pages.panel.close');return true}
 function resetDocument(){close();if(mergeInput)mergeInput.value='';setPanelStatus('');syncEnabled()}
 function syncEnabled(){if(!button)return;const s=runtime?.state()||{active:!!session.active,busy:false,pageCount:layout.pageCount||session.pageCount||0,currentPage:layout.currentPage||1};const label=$('pageToolsCurrent'),target=$('pageMoveTarget');if(label)label.textContent=s.active?`Page ${s.currentPage} of ${s.pageCount}`:'No PDF open';if(target){target.min='1';target.max=String(Math.max(1,s.pageCount));if(document.activeElement!==target)target.value=String(s.currentPage)}registry?.sync()}
 function build(){const nav=$('navPanelBtn');if(!nav||$('pageToolsBtn'))return;button=document.createElement('button');button.id='pageToolsBtn';button.className='tool-btn';button.type='button';button.disabled=true;button.dataset.command='pdf.pages.panel.toggle';button.setAttribute('aria-label','PDF page tools');button.innerHTML='<svg viewBox="0 0 24 24"><path d="M6 4h10v13H6z"/><path d="M9 7h10v13H9"/><path d="M12 10h4M12 14h4"/></svg><span class="tool-label">Pages</span>';nav.insertAdjacentElement('afterend',button);panel=document.createElement('section');panel.id='pageToolsPanel';panel.className='page-tools-panel';panel.hidden=true;panel.setAttribute('aria-label','PDF page tools');panel.innerHTML='<div class="page-tools-head"><strong>Page tools</strong><button id="closePageTools" data-command="pdf.pages.panel.close" class="page-tools-close" type="button" aria-label="Close page tools">×</button></div><div class="page-tools-section"><div class="page-tools-label">Current page</div><div class="page-tools-current"><span id="pageToolsCurrent">No PDF open</span></div><div class="page-tools-row"><input id="pageMoveTarget" type="number" min="1" value="1" aria-label="Move current page to position"><button id="pageMoveBtn" data-command="pdf.pages.move" class="page-tools-action" type="button">Move to</button><button id="pageRotateBtn" data-command="pdf.pages.rotate" class="page-tools-action" type="button">Rotate 90°</button></div><div class="page-tools-row"><button id="pageDeleteBtn" data-command="pdf.pages.delete" class="page-tools-action danger" type="button">Delete page</button><button id="pageExtractBtn" data-command="pdf.pages.extract" class="page-tools-action" type="button">Extract page</button></div></div><div class="page-tools-section"><div class="page-tools-label">Document</div><div class="page-tools-row"><button id="pageSplitBtn" data-command="pdf.pages.split" class="page-tools-action" type="button">Split after this page</button><button id="pageMergeBtn" data-command="pdf.pages.merge.choose" class="page-tools-action primary" type="button">Merge PDFs…</button></div><p class="page-tools-note">Page operations run locally. Merge appends selected PDFs. Split exports two PDFs inside one ZIP. Advanced PDF structures from appended/extracted documents may not round-trip perfectly.</p></div><div id="pageToolsStatus" class="page-tools-status"></div>';document.querySelector('.app-shell')?.append(panel);mergeInput=document.createElement('input');mergeInput.type='file';mergeInput.accept='.pdf,application/pdf';mergeInput.multiple=true;mergeInput.hidden=true;document.body.append(mergeInput)}
 function createActions(){runtime=NS.PageToolsRuntime.create({session,getDocument,fileOpen,editor,chrome,layout,onState:syncEnabled,onStatus:setPanelStatus});actions=Object.freeze({move:NS.PageMoveAction.create(runtime),rotate:NS.PageRotateAction.create(runtime),deletePage:NS.PageDeleteAction.create(runtime),extract:NS.PageExtractAction.create(runtime),split:NS.PageSplitAction.create(runtime),merge:NS.PageMergeAction.create(runtime)})}
 function registerCommands(){registry.register('pdf.pages.panel.toggle',{isEnabled:()=>!!session.active&&!runtime.state().busy,execute:()=>panel.hidden?open():close()});registry.register('pdf.pages.panel.close',{isEnabled:()=>!!panel&&!panel.hidden,execute:close});registry.register('pdf.pages.move',{isEnabled:actions.move.isEnabled,execute:()=>actions.move.execute(Number($('pageMoveTarget')?.value))});registry.register('pdf.pages.rotate',{isEnabled:actions.rotate.isEnabled,execute:actions.rotate.execute});registry.register('pdf.pages.delete',{isEnabled:actions.deletePage.isEnabled,execute:actions.deletePage.execute});registry.register('pdf.pages.extract',{isEnabled:actions.extract.isEnabled,execute:actions.extract.execute});registry.register('pdf.pages.split',{isEnabled:actions.split.isEnabled,execute:actions.split.execute});registry.register('pdf.pages.merge.choose',{isEnabled:actions.merge.isEnabled,execute:()=>{mergeInput.click();return true}});registry.register('pdf.pages.merge.files',{isEnabled:actions.merge.isEnabled,execute:files=>actions.merge.execute(files)})}
 function bindControls(){registry.bindElement(button,'pdf.pages.panel.toggle');for(const el of panel.querySelectorAll('[data-command]'))registry.bindElement(el,el.dataset.command);mergeInput.onchange=async()=>{const files=Array.from(mergeInput.files||[]);try{await registry.execute('pdf.pages.merge.files',files)}finally{mergeInput.value=''}}}
 function install(){build();if(!button)return;createActions();registerCommands();bindControls();global.addEventListener('resize',resize,{passive:true});syncEnabled()}
 function destroy(){global.removeEventListener('resize',resize);for(const id of COMMAND_IDS)registry.unregister(id);if(button)registry.unbindElement(button);for(const el of panel?.querySelectorAll('[data-command]')||[])registry.unbindElement(el);button?.remove();panel?.remove();mergeInput?.remove();button=panel=mergeInput=null;actions=runtime=null}
 return Object.freeze({install,open,close,resetDocument,syncEnabled,destroy,inspect:()=>Object.freeze({busy:!!runtime?.state().busy,open:!!panel&&!panel.hidden,currentPage:layout.currentPage||1,pageCount:layout.pageCount||0,commands:COMMAND_IDS.slice()})})
}
NS.PageTools=Object.freeze({create,COMMAND_IDS});
})(globalThis);
