(function(global){'use strict';
const NS=global.InkDOS2PdfP4=global.InkDOS2PdfP4||{},$=id=>document.getElementById(id);
function cleanName(name,ext){let n=String(name||('document'+ext)).trim()||('document'+ext);n=n.replace(/[\\/:*?"<>|]+/g,'-');if(!n.toLowerCase().endsWith(ext))n+=ext;return n}
function baseName(name){return String(name||'document.pdf').replace(/\.pdf$/i,'').replace(/[\\/:*?"<>|]+/g,'-')||'document'}
function isAppleTouchHost(){const nav=global.navigator||{},ua=String(nav.userAgent||''),platform=String(nav.platform||''),touches=Number(nav.maxTouchPoints||0);return /iPad|iPhone|iPod/i.test(ua)||(platform==='MacIntel'&&touches>1)}
async function deliverGeneric(blob,name,{mime,extension,description}){name=cleanName(name,extension);let file=null;try{file=new File([blob],name,{type:mime,lastModified:Date.now()})}catch(_){}
 const canShare=()=>{try{return !!file&&typeof navigator.share==='function'&&typeof navigator.canShare==='function'&&navigator.canShare({files:[file]})}catch(_){return false}};
 const share=async()=>{await navigator.share({files:[file],title:name});return {method:'web-share',fileName:name,deliveryConfirmed:false}};
 const download=()=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.hidden=true;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),15000);return {method:'download',fileName:name,deliveryConfirmed:false}};
 if(isAppleTouchHost()&&canShare()){try{return await share()}catch(e){if(e?.name==='AbortError')throw e;return download()}}
 if(typeof global.showSaveFilePicker==='function'){let handle;try{handle=await global.showSaveFilePicker({suggestedName:name,types:[{description,accept:{[mime]:[extension]}}]})}catch(e){if(e?.name==='AbortError')throw e;handle=null}if(handle){try{const writable=await handle.createWritable();await writable.write(blob);await writable.close();return {method:'file-system-access',fileName:name,deliveryConfirmed:true}}catch(e){const err=new Error('The selected file could not be written.');err.code='write-failed';err.cause=e;throw err}}}
 if(canShare()){try{return await share()}catch(e){if(e?.name==='AbortError')throw e}}
 return download()}
function create({session,getDocument,fileOpen,editor,chrome,layout,navigation}={}){let busy=false,panel=null,button=null,mergeInput=null;
 function setPanelStatus(text){const node=$('pageToolsStatus');if(node)node.textContent=text||''}
 function position(){if(!panel||panel.hidden||!button)return;const a=button.getBoundingClientRect(),w=panel.offsetWidth||360,h=panel.offsetHeight||420;panel.style.left=Math.max(8,Math.min(innerWidth-w-8,a.left))+'px';panel.style.top=Math.max(8,Math.min(innerHeight-h-8,a.bottom+6))+'px'}
 function open(){if(!session.active||busy)return;navigation?.close();panel.hidden=false;syncEnabled();position()}
 function close(){if(panel)panel.hidden=true}
 function resetDocument(){close();if(mergeInput)mergeInput.value='';setPanelStatus('')}
 function syncEnabled(){if(!button)return;const active=!!session.active,count=layout.pageCount||session.pageCount||0,current=layout.currentPage||1;button.disabled=!active||busy;const currentLabel=$('pageToolsCurrent'),target=$('pageMoveTarget');if(currentLabel)currentLabel.textContent=active?`Page ${current} of ${count}`:'No PDF open';if(target){target.min='1';target.max=String(Math.max(1,count));if(document.activeElement!==target)target.value=String(current)}const ids=['pageMoveBtn','pageRotateBtn','pageDeleteBtn','pageExtractBtn','pageSplitBtn','pageMergeBtn'];for(const id of ids){const n=$(id);if(n)n.disabled=!active||busy}if($('pageDeleteBtn'))$('pageDeleteBtn').disabled=!active||busy||count<=1;if($('pageSplitBtn'))$('pageSplitBtn').disabled=!active||busy||current>=count}
 function setBusy(value,message=''){busy=!!value;syncEnabled();if(message)setPanelStatus(message)}
 async function verifyPdf(bytes,expectedPages){const task=pdfjsLib.getDocument({data:new Uint8Array(bytes),isEvalSupported:false,useWorkerFetch:false,stopAtErrors:false});const doc=await task.promise;try{if(expectedPages!=null&&doc.numPages!==expectedPages)throw new Error(`Generated PDF page count mismatch (${doc.numPages} instead of ${expectedPages}).`);return doc.numPages}finally{await doc.destroy()}}
 async function snapshotCurrent(){const doc=getDocument?.();if(!session.active||!doc)throw new Error('Open a PDF first.');editor.commit();if(!session.dirty)return new Uint8Array(session.sourceBytes);const bytes=new Uint8Array(await doc.saveDocument());await verifyPdf(bytes,doc.numPages);return bytes}
 async function applyMutation(message,work,nextPage){if(busy)return;setBusy(true,message);try{const source=await snapshotCurrent(),result=await work(source);await verifyPdf(result.bytes,result.pageCount);const ok=await fileOpen.replaceBytes(result.bytes,{fileName:session.fileName,page:Math.max(1,Math.min(result.pageCount,nextPage||layout.currentPage||1)),markDirty:true});if(!ok)throw new Error('The updated PDF could not replace the current document.');setPanelStatus('Page operation applied · save a copy to persist it.');chrome.status('PDF page operation applied · unsaved')}catch(e){console.error(e);chrome.error(e);chrome.status('Page operation failed');setPanelStatus(e?.message||'Page operation failed')}finally{setBusy(false)}}
 async function moveCurrent(){const count=layout.pageCount||session.pageCount||0,current=layout.currentPage||1,target=Math.trunc(Number($('pageMoveTarget')?.value));if(!Number.isFinite(target)||target<1||target>count){setPanelStatus(`Move target must be between 1 and ${count}.`);return}if(target===current){setPanelStatus('Page is already at that position.');return}await applyMutation(`Moving page ${current}…`,bytes=>NS.PageToolsEngine.movePage(bytes,current,target),target)}
 async function rotateCurrent(){const current=layout.currentPage||1;await applyMutation(`Rotating page ${current}…`,bytes=>NS.PageToolsEngine.rotatePage(bytes,current,90),current)}
 async function deleteCurrent(){const current=layout.currentPage||1,count=layout.pageCount||session.pageCount||0;if(count<=1)return;if(!global.confirm(`Delete page ${current}? This change remains local until you save a copy.`))return;await applyMutation(`Deleting page ${current}…`,bytes=>NS.PageToolsEngine.deletePage(bytes,current),Math.min(current,count-1))}
 async function extractCurrent(){if(busy)return;const current=layout.currentPage||1;setBusy(true,`Extracting page ${current}…`);try{const source=await snapshotCurrent(),result=await NS.PageToolsEngine.extractPages(source,[current]);await verifyPdf(result.bytes,1);const name=`${baseName(session.fileName)}-page-${current}.pdf`;const receipt=await NS.FileDelivery.deliver(new Blob([result.bytes],{type:'application/pdf'}),name);setPanelStatus(receipt.deliveryConfirmed?'Extracted page saved.':'Extracted page handed to the system.');chrome.status('Page extracted')}catch(e){if(e?.name!=='AbortError')console.error(e);setPanelStatus(e?.name==='AbortError'?'Extract cancelled':(e?.message||'Extract failed'));chrome.status(e?.name==='AbortError'?'Extract cancelled':'Extract failed')}finally{setBusy(false)}}
 async function splitCurrent(){if(busy)return;const current=layout.currentPage||1,count=layout.pageCount||session.pageCount||0;if(current>=count)return;setBusy(true,`Splitting after page ${current}…`);try{if(!global.JSZip)throw new Error('Local JSZip runtime is unavailable.');const source=await snapshotCurrent(),result=await NS.PageToolsEngine.splitAfter(source,current);await verifyPdf(result.parts[0].bytes,current);await verifyPdf(result.parts[1].bytes,count-current);const zip=new global.JSZip(),base=baseName(session.fileName);zip.file(`${base}-part-1.pdf`,result.parts[0].bytes);zip.file(`${base}-part-2.pdf`,result.parts[1].bytes);const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});const receipt=await deliverGeneric(blob,`${base}-split.zip`,{mime:'application/zip',extension:'.zip',description:'ZIP archive'});setPanelStatus(receipt.deliveryConfirmed?'Split archive saved.':'Split archive handed to the system.');chrome.status('PDF split complete')}catch(e){if(e?.name!=='AbortError')console.error(e);setPanelStatus(e?.name==='AbortError'?'Split cancelled':(e?.message||'Split failed'));chrome.status(e?.name==='AbortError'?'Split cancelled':'Split failed')}finally{setBusy(false)}}
 async function mergeFiles(files){if(busy||!files?.length)return;setBusy(true,`Merging ${files.length} PDF${files.length===1?'':'s'}…`);try{if(files.length>NS.PageToolsEngine.LIMITS.maxMergeFiles)throw new Error(`Choose no more than ${NS.PageToolsEngine.LIMITS.maxMergeFiles} PDFs at once.`);const source=await snapshotCurrent(),extras=[];let total=source.byteLength;for(const file of files){const bytes=new Uint8Array(await file.arrayBuffer());total+=bytes.byteLength;if(total>NS.PageToolsEngine.LIMITS.maxMergeBytes)throw new Error('Combined merge input exceeds the 192 MB safety limit.');if(bytes.byteLength<5||String.fromCharCode(...bytes.subarray(0,5))!=='%PDF-')throw new Error(`${file.name||'Selected file'} is not a PDF.`);extras.push(bytes)}const current=layout.currentPage||1,result=await NS.PageToolsEngine.merge(source,extras);await verifyPdf(result.bytes,result.pageCount);const ok=await fileOpen.replaceBytes(result.bytes,{fileName:session.fileName,page:current,markDirty:true});if(!ok)throw new Error('The merged PDF could not replace the current document.');setPanelStatus(`Merged PDF ready · ${result.pageCount} pages · save a copy to persist it.`);chrome.status('PDFs merged · unsaved')}catch(e){if(e?.name!=='AbortError')console.error(e);setPanelStatus(e?.message||'Merge failed');chrome.status('Merge failed')}finally{if(mergeInput)mergeInput.value='';setBusy(false)}}
 function build(){const nav=$('navPanelBtn');if(!nav||$('pageToolsBtn'))return;button=document.createElement('button');button.id='pageToolsBtn';button.className='tool-btn';button.type='button';button.disabled=true;button.setAttribute('aria-label','PDF page tools');button.innerHTML='<svg viewBox="0 0 24 24"><path d="M6 4h10v13H6z"/><path d="M9 7h10v13H9"/><path d="M12 10h4M12 14h4"/></svg><span class="tool-label">Pages</span>';nav.insertAdjacentElement('afterend',button);
  panel=document.createElement('section');panel.id='pageToolsPanel';panel.className='page-tools-panel';panel.hidden=true;panel.setAttribute('aria-label','PDF page tools');panel.innerHTML='<div class="page-tools-head"><strong>Page tools</strong><button id="closePageTools" class="page-tools-close" type="button" aria-label="Close page tools">×</button></div><div class="page-tools-section"><div class="page-tools-label">Current page</div><div class="page-tools-current"><span id="pageToolsCurrent">No PDF open</span></div><div class="page-tools-row"><input id="pageMoveTarget" type="number" min="1" value="1" aria-label="Move current page to position"><button id="pageMoveBtn" class="page-tools-action" type="button">Move to</button><button id="pageRotateBtn" class="page-tools-action" type="button">Rotate 90°</button></div><div class="page-tools-row"><button id="pageDeleteBtn" class="page-tools-action danger" type="button">Delete page</button><button id="pageExtractBtn" class="page-tools-action" type="button">Extract page</button></div></div><div class="page-tools-section"><div class="page-tools-label">Document</div><div class="page-tools-row"><button id="pageSplitBtn" class="page-tools-action" type="button">Split after this page</button><button id="pageMergeBtn" class="page-tools-action primary" type="button">Merge PDFs…</button></div><p class="page-tools-note">Page operations run locally. Merge appends selected PDFs. Split exports two PDFs inside one ZIP. Advanced PDF structures from appended/extracted documents may not round-trip perfectly.</p></div><div id="pageToolsStatus" class="page-tools-status"></div>';
  document.querySelector('.app-shell')?.append(panel);mergeInput=document.createElement('input');mergeInput.type='file';mergeInput.accept='.pdf,application/pdf';mergeInput.multiple=true;mergeInput.hidden=true;document.body.append(mergeInput);
 }
 function install(){build();if(!button)return;button.onclick=()=>panel.hidden?open():close();$('closePageTools').onclick=close;$('pageMoveBtn').onclick=moveCurrent;$('pageRotateBtn').onclick=rotateCurrent;$('pageDeleteBtn').onclick=deleteCurrent;$('pageExtractBtn').onclick=extractCurrent;$('pageSplitBtn').onclick=splitCurrent;$('pageMergeBtn').onclick=()=>mergeInput.click();mergeInput.onchange=()=>mergeFiles(Array.from(mergeInput.files||[]));global.addEventListener('resize',()=>{if(panel&&!panel.hidden)position()},{passive:true});syncEnabled()}
 return Object.freeze({install,open,close,resetDocument,syncEnabled,inspect:()=>Object.freeze({busy,open:!!panel&&!panel.hidden,currentPage:layout.currentPage||1,pageCount:layout.pageCount||0})})}
NS.PageTools=Object.freeze({create});
})(globalThis);
