(function(global){'use strict';
const NS=global.InkDOS2PdfP4=global.InkDOS2PdfP4||{},$=id=>document.getElementById(id);
const COMMAND_IDS=Object.freeze(['reader.search','reader.search.close','reader.search.query','reader.search.previous','reader.search.next','reader.search.reveal','reader.rotate-view','reader.print']);
function create({session,getDocument,layout,chrome,registry,canRotate}={}){
 let runtime=null,panel=null,input=null,status=null,list=null,prevBtn=null,nextBtn=null,searchBtn=null,printBtn=null,rotateBtn=null,inputTimer=0,resultButtons=[];
 const resize=()=>positionPanel();
 const outsidePointer=e=>{if(panel&&!panel.hidden&&!panel.contains(e.target)&&!searchBtn?.contains(e.target))registry.execute('reader.search.close')};
 function injectStyle(){if($('pdfReaderToolsStyle'))return;const s=document.createElement('style');s.id='pdfReaderToolsStyle';s.textContent=`.pdf-reader-popover{position:fixed;z-index:92;width:min(420px,calc(100vw - 24px));max-height:min(70vh,560px);display:grid;grid-template-rows:auto auto minmax(0,1fr);gap:8px;padding:10px;border:1px solid var(--line);border-radius:14px;background:var(--paper);box-shadow:var(--shadow)}.pdf-reader-popover[hidden]{display:none!important}.pdf-search-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:6px}.pdf-search-row input{min-width:0;height:38px;border:1px solid var(--line);border-radius:9px;background:var(--paper);color:var(--text);padding:0 10px;font:inherit}.pdf-search-row button,.pdf-search-result{border:1px solid var(--line);border-radius:9px;background:var(--paper);color:var(--text);font:inherit;cursor:pointer}.pdf-search-row button{min-width:38px}.pdf-search-meta{font-size:12px;color:var(--muted);min-height:18px}.pdf-search-results{overflow:auto;display:grid;gap:5px}.pdf-search-result{text-align:left;padding:8px 10px;line-height:1.35}.pdf-search-result:hover,.pdf-search-result.active{background:color-mix(in srgb,var(--accent) 10%,var(--paper))}.pdf-search-page{display:block;font-size:11px;font-weight:800;color:var(--accent);margin-bottom:2px}.pdf-search-snippet{font-size:12px;color:var(--text)}@media(max-width:640px){.pdf-reader-popover{left:12px!important;right:12px!important;top:auto!important;bottom:calc(env(safe-area-inset-bottom) + 48px);width:auto}}`;(document.head||document.documentElement).appendChild(s)}
 function button(id,label,title,svg,command){const b=document.createElement('button');b.id=id;b.className='tool-btn icon-only';b.type='button';b.dataset.command=command;b.setAttribute('aria-label',label);b.title=title||label;b.innerHTML=svg;return b}
 function installToolbar(){const zoom=$('zoomSelect')?.closest('.tool-group');if(!zoom)return;searchBtn=button('pdfSearchBtn','Find text in PDF','Find (⌘F)','<svg viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="5.5"/><path d="m15 15 5 5"/></svg>','reader.search');rotateBtn=button('pdfRotateViewBtn','Rotate view clockwise','Rotate view','<svg viewBox="0 0 24 24"><path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 5v6h-6"/></svg>','reader.rotate-view');printBtn=button('pdfPrintBtn','Print PDF','Print (⌘P)','<svg viewBox="0 0 24 24"><path d="M7 8V4h10v4M7 17H5a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-2"/><path d="M7 14h10v6H7z"/></svg>','reader.print');zoom.insertBefore(searchBtn,zoom.firstChild);zoom.insertBefore(rotateBtn,$('zoomSelect'));zoom.insertBefore(printBtn,$('saveToolbarBtn'));for(const b of[searchBtn,rotateBtn,printBtn])registry.bindElement(b,b.dataset.command)}
 function installPanel(){panel=document.createElement('section');panel.id='pdfSearchPanel';panel.className='pdf-reader-popover';panel.hidden=true;panel.setAttribute('aria-label','Find in PDF');panel.innerHTML='<div class="pdf-search-row"><input id="pdfSearchInput" type="search" autocomplete="off" placeholder="Find in PDF" aria-label="Find text"><button id="pdfSearchPrev" data-command="reader.search.previous" type="button" aria-label="Previous result">‹</button><button id="pdfSearchNext" data-command="reader.search.next" type="button" aria-label="Next result">›</button></div><div id="pdfSearchStatus" class="pdf-search-meta"></div><div id="pdfSearchResults" class="pdf-search-results"></div>';document.body.appendChild(panel);input=$('pdfSearchInput');status=$('pdfSearchStatus');list=$('pdfSearchResults');prevBtn=$('pdfSearchPrev');nextBtn=$('pdfSearchNext');for(const b of[prevBtn,nextBtn])registry.bindElement(b,b.dataset.command);input.addEventListener('input',()=>{clearTimeout(inputTimer);inputTimer=setTimeout(()=>registry.execute('reader.search.query',input.value),160)});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();registry.execute(e.shiftKey?'reader.search.previous':'reader.search.next')}else if(e.key==='Escape'){e.preventDefault();registry.execute('reader.search.close')}});document.addEventListener('pointerdown',outsidePointer)}
 function positionPanel(){if(!panel||panel.hidden||!searchBtn||matchMedia('(max-width:640px)').matches)return;const r=searchBtn.getBoundingClientRect(),w=Math.min(420,innerWidth-24);panel.style.left=Math.max(12,Math.min(innerWidth-w-12,r.left))+'px';panel.style.top=Math.min(innerHeight-panel.offsetHeight-12,r.bottom+6)+'px'}
 function syncEnabled(){for(const id of COMMAND_IDS)registry.sync(id)}
 function resetDocument(){runtime?.resetDocument();if(input)input.value='';closeSearch();syncEnabled()}
 function toggleSearch(){if(!session.active)return false;return panel.hidden?openSearch():closeSearch()}
 function openSearch(){if(!session.active||!panel)return false;panel.hidden=false;requestAnimationFrame(()=>{positionPanel();input.focus();input.select()});return true}
 function closeSearch(){if(panel)panel.hidden=true;return true}
 function resultIndex(arg){if(typeof arg==='number')return arg;const el=arg?.currentTarget||arg?.target?.closest?.('[data-result-index]');return Number(el?.dataset?.resultIndex)}
 function renderResults(snapshot=runtime?.inspect()){if(!list||!status||!snapshot)return;for(const b of resultButtons)registry.unbindElement(b);resultButtons=[];list.replaceChildren();const {query,results,cursor}=snapshot;if(!query){status.textContent='';registry.sync('reader.search.previous');registry.sync('reader.search.next');return}if(!results.length){if(status.textContent!=='Searching…'&&!status.textContent.startsWith('Searching… '))status.textContent='No matches';registry.sync('reader.search.previous');registry.sync('reader.search.next');return}status.textContent=`${results.length}${results.length>=NS.ReaderRuntime.MAX_RESULTS?'+':''} match${results.length===1?'':'es'}`;const frag=document.createDocumentFragment();results.forEach((r,i)=>{const b=document.createElement('button');b.className='pdf-search-result'+(i===cursor?' active':'');b.type='button';b.dataset.command='reader.search.reveal';b.dataset.resultIndex=String(i);const pg=document.createElement('span');pg.className='pdf-search-page';pg.textContent='Page '+r.page;const sn=document.createElement('span');sn.className='pdf-search-snippet';sn.textContent=r.snippet;b.append(pg,sn);resultButtons.push(b);frag.appendChild(b)});list.appendChild(frag);for(const b of resultButtons)registry.bindElement(b,'reader.search.reveal');resultButtons[cursor]?.scrollIntoView({block:'nearest'});registry.sync('reader.search.previous');registry.sync('reader.search.next')}
 function registerCommands(){registry.register('reader.search',{isEnabled:()=>!!session.active,execute:toggleSearch});registry.register('reader.search.close',{isEnabled:()=>!!panel&&!panel.hidden,execute:closeSearch});registry.register('reader.search.query',{isEnabled:()=>!!session.active,execute:value=>runtime.search(typeof value==='string'?value:input?.value)});registry.register('reader.search.previous',{isEnabled:()=>!!session.active&&runtime.results.length>0,execute:()=>runtime.step(-1)});registry.register('reader.search.next',{isEnabled:()=>!!session.active&&runtime.results.length>0,execute:()=>runtime.step(1)});registry.register('reader.search.reveal',{isEnabled:()=>!!session.active&&runtime.results.length>0,execute:arg=>runtime.reveal(resultIndex(arg))});registry.register('reader.rotate-view',{isEnabled:()=>!!session.active&&(canRotate?.()!==false),execute:()=>runtime.rotate(90)});registry.register('reader.print',{isEnabled:()=>!!session.active,execute:()=>runtime.print()})}
 function install(){injectStyle();installPanel();runtime=NS.ReaderRuntime.create({session,getDocument,layout,chrome,onChange:renderResults,onStatus:text=>{if(status)status.textContent=text}});registerCommands();installToolbar();global.addEventListener('resize',resize,{passive:true});syncEnabled()}
 function destroy(){clearTimeout(inputTimer);global.removeEventListener('resize',resize);document.removeEventListener('pointerdown',outsidePointer);for(const b of resultButtons)registry.unbindElement(b);for(const b of[searchBtn,rotateBtn,printBtn,prevBtn,nextBtn])if(b)registry.unbindElement(b);for(const id of COMMAND_IDS)registry.unregister(id);panel?.remove();searchBtn?.remove();rotateBtn?.remove();printBtn?.remove();panel=input=status=list=prevBtn=nextBtn=searchBtn=rotateBtn=printBtn=null;runtime=null}
 return Object.freeze({install,destroy,resetDocument,syncEnabled,openSearch,closeSearch,search:value=>registry.execute('reader.search.query',value),step:delta=>registry.execute(delta<0?'reader.search.previous':'reader.search.next'),print:()=>registry.execute('reader.print'),rotate:()=>registry.execute('reader.rotate-view'),inspect:()=>Object.freeze({open:!!panel&&!panel.hidden,runtime:runtime?.inspect(),commands:COMMAND_IDS.slice()})})}
NS.ReaderTools=Object.freeze({create,COMMAND_IDS});
})(globalThis);
