(function(global){'use strict';
const NS=global.InkDOS2PdfP4=global.InkDOS2PdfP4||{},$=id=>document.getElementById(id),MAX_RESULTS=1000,MAX_INDEX_PAGES=2000;
function create({session,getDocument,layout,chrome}={}){
 let query='',results=[],cursor=-1,searchToken=0,indexedDoc=null,pageTexts=new Map(),panel=null,input=null,status=null,list=null,prevBtn=null,nextBtn=null,searchBtn=null,printBtn=null,rotateBtn=null;
 function injectStyle(){if($('pdfReaderToolsStyle'))return;const s=document.createElement('style');s.id='pdfReaderToolsStyle';s.textContent=`.pdf-reader-popover{position:fixed;z-index:92;width:min(420px,calc(100vw - 24px));max-height:min(70vh,560px);display:grid;grid-template-rows:auto auto minmax(0,1fr);gap:8px;padding:10px;border:1px solid var(--line);border-radius:14px;background:var(--paper);box-shadow:var(--shadow)}.pdf-reader-popover[hidden]{display:none!important}.pdf-search-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:6px}.pdf-search-row input{min-width:0;height:38px;border:1px solid var(--line);border-radius:9px;background:var(--paper);color:var(--text);padding:0 10px;font:inherit}.pdf-search-row button,.pdf-search-result{border:1px solid var(--line);border-radius:9px;background:var(--paper);color:var(--text);font:inherit;cursor:pointer}.pdf-search-row button{min-width:38px}.pdf-search-meta{font-size:12px;color:var(--muted);min-height:18px}.pdf-search-results{overflow:auto;display:grid;gap:5px}.pdf-search-result{text-align:left;padding:8px 10px;line-height:1.35}.pdf-search-result:hover,.pdf-search-result.active{background:color-mix(in srgb,var(--accent) 10%,var(--paper))}.pdf-search-page{display:block;font-size:11px;font-weight:800;color:var(--accent);margin-bottom:2px}.pdf-search-snippet{font-size:12px;color:var(--text)}@media(max-width:640px){.pdf-reader-popover{left:12px!important;right:12px!important;top:auto!important;bottom:calc(env(safe-area-inset-bottom) + 48px);width:auto}}`;(document.head||document.documentElement).appendChild(s)}
 function button(id,label,title,svg){const b=document.createElement('button');b.id=id;b.className='tool-btn icon-only';b.type='button';b.setAttribute('aria-label',label);b.title=title||label;b.innerHTML=svg;return b}
 function installToolbar(){const zoom=$('zoomSelect')?.closest('.tool-group');if(!zoom)return;searchBtn=button('pdfSearchBtn','Find text in PDF','Find (⌘F)','<svg viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="5.5"/><path d="m15 15 5 5"/></svg>');rotateBtn=button('pdfRotateViewBtn','Rotate view clockwise','Rotate view','<svg viewBox="0 0 24 24"><path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 5v6h-6"/></svg>');printBtn=button('pdfPrintBtn','Print PDF','Print (⌘P)','<svg viewBox="0 0 24 24"><path d="M7 8V4h10v4M7 17H5a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-2"/><path d="M7 14h10v6H7z"/></svg>');zoom.insertBefore(searchBtn,zoom.firstChild);zoom.insertBefore(rotateBtn,$('zoomSelect'));zoom.insertBefore(printBtn,$('saveToolbarBtn'));searchBtn.onclick=toggleSearch;rotateBtn.onclick=()=>rotate(90);printBtn.onclick=print;syncEnabled()}
 function installPanel(){panel=document.createElement('section');panel.id='pdfSearchPanel';panel.className='pdf-reader-popover';panel.hidden=true;panel.setAttribute('aria-label','Find in PDF');panel.innerHTML='<div class="pdf-search-row"><input id="pdfSearchInput" type="search" autocomplete="off" placeholder="Find in PDF" aria-label="Find text"><button id="pdfSearchPrev" type="button" aria-label="Previous result">‹</button><button id="pdfSearchNext" type="button" aria-label="Next result">›</button></div><div id="pdfSearchStatus" class="pdf-search-meta"></div><div id="pdfSearchResults" class="pdf-search-results"></div>';document.body.appendChild(panel);input=$('pdfSearchInput');status=$('pdfSearchStatus');list=$('pdfSearchResults');prevBtn=$('pdfSearchPrev');nextBtn=$('pdfSearchNext');let timer=0;input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>search(input.value),160)});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();step(e.shiftKey?-1:1)}else if(e.key==='Escape'){e.preventDefault();closeSearch()}});prevBtn.onclick=()=>step(-1);nextBtn.onclick=()=>step(1);document.addEventListener('pointerdown',e=>{if(!panel.hidden&&!panel.contains(e.target)&&!searchBtn?.contains(e.target))closeSearch()})}
 function positionPanel(){if(!panel||panel.hidden||matchMedia('(max-width:640px)').matches)return;const r=searchBtn.getBoundingClientRect(),w=Math.min(420,innerWidth-24);panel.style.left=Math.max(12,Math.min(innerWidth-w-12,r.left))+'px';panel.style.top=Math.min(innerHeight-panel.offsetHeight-12,r.bottom+6)+'px'}
 function syncEnabled(){const active=!!session.active;for(const b of [searchBtn,rotateBtn,printBtn])if(b)b.disabled=!active}
 function resetDocument(){searchToken++;indexedDoc=null;pageTexts.clear();results=[];cursor=-1;query='';if(input)input.value='';renderResults();syncEnabled();closeSearch()}
 function toggleSearch(){if(!session.active)return;if(panel.hidden)openSearch();else closeSearch()}
 function openSearch(){if(!session.active)return;panel.hidden=false;requestAnimationFrame(()=>{positionPanel();input.focus();input.select()})}
 function closeSearch(){if(panel)panel.hidden=true}
 async function pageText(doc,n,token){if(pageTexts.has(n))return pageTexts.get(n);const p=await doc.getPage(n);if(token!==searchToken)throw new DOMException('Search cancelled','AbortError');const tc=await p.getTextContent({normalizeWhitespace:true});const text=(tc.items||[]).map(x=>x.str||'').join(' ').replace(/\s+/g,' ').trim();pageTexts.set(n,text);return text}
 function snippet(text,index,len){const a=Math.max(0,index-55),b=Math.min(text.length,index+len+85);return (a?'…':'')+text.slice(a,b)+(b<text.length?'…':'')}
 async function search(value){const doc=getDocument?.();const q=String(value||'').trim();query=q;results=[];cursor=-1;renderResults();if(!q||!doc)return;const token=++searchToken,indexed=Math.min(doc.numPages,MAX_INDEX_PAGES);status.textContent='Searching…';const needle=q.toLocaleLowerCase();try{for(let n=1;n<=indexed&&results.length<MAX_RESULTS;n++){const text=await pageText(doc,n,token),low=text.toLocaleLowerCase();let from=0;while(results.length<MAX_RESULTS){const i=low.indexOf(needle,from);if(i<0)break;results.push({page:n,index:i,snippet:snippet(text,i,q.length)});from=i+Math.max(1,needle.length)}if(token!==searchToken)return;if(n%12===0){status.textContent=`Searching… ${n}/${indexed}`;await new Promise(r=>setTimeout(r,0))}}if(token!==searchToken)return;cursor=results.length?0:-1;renderResults();if(results.length)await reveal(cursor)}catch(e){if(e?.name!=='AbortError'){console.error(e);status.textContent='Search failed';chrome.status('PDF search failed')}}}
 function renderResults(){if(!list||!status)return;list.replaceChildren();if(!query){status.textContent='';return}if(!results.length){status.textContent='No matches';return}status.textContent=`${results.length}${results.length>=MAX_RESULTS?'+':''} match${results.length===1?'':'es'}`;const frag=document.createDocumentFragment();results.slice(0,MAX_RESULTS).forEach((r,i)=>{const b=document.createElement('button');b.className='pdf-search-result'+(i===cursor?' active':'');b.type='button';const pg=document.createElement('span');pg.className='pdf-search-page';pg.textContent='Page '+r.page;const sn=document.createElement('span');sn.className='pdf-search-snippet';sn.textContent=r.snippet;b.append(pg,sn);b.onclick=()=>reveal(i);frag.appendChild(b)});list.appendChild(frag)}
 async function reveal(i){if(!results.length)return;cursor=(i+results.length)%results.length;const r=results[cursor];await layout.goToPage(r.page,{smooth:true});renderResults();list.children[cursor]?.scrollIntoView({block:'nearest'});chrome.status(`Match ${cursor+1} of ${results.length} · page ${r.page}`)}
 function step(delta){if(results.length)reveal((cursor<0?0:cursor)+delta)}
 async function rotate(delta=90){if(!session.active)return;await layout.rotateView(delta);chrome.status(`View rotated ${layout.rotation}°`)}
 function print(){if(!session.active||!session.sourceBytes?.length)return;if(session.dirty&&!global.confirm('Unsaved annotations are not included in browser printing. Print the opened PDF anyway?'))return;const blob=new Blob([session.sourceBytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),frame=document.createElement('iframe');frame.style.cssText='position:fixed;right:0;bottom:0;width:1px;height:1px;border:0;opacity:0;pointer-events:none';frame.onload=()=>{setTimeout(()=>{try{frame.contentWindow?.focus();frame.contentWindow?.print()}catch(e){console.error(e);chrome.status('Browser printing is unavailable')}setTimeout(()=>{URL.revokeObjectURL(url);frame.remove()},60000)},250)};frame.src=url;document.body.appendChild(frame);chrome.status('Preparing print dialog…')}
 function install(){injectStyle();installPanel();installToolbar();global.addEventListener('resize',positionPanel);syncEnabled()}
 return Object.freeze({install,resetDocument,syncEnabled,openSearch,closeSearch,search,step,print,rotate,get results(){return results.slice()},get cursor(){return cursor}})}
NS.ReaderTools=Object.freeze({create});})(globalThis);
