(function(global){'use strict';const NS=global.InkDOS2Presentations;if(!NS)throw new Error('Presentations private runtime namespace missing.');const $=id=>document.getElementById(id);const session=new NS.PresentationSession();let editor=null,commands=null;const chrome=NS.ChromeController.create({session});const selection=new NS.SelectionController(()=>editor?.sync());const history=new NS.HistoryController(session,()=>editor?.sync());const adapter=new NS.ContentViewportAdapter($('viewport'),$('stage'));let zoomControls=null;const zoom=new NS.ZoomController(adapter,$('stage'),$('slideShell'),$('slideCanvas'),()=>session.currentSlide,info=>zoomControls?.update(info));const surface=NS.SlideSurface.create({session,stage:$('stage'),shell:$('slideShell'),canvas:$('slideCanvas'),selection,history,onModelChange:()=>{panel.render({ensureActive:false});editor?.sync()}});let panel=null;function navigate(index){session.setCurrentByIndex(index);selection.clear();surface.render();panel.syncActive();zoom.recenter();chrome.stats();editor?.sync()}panel=NS.SlidePanelController.create({session,workspace:$('workspace'),panel:$('slidePanel'),inner:$('slidePanelInner'),onNavigate:navigate,onLayout:()=>zoom.apply({preserveFocus:true})});zoomControls=NS.ZoomControls.create({zoom});const fileOpen=NS.PptxOpenController.create({session,fileInput:$('fileInput'),history,chrome,onCommit:()=>{selection.clear();surface.render();panel.render();zoom.recenter();chrome.title();chrome.stats();commands?.sync()}});const save=NS.SaveController.create({session,chrome});const slideshow=NS.SlideshowController.create({session,overlay:$('presentOverlay'),host:$('presentHost'),counter:$('presentCounter')});editor=NS.EditingController.create({session,history,selection,surface,panel,zoom,chrome,onStructureChange:()=>{}});commands=NS.CommandController.create({session,history,chrome,fileOpen,save,editor,panel,slideshow});NS.Appearance.install();fileOpen.install();zoomControls.install();editor.install();commands.install();surface.render();panel.render();zoom.install();chrome.title();chrome.stats();chrome.setRetry(fileOpen.requestOpen);
function inspect(){const rect=e=>{const r=e.getBoundingClientRect();return {left:r.left,top:r.top,right:r.right,bottom:r.bottom,width:r.width,height:r.height}};const active=$('slidePanelInner').querySelector('.slide-thumb.active');const canvas=$('slideCanvas'),viewport=$('viewport'),workspace=$('workspace'),bar=$('editbar');return Object.freeze({session:{fileName:session.fileName,sourceKind:session.sourceKind,dirty:session.dirty,slideCount:session.slides.length,currentIndex:session.currentIndex,currentSlideId:session.currentSlideId,selectedObjectId:selection.objectId},view:{mode:zoom.mode,manual:zoom.manual,scale:zoom.scale,panelOpen:panel.isOpen,orientation:adapter.metrics().orientation},geometry:{documentOverflowX:document.documentElement.scrollWidth-document.documentElement.clientWidth,documentOverflowY:document.documentElement.scrollHeight-document.documentElement.clientHeight,bodyOverflowX:document.body.scrollWidth-document.body.clientWidth,toolbarClientWidth:bar.clientWidth,toolbarScrollWidth:bar.scrollWidth,viewport:rect(viewport),workspace:rect(workspace),panel:rect($('slidePanel')),canvas:rect(canvas),activeThumb:active?rect(active):null,viewportScrollWidth:viewport.scrollWidth,viewportClientWidth:viewport.clientWidth,viewportScrollHeight:viewport.scrollHeight,viewportClientHeight:viewport.clientHeight}})}
NS.PresentationsApp=Object.freeze({session,history,selection,zoom,panel,open:fileOpen.openFile,newPresentation:commands.requestNew,save:save.save,present:slideshow.open,inspect});global.__inkdosPresentations=NS.PresentationsApp;})(globalThis);

(function(global){'use strict';
function installToolbarRail(){
 const target=document.getElementById('formatbar')||document.getElementById('editbar')||document.getElementById('toolbar');
 if(!target||target.closest('.inkdos-toolbar-rail'))return;
 const style=document.createElement('style');style.id='inkdosToolbarRailStyle';style.textContent=`.inkdos-toolbar-rail{width:100%;min-width:0;display:grid;grid-template-columns:34px 1px minmax(0,1fr) 1px 34px;align-items:stretch;background:var(--chrome,var(--frame-chrome,#fff));border-bottom:1px solid var(--line,var(--frame-line,#d7dce2));position:relative;z-index:30}.inkdos-toolbar-rail>.inkdos-toolbar-scroll{grid-column:3;min-width:0!important;width:100%!important;max-width:none!important;border-bottom:0!important}.inkdos-toolbar-arrow{width:34px;min-width:34px;min-height:44px;padding:0;border:0;border-radius:0;background:transparent;color:var(--muted,var(--frame-muted,#5f6368));font:600 18px/1 Arial,sans-serif;display:grid;place-items:center;cursor:pointer;user-select:none;-webkit-user-select:none}.inkdos-toolbar-arrow:hover:not(:disabled),.inkdos-toolbar-arrow:focus-visible:not(:disabled){background:var(--toolbar-hover,var(--frame-hover,rgba(60,64,67,.08)));color:var(--text,var(--frame-text,#202124));outline:none}.inkdos-toolbar-arrow:disabled{opacity:.28;cursor:default}.inkdos-toolbar-separator{width:1px;height:calc(100% - 16px);min-height:22px;align-self:center;background:var(--line,var(--frame-line,#d7dce2));pointer-events:none}.inkdos-toolbar-rail-host::after{display:none!important}@media(max-width:480px){.inkdos-toolbar-rail{grid-template-columns:30px 1px minmax(0,1fr) 1px 30px}.inkdos-toolbar-arrow{width:30px;min-width:30px;font-size:17px}}`;(document.head||document.documentElement).appendChild(style);
 const shell=document.createElement('div');shell.className='inkdos-toolbar-rail';
 const left=document.createElement('button'),right=document.createElement('button'),sepL=document.createElement('span'),sepR=document.createElement('span');
 left.type=right.type='button';left.className=right.className='inkdos-toolbar-arrow';sepL.className=sepR.className='inkdos-toolbar-separator';left.textContent='<';right.textContent='>';left.setAttribute('aria-label','Scroll toolbar left');right.setAttribute('aria-label','Scroll toolbar right');
 const parent=target.parentNode;parent.insertBefore(shell,target);shell.append(left,sepL,target,sepR,right);target.classList.add('inkdos-toolbar-scroll');if(parent.classList?.contains('toolstrip-shell'))parent.classList.add('inkdos-toolbar-rail-host');
 function sync(){const max=Math.max(0,target.scrollWidth-target.clientWidth);left.disabled=max<2||target.scrollLeft<=1;right.disabled=max<2||target.scrollLeft>=max-1}
 function move(dir){const amount=Math.max(150,Math.round(target.clientWidth*.62));try{target.scrollBy({left:dir*amount,behavior:'smooth'})}catch(_){target.scrollLeft+=dir*amount}setTimeout(sync,180)}
 left.addEventListener('click',()=>move(-1));right.addEventListener('click',()=>move(1));target.addEventListener('scroll',sync,{passive:true});global.addEventListener('resize',sync,{passive:true});
 if(global.ResizeObserver)new ResizeObserver(sync).observe(target);new MutationObserver(sync).observe(target,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','class','style']});requestAnimationFrame(sync);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installToolbarRail,{once:true});else installToolbarRail();
})(globalThis);
