(function(root){'use strict';
const doc=typeof document!=='undefined'?document:null;
const APPS=new Set(['documents','spreadsheets','presentations','pdf','epub','txt']),SUITE_LANGUAGE_KEY='inkdos2:language';
const TRANSIENT_EVENT='inkdos:transient-open',transientOwner={kind:'settings-strip'};
let context=null,drawer=null,strip=null,popover=null,activeButton=null,mutationObserver=null;
function appContext(){if(context)return context;let parts=[];try{parts=decodeURIComponent(root.location?.pathname||'').split('/').filter(Boolean)}catch(_){}context=parts.find(part=>APPS.has(part))||null;return context}
function languageKey(){const app=appContext();return app?'inkdos2:'+app+':language':SUITE_LANGUAGE_KEY}
function legacyLanguageKey(){return appContext()?SUITE_LANGUAGE_KEY:null}
function button(kind,icon,label){const item=doc.createElement('button');item.type='button';item.className='inkdos-settings-button';item.dataset.settingsItem=kind;item.setAttribute('aria-haspopup','dialog');item.setAttribute('aria-expanded','false');item.title=label;item.setAttribute('aria-label',label);item.innerHTML='<span class="inkdos-settings-icon" aria-hidden="true">'+icon+'</span><span class="inkdos-settings-label">'+label+'</span>';item.addEventListener('click',()=>toggle(kind,item));return item}
function option(label,value,onChoose){const item=doc.createElement('button');item.type='button';item.className='inkdos-settings-option';item.textContent=label;item.dataset.settingsValue=value;item.addEventListener('click',onChoose);return item}
function closePopover(){if(!popover)return;popover.hidden=true;if(activeButton)activeButton.setAttribute('aria-expanded','false');activeButton=null}
function claimTransient(){if(!doc)return;try{doc.dispatchEvent(new CustomEvent(TRANSIENT_EVENT,{detail:{owner:transientOwner}}))}catch(_){}}
function positionPopover(anchor){if(!popover||!anchor)return;popover.hidden=false;const rect=anchor.getBoundingClientRect(),margin=12,width=popover.offsetWidth||286,height=popover.offsetHeight||280;let left=Math.min(root.innerWidth-margin-width,Math.max(margin,rect.right-width));if(!Number.isFinite(left))left=margin;let top=rect.top-height-8;if(top<margin)top=Math.min(root.innerHeight-margin-height,rect.bottom+8);popover.style.left=Math.max(margin,left)+'px';popover.style.top=Math.max(margin,top)+'px'}
function openPopover(anchor,title){if(!popover)return;claimTransient();popover.replaceChildren();const heading=doc.createElement('div');heading.className='inkdos-settings-popover-title';heading.textContent=title;popover.appendChild(heading);if(activeButton&&activeButton!==anchor)activeButton.setAttribute('aria-expanded','false');activeButton=anchor;anchor.setAttribute('aria-expanded','true');positionPopover(anchor)}
function markActive(selector,value){if(!popover)return;for(const item of popover.querySelectorAll(selector))item.classList.toggle('active',item.dataset.settingsValue===value)}
function appearanceMode(){const current=drawer?.querySelector('[data-appearance-choice].active,[data-appearance-choice][aria-pressed="true"],[data-appearance-mode].active,[data-appearance-mode][aria-pressed="true"]');return current?.dataset.appearanceChoice||current?.dataset.appearanceMode||'system'}
function showAppearance(anchor){openPopover(anchor,'Appearance');for(const [mode,label] of [['light','Light'],['dark','Dark'],['system','System']])popover.appendChild(option(label,mode,()=>{const target=drawer?.querySelector('[data-appearance-choice="'+mode+'"],[data-appearance-mode="'+mode+'"]');target?.click();markActive('[data-settings-value]',mode);closePopover()}));markActive('[data-settings-value]',appearanceMode())}
function showInterface(anchor){openPopover(anchor,'Interface');const api=root.InkDOSUiDensity;for(const [mode,label] of [['auto','Auto'],['desktop','Desktop'],['mobile','Smartphone']])popover.appendChild(option(label,mode,()=>{api?.set?.(mode);markActive('[data-settings-value]',api?.preference||mode);closePopover()}));markActive('[data-settings-value]',api?.preference||'auto')}
function showLanguage(anchor){openPopover(anchor,'Language');const api=root.InkDOSLocalization;if(!api)return;for(const language of api.languages){popover.appendChild(option(language.label,language.code,async()=>{await api.setLanguage(language.code,{storageKey:languageKey()});markActive('[data-settings-value]',api.currentLanguage);closePopover()}))}markActive('[data-settings-value]',api.currentLanguage)}
function clickHelp(){const entry=doc.querySelector('[data-inkdos-help-entry]');if(entry){closePopover();entry.click();return true}return false}
function clickUpdater(){const candidate=doc.querySelector('[title="Check for updates"],[aria-label="Check for updates"],[data-command="updater.check"]');if(candidate){closePopover();candidate.click();return true}return false}
function showHelp(anchor){openPopover(anchor,'Help');popover.appendChild(option('Getting started','getting-started',()=>clickHelp()));popover.appendChild(option('Keyboard shortcuts','keyboard-shortcuts',()=>clickHelp()));popover.appendChild(option('File compatibility','file-compatibility',()=>clickHelp()));if(doc.querySelector('[title="Check for updates"],[aria-label="Check for updates"],[data-command="updater.check"]'))popover.appendChild(option('Check for updates','updates',()=>clickUpdater()));const about=option('About InkDOS','about',()=>{let note=popover.querySelector('.inkdos-settings-help-note');if(note){note.remove();return}note=doc.createElement('div');note.className='inkdos-settings-help-note';note.textContent='InkDOS keeps workspace editing local-first and offline-capable. Interface language changes presentation only; file content is never translated.';popover.appendChild(note);root.InkDOSLocalization?.apply?.()});popover.appendChild(about)}
function toggle(kind,anchor){if(!popover)return;if(activeButton===anchor&&!popover.hidden){closePopover();return}if(kind==='appearance')showAppearance(anchor);else if(kind==='interface')showInterface(anchor);else if(kind==='language')showLanguage(anchor);else if(kind==='help')showHelp(anchor)}
function suppressLegacyControls(){if(!drawer)return;const appearance=drawer.querySelector('[data-appearance-choice]')?.closest('.drawer-section');appearance?.setAttribute('data-inkdos-settings-redundant','');const density=drawer.querySelector('[data-inkdos-density-control]');if(density){density.setAttribute('data-inkdos-settings-redundant','');const label=density.previousElementSibling;if(label?.classList.contains('inkdos-density-label'))label.setAttribute('data-inkdos-settings-redundant','')}const help=drawer.querySelector('[data-inkdos-help-entry]')?.closest('.inkdos-help-menu-list');help?.setAttribute('data-inkdos-settings-redundant','')}
function watchLegacyControls(){if(!drawer||mutationObserver||typeof MutationObserver!=='function')return;mutationObserver=new MutationObserver(()=>{suppressLegacyControls();if(drawer.hidden)closePopover()});mutationObserver.observe(drawer,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']})}

// Frame actions: Home · Open · Save on the left, Settings (sun) · Share on the right, Help in the status bar.
// The legacy menu button and drawer stay in the DOM (hidden trigger); header buttons proxy the drawer commands.
const ICONS={new:'<path d="M12 5v14M5 12h14"/>',open:'<path d="M3.5 7.5a2 2 0 0 1 2-2h4l2 2h7a2 2 0 0 1 2 2v7.5a2 2 0 0 1-2 2h-13a2 2 0 0 1-2-2z"/>',save:'<path d="M5 4h11l3 3v12a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1z"/><path d="M8 4v5h7V4M8 20v-6h8v6"/>',share:'<path d="M12 15V4M8 8l4-4 4 4"/><path d="M6 11H5v9h14v-9h-1"/>',sun:'<circle cx="12" cy="12" r="3.6"/><path d="M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6l1.4 1.4M17 17l1.4 1.4M5.6 18.4 7 17M17 7l1.4-1.4"/>',help:'<circle cx="12" cy="12" r="8.5"/><path d="M9.6 9.4a2.5 2.5 0 0 1 4.8.9c0 1.7-2.4 2-2.4 3.7M12 17h.01"/>'};
let frameInstalled=false;
function drawerTarget(ids){for(const id of ids){const el=drawer?.querySelector('#'+id);if(el)return el}return null}
function frameButton(kind,label,onClick){const b=doc.createElement('button');b.type='button';b.className='frame-btn inkdos-frame-action';b.dataset.frameAction=kind;b.title=label;b.setAttribute('aria-label',label);b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true">'+ICONS[kind]+'</svg>';b.addEventListener('click',onClick);return b}
function proxyButton(kind,label,target){const b=frameButton(kind,label,()=>{if(target.disabled)return;const options=kind==='save'?root.InkDOSSaveOptions:null;if(typeof options==='function')options(b);else if(kind==='save'&&root.InkDOSSaveProvider)showSaveMenu(root.InkDOSSaveProvider);else target.click()});const sync=()=>{b.disabled=!!target.disabled};sync();if(typeof MutationObserver==='function')new MutationObserver(sync).observe(target,{attributes:true,attributeFilter:['disabled']});return b}
// Full screen (Fullscreen API): offered where the browser allows it and InkDOS is not already an installed app window.
function fullscreenApi(){const el=doc.documentElement,req=el.requestFullscreen||el.webkitRequestFullscreen;if(!req||!(doc.fullscreenEnabled||doc.webkitFullscreenEnabled))return null;try{if(root.navigator?.standalone||root.matchMedia?.('(display-mode: standalone),(display-mode: fullscreen)').matches)return null}catch(_){}const active=()=>!!(doc.fullscreenElement||doc.webkitFullscreenElement);return{active,toggle:()=>active()?(doc.exitFullscreen||doc.webkitExitFullscreen).call(doc):req.call(el)}}
function section(title){const h=doc.createElement('div');h.className='inkdos-settings-popover-title inkdos-settings-section';h.textContent=title;popover.appendChild(h)}
function showSettings(anchor){openPopover(anchor,'Appearance');const current=appearanceMode();for(const [mode,label] of [['light','Light'],['dark','Dark'],['system','System']]){const o=option(label,mode,()=>{drawer?.querySelector('[data-appearance-choice="'+mode+'"],[data-appearance-mode="'+mode+'"]')?.click();closePopover()});o.dataset.settingsGroup='appearance';o.classList.toggle('active',mode===current);popover.appendChild(o)}
 const density=root.InkDOSUiDensity;section('Interface');const row=doc.createElement('div');row.className='inkdos-settings-segment';for(const [mode,label] of [['auto','Auto'],['desktop','Desktop'],['mobile','Smartphone']]){const o=option(label,mode,()=>{density?.set?.(mode);for(const x of row.children)x.classList.toggle('active',x.dataset.settingsValue===(density?.preference||mode))});o.classList.toggle('active',mode===(density?.preference||'auto'));row.appendChild(o)}popover.appendChild(row);
 const fs=fullscreenApi();if(fs){section('Window');popover.appendChild(option(fs.active()?'Exit full screen':'Full screen','fullscreen',()=>{closePopover();Promise.resolve().then(fs.toggle).catch(()=>{})}))}
 const safety=root.InkDOSWorkSafety;if(safety){section('Recovery');const modes=[['on','Keep recovery drafts'],['password','Drafts with password'],['off','No recovery drafts']].map(([m,label])=>{const b=option(label,'recovery-'+m,async()=>{await safety.setDraftsMode(m);sync()});popover.appendChild(b);return [m,b]});const sync=()=>{const cur=safety.draftsMode;for(const [m,b] of modes){b.classList.toggle('active',m===cur);b.setAttribute('aria-pressed',String(m===cur))}};sync()}
 // INKDOS:FROZEN-LEGACY legacy-pdf-signer: the web edition no longer lists the PDF signer here (betaTools.openPdfTools stays)
 if(doc.documentElement.dataset.inkdosHost==='tauri'&&root.InkDOSDesktop?.betaTools){const desktopBeta=root.InkDOSDesktop.betaTools,tools=desktopBeta.tools.length?desktopBeta.tools:[{id:'pdf',title:'PDF tools (beta)'}];section('Beta tools');for(const tool of tools)popover.appendChild(option(String(tool.title),'beta-'+tool.id,()=>{closePopover();desktopBeta.open(tool.id)}))}
 const api=root.InkDOSLocalization;if(api){section('Language');for(const language of api.languages){const o=option(language.label,language.code,async()=>{await api.setLanguage(language.code,{storageKey:languageKey()});closePopover()});o.classList.toggle('active',language.code===api.currentLanguage);popover.appendChild(o)}}
 positionPopover(anchor);api?.apply?.()}

// Shared Save menu for workspaces that register root.InkDOSSaveProvider:
// {fileName(), canOverwrite(), buildOverwrite()→Blob, afterOverwrite(), saveCopy(), exports:[{label,note,run}], onError(e)}.
let saveLayer=null;
function closeSaveMenu(){if(saveLayer)saveLayer.hidden=true}
function saveCard(build){if(!saveLayer){saveLayer=doc.createElement('div');saveLayer.className='inkdos-save-overlay';saveLayer.hidden=true;saveLayer.addEventListener('pointerdown',e=>{if(e.target===saveLayer)closeSaveMenu()});doc.addEventListener('keydown',e=>{if(e.key==='Escape'&&saveLayer&&!saveLayer.hidden)closeSaveMenu()});doc.body.appendChild(saveLayer)}const card=doc.createElement('div');card.className='inkdos-save-card';card.setAttribute('role','dialog');card.setAttribute('aria-modal','true');build(card);saveLayer.replaceChildren(card);saveLayer.hidden=false;card.querySelector('button.primary,button:not(:disabled)')?.focus();root.InkDOSLocalization?.apply?.()}
function saveOption(label,cls,run,disabled,note){const b=doc.createElement('button');b.type='button';b.className='inkdos-save-option '+(cls||'');const t=doc.createElement('strong');t.textContent=label;b.appendChild(t);if(note){const n=doc.createElement('small');n.textContent=note;b.appendChild(n)}b.disabled=!!disabled;b.addEventListener('click',async()=>{closeSaveMenu();try{await run()}catch(e){console.error(e)}});return b}
function saveHeading(card,title,text){const h=doc.createElement('h2');h.textContent=title;card.appendChild(h);if(text){const p=doc.createElement('p');p.textContent=text;card.appendChild(p)}}
function writableOriginal(P){const h=root.InkDOSCurrentHandle;if(!h||typeof h.createWritable!=='function')return null;const name=String(P.fileName?.()||'');if(h.name&&name&&h.name!==name)return null;return h}
async function overwriteOriginal(P,h){try{if(typeof h.requestPermission==='function'){const state=await h.requestPermission({mode:'readwrite'});if(state!=='granted')throw new Error('This host did not allow writing to the original file. Save a copy instead.')}const blob=await P.buildOverwrite();const w=await h.createWritable();try{await w.write(blob);await w.close()}catch(e){try{await w.abort?.()}catch(_){}throw e}await P.afterOverwrite?.()}catch(e){if(typeof P.onError==='function')P.onError(e);else console.error(e)}}
function showSaveMenu(P){const h=P.canOverwrite?.()?writableOriginal(P):null,name=String(P.fileName?.()||'');saveCard(card=>{saveHeading(card,'Save');card.appendChild(saveOption('Overwrite original','',()=>confirmOverwrite(P,h),!h,h?'Replace '+name:'Available when the file was opened from the host file manager'));card.appendChild(saveOption('Save edited copy','primary',()=>P.saveCopy(),false,'Original stays intact'));const ex=(P.exports||[]).filter(Boolean);if(ex.length){const l=doc.createElement('div');l.className='inkdos-save-label';l.textContent='Export';card.appendChild(l);const row=doc.createElement('div');row.className='inkdos-save-row';for(const x of ex)row.appendChild(saveOption(x.label,'',x.run,false,x.note));card.appendChild(row)}card.appendChild(saveOption('Cancel','plain',()=>{}))})}
function confirmOverwrite(P,h){saveCard(card=>{saveHeading(card,'Overwrite the original?','The original file will be replaced by this edited version. If the host interrupts the write, the original can be damaged and cannot be recovered by InkDOS.');card.appendChild(saveOption('Save an edited copy instead','primary',()=>P.saveCopy(),false,'Keeps the original intact (recommended)'));card.appendChild(saveOption('Overwrite anyway','danger',()=>overwriteOriginal(P,h)));card.appendChild(saveOption('Cancel','plain',()=>{}))})}
function installFrameActions(){if(frameInstalled||!drawer)return;const header=doc.querySelector('header.topbar,header.framebar,header');const left=header?.querySelector('.frame-left');if(!header||!left)return;frameInstalled=true;doc.documentElement.classList.add('inkdos-frame-actions');
 const home=header.querySelector('a[aria-label="Home"],a[title="Home"]');if(home&&left.firstChild!==home)left.insertBefore(home,left.firstChild);
 const open=drawerTarget(['openMenuBtn','menuOpen','openBtn']),save=drawerTarget(['saveMenuBtn','menuSave','saveBtn']),share=drawerTarget(['shareMenuBtn','menuShare','shareBtn']);
 // New document: a + at the far top-left, before every other header symbol.
 const create=drawerTarget(['newMenuBtn','menuNew','newBtn']);if(create)left.insertBefore(proxyButton('new',(create.textContent||'New').replace(/⌘.*/,'').trim()||'New',create),left.firstChild);
 let ref=home?home.nextSibling:left.firstChild;for(const b of [open&&proxyButton('open',(open.textContent||'Open').replace(/⌘.*/,'').trim()||'Open',open),save&&proxyButton('save',(save.textContent||'Save').replace(/⌘.*/,'').trim()||'Save',save)].filter(Boolean))left.insertBefore(b,ref);
 let right=header.querySelector('.frame-right');if(!right){right=doc.createElement('div');right.className='frame-side frame-right';header.appendChild(right)}right.removeAttribute('aria-hidden');right.classList.add('inkdos-frame-right');
 const sun=frameButton('sun','Settings',()=>{if(activeButton===sun&&!popover.hidden){closePopover();return}showSettings(sun)});right.appendChild(sun);if(share)right.appendChild(proxyButton('share','Share',share));else{const slot=frameButton('share','Share',()=>{});slot.disabled=true;right.appendChild(slot);let tries=0;const timer=setInterval(()=>{const t=drawerTarget(['shareMenuBtn','menuShare','shareBtn']);if(t){clearInterval(timer);slot.replaceWith(proxyButton('share','Share',t))}else if(++tries>40){clearInterval(timer);slot.remove()}},100)}
 const status=doc.querySelector('footer.statusbar,footer.bottom-shell,footer');if(status){const help=frameButton('help','Help',()=>{if(activeButton===help&&!popover.hidden){closePopover();return}showHelp(help)});help.classList.add('inkdos-status-help');status.appendChild(help)}
 doc.addEventListener('pointerdown',event=>{if(popover.hidden)return;const t=event.target;if(t instanceof Element&&t.closest('.inkdos-frame-action'))return;if(!popover.contains(t))closePopover()},true);doc.addEventListener('keydown',event=>{if(event.key==='Escape'&&!popover.hidden){const back=activeButton;closePopover();back?.focus?.()}})}
function install(){if(!doc||!appContext()||strip)return false;drawer=doc.getElementById('generalMenu')||doc.querySelector('aside.drawer');if(!drawer)return false;strip=doc.createElement('div');strip.className='inkdos-settings-strip';strip.setAttribute('role','group');strip.setAttribute('aria-label','Settings');strip.append(button('appearance','◐','Appearance'),button('interface','↔','Interface'),button('language','文A','Language'),button('help','?','Help'));drawer.appendChild(strip);popover=doc.createElement('div');popover.className='inkdos-settings-popover';popover.hidden=true;popover.setAttribute('role','dialog');popover.setAttribute('aria-label','Settings');doc.body.appendChild(popover);suppressLegacyControls();watchLegacyControls();const localization=root.InkDOSLocalization;if(localization)localization.install({storageKey:languageKey(),legacyStorageKeys:[legacyLanguageKey()].filter(Boolean)}).then(()=>localization.apply());doc.addEventListener(TRANSIENT_EVENT,event=>{if(event.detail?.owner!==transientOwner)closePopover()});doc.addEventListener('pointerdown',event=>{if(popover.hidden)return;if(popover.contains(event.target)||strip.contains(event.target)||(event.target instanceof Element&&event.target.closest('.inkdos-frame-action')))return;closePopover()});doc.addEventListener('click',event=>{if(popover.hidden)return;const target=event.target instanceof Element?event.target:null;if(target?.closest('.formatbar,.toolbar,.toolstrip,.command-scroll')&&!strip.contains(target))closePopover()},true);root.addEventListener?.('resize',closePopover,{passive:true});installFrameActions();return true}
function boot(){if(install())return;let attempts=0;const timer=setInterval(()=>{attempts+=1;if(install()||attempts>20)clearInterval(timer)},50)}
if(doc){if(doc.readyState==='loading')doc.addEventListener('DOMContentLoaded',boot,{once:true});else boot()}
// Beta tools (web edition): the PDF tools page opens in a new tab, or in the workspace's own panel when
// its provider offers openTools() (the PDF workspace does). A workspace that sets
// root.InkDOSBetaToolsProvider ({currentPdf()→{name,bytes}, openPdf(file)}) hands it the PDF it has open
// and receives results back (this script may load after the workspace, hence the global).
const betaTools={provider:null,register(p){betaTools.provider=p||null},openPdfTools(){const p=betaTools.provider||root.InkDOSBetaToolsProvider;try{if(p&&typeof p.openTools==='function'&&p.openTools())return}catch(e){console.error(e)}const url=new URL('../../labs/pdf/index.html?from=app',root.location.href);if(!root.open(url.href,'_blank'))root.location.href=url.href}};
// Only the PDF tools page itself may ask for the open PDF or hand one back, not any other page of this origin.
function fromPdfTools(source){try{return !!source&&source!==root&&source.location.pathname===new URL('../../labs/pdf/index.html',root.location.href).pathname}catch(_){return false}}
root.addEventListener?.('message',async event=>{const data=event.data,p=betaTools.provider||root.InkDOSBetaToolsProvider;if(event.origin!==root.location.origin||!data||!p||!fromPdfTools(event.source))return;try{if(data.type==='inkdos-lab-ready'&&p.currentPdf){const f=await p.currentPdf();if(f&&f.bytes&&f.bytes.length)event.source?.postMessage({type:'inkdos-lab-file',name:f.name,bytes:f.bytes},root.location.origin)}else if(data.type==='inkdos-lab-result'&&p.openPdf){p.openPdf(new File([data.bytes],String(data.name||'document.pdf'),{type:'application/pdf'}))}}catch(e){console.error(e)}});
root.InkDOSBetaTools=Object.freeze({register:betaTools.register,openPdfTools:betaTools.openPdfTools});
root.InkDOSSettingsStrip=Object.freeze({install,get context(){return appContext()},get languageStorageKey(){return languageKey()}});
})(globalThis);
