(function(root){'use strict';
const doc=typeof document!=='undefined'?document:null;
const APPS=new Set(['documents','spreadsheets','presentations','pdf','epub','txt']),LANGUAGE_KEY='inkdos2:language';
const TRANSIENT_EVENT='inkdos:transient-open',transientOwner={kind:'settings-strip'};
let context=null,drawer=null,strip=null,popover=null,activeButton=null,mutationObserver=null;
function appContext(){if(context)return context;let parts=[];try{parts=decodeURIComponent(root.location?.pathname||'').split('/').filter(Boolean)}catch(_){}context=parts.find(part=>APPS.has(part))||null;return context}
function languageKey(){return LANGUAGE_KEY}
function legacyLanguageKey(){const app=appContext();return app?'inkdos2:'+app+':language':null}
function button(kind,icon,label){const item=doc.createElement('button');item.type='button';item.className='inkdos-settings-button';item.dataset.settingsItem=kind;item.setAttribute('aria-haspopup','dialog');item.setAttribute('aria-expanded','false');item.title=label;item.setAttribute('aria-label',label);item.innerHTML='<span class="inkdos-settings-icon" aria-hidden="true">'+icon+'</span><span class="inkdos-settings-label">'+label+'</span>';item.addEventListener('click',()=>toggle(kind,item));return item}
function option(label,value,onChoose){const item=doc.createElement('button');item.type='button';item.className='inkdos-settings-option';item.textContent=label;item.dataset.settingsValue=value;item.addEventListener('click',onChoose);return item}
function closePopover(){if(!popover)return;popover.hidden=true;if(activeButton)activeButton.setAttribute('aria-expanded','false');activeButton=null}
function claimTransient(){if(!doc)return;try{doc.dispatchEvent(new CustomEvent(TRANSIENT_EVENT,{detail:{owner:transientOwner}}))}catch(_){}}
function positionPopover(anchor){if(!popover||!anchor)return;popover.hidden=false;const rect=anchor.getBoundingClientRect(),margin=12,width=popover.offsetWidth||286,height=popover.offsetHeight||280;let left=Math.min(root.innerWidth-margin-width,Math.max(margin,rect.right-width));if(!Number.isFinite(left))left=margin;let top=rect.top-height-8;if(top<margin)top=Math.min(root.innerHeight-margin-height,rect.bottom+8);popover.style.left=Math.max(margin,left)+'px';popover.style.top=Math.max(margin,top)+'px'}
function openPopover(anchor,title){if(!popover)return;claimTransient();popover.replaceChildren();const heading=doc.createElement('div');heading.className='inkdos-settings-popover-title';heading.textContent=title;popover.appendChild(heading);if(activeButton&&activeButton!==anchor)activeButton.setAttribute('aria-expanded','false');activeButton=anchor;anchor.setAttribute('aria-expanded','true');positionPopover(anchor)}
function markActive(selector,value){if(!popover)return;for(const item of popover.querySelectorAll(selector))item.classList.toggle('active',item.dataset.settingsValue===value)}
function appearanceMode(){const current=drawer?.querySelector('[data-appearance-choice].active,[data-appearance-choice][aria-pressed="true"],[data-appearance-mode].active,[data-appearance-mode][aria-pressed="true"]');return current?.dataset.appearanceChoice||current?.dataset.appearanceMode||'system'}
function showAppearance(anchor){openPopover(anchor,'Appearance');for(const [mode,label] of [['light','Light'],['dark','Dark'],['system','System']])popover.appendChild(option(label,mode,()=>{const target=drawer?.querySelector('[data-appearance-choice="'+mode+'"],[data-appearance-mode="'+mode+'"]');target?.click();markActive('[data-settings-value]',mode);closePopover()}));markActive('[data-settings-value]',appearanceMode())}
function showInterface(anchor){openPopover(anchor,'Interface');const api=root.InkDOSUiDensity;for(const [mode,label] of [['auto','Auto'],['desktop','Desktop'],['mobile','Smartphone']])popover.appendChild(option(label,mode,()=>{api?.set?.(mode);markActive('[data-settings-value]',api?.preference||mode);closePopover()}));markActive('[data-settings-value]',api?.preference||'auto')}
function showLanguage(anchor){openPopover(anchor,'Language');const api=root.InkDOSLocalization;if(!api)return;for(const language of api.languages){popover.appendChild(option(language.label,language.code,async()=>{await api.setLanguage(language.code,{storageKey:languageKey()});markActive('[data-settings-value]',api.currentLanguage);closePopover()}))}markActive('[data-settings-value]',api.currentLanguage)}
function clickHelp(){const entry=doc.querySelector('[data-inkdos-help-entry]');if(entry){closePopover();entry.click();return true}return false}
function clickUpdater(){const candidate=doc.querySelector('[title="Check for updates"],[aria-label="Check for updates"],[data-command="updater.check"]');if(candidate){closePopover();candidate.click();return true}return false}
function showHelp(anchor){openPopover(anchor,'Help');popover.appendChild(option('Getting started','getting-started',()=>clickHelp()));popover.appendChild(option('Keyboard shortcuts','keyboard-shortcuts',()=>clickHelp()));popover.appendChild(option('File compatibility','file-compatibility',()=>clickHelp()));if(doc.querySelector('[title="Check for updates"],[aria-label="Check for updates"],[data-command="updater.check"]'))popover.appendChild(option('Check for updates','updates',()=>clickUpdater()));const about=option('About InkDOS','about',()=>{let note=popover.querySelector('.inkdos-settings-help-note');if(note){note.remove();return}note=doc.createElement('div');note.className='inkdos-settings-help-note';note.textContent='InkDOS keeps workspace editing local-first and offline-capable. Interface language changes presentation only; file content is never translated.';popover.appendChild(note);root.InkDOSLocalization?.apply?.()});popover.appendChild(about)}
function toggle(kind,anchor){if(!popover)return;if(activeButton===anchor&&!popover.hidden){closePopover();return}if(kind==='appearance')showAppearance(anchor);else if(kind==='interface')showInterface(anchor);else if(kind==='language')showLanguage(anchor);else if(kind==='help')showHelp(anchor)}
function suppressLegacyControls(){if(!drawer)return;const appearance=drawer.querySelector('[data-appearance-choice]')?.closest('.drawer-section');appearance?.setAttribute('data-inkdos-settings-redundant','');const density=drawer.querySelector('[data-inkdos-density-control]');if(density){density.setAttribute('data-inkdos-settings-redundant','');const label=density.previousElementSibling;if(label?.classList.contains('inkdos-density-label'))label.setAttribute('data-inkdos-settings-redundant','')}const help=drawer.querySelector('[data-inkdos-help-entry]')?.closest('.inkdos-help-menu-list');help?.setAttribute('data-inkdos-settings-redundant','')}
function watchLegacyControls(){if(!drawer||mutationObserver||typeof MutationObserver!=='function')return;mutationObserver=new MutationObserver(()=>{suppressLegacyControls();if(drawer.hidden)closePopover()});mutationObserver.observe(drawer,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']})}
function install(){if(!doc||!appContext()||strip)return false;drawer=doc.getElementById('generalMenu')||doc.querySelector('aside.drawer');if(!drawer)return false;strip=doc.createElement('div');strip.className='inkdos-settings-strip';strip.setAttribute('role','group');strip.setAttribute('aria-label','Settings');strip.append(button('appearance','◐','Appearance'),button('interface','↔','Interface'),button('language','文A','Language'),button('help','?','Help'));drawer.appendChild(strip);popover=doc.createElement('div');popover.className='inkdos-settings-popover';popover.hidden=true;popover.setAttribute('role','dialog');popover.setAttribute('aria-label','Settings');doc.body.appendChild(popover);suppressLegacyControls();watchLegacyControls();const localization=root.InkDOSLocalization;if(localization)localization.install({storageKey:languageKey(),legacyStorageKeys:[legacyLanguageKey()].filter(Boolean)}).then(()=>localization.apply());doc.addEventListener(TRANSIENT_EVENT,event=>{if(event.detail?.owner!==transientOwner)closePopover()});doc.addEventListener('pointerdown',event=>{if(popover.hidden)return;if(popover.contains(event.target)||strip.contains(event.target))return;closePopover()});doc.addEventListener('click',event=>{if(popover.hidden)return;const target=event.target instanceof Element?event.target:null;if(target?.closest('.formatbar,.toolbar,.toolstrip,.command-scroll')&&!strip.contains(target))closePopover()},true);root.addEventListener?.('resize',closePopover,{passive:true});return true}
function boot(){if(install())return;let attempts=0;const timer=setInterval(()=>{attempts+=1;if(install()||attempts>20)clearInterval(timer)},50)}
if(doc){if(doc.readyState==='loading')doc.addEventListener('DOMContentLoaded',boot,{once:true});else boot()}
root.InkDOSSettingsStrip=Object.freeze({install,get context(){return appContext()},get languageStorageKey(){return languageKey()}});
})(globalThis);
