"""PDF tools (beta): the bundled ICP-Brasil trust list holds exactly the pinned roots.

Trust anchors decide when a signature is reported as "ICP-Brasil certificate". They must be the
pinned document-signing roots (see labs/pdf/trust/PROVENANCE.txt) and match their fingerprints.
"""
import base64
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TRUST = ROOT / "labs" / "pdf" / "trust" / "icp-brasil.js"
PINS = {
    "Autoridade Certificadora Raiz Brasileira v5": "caa53fc6091c6951887c976e378f6ef89aa6377c55d97b6475422b71ed7e9b17",
    "Autoridade Certificadora Raiz Brasileira v6": "3bdb9b509352f1d3d71c2bf64d9a38a4e6cebda27809d77f7ac476cbde6e314a",
    "Autoridade Certificadora Raiz Brasileira v7": "5657e70580eb678983f3ed7dfce091d84cae6549389a47fccda8d0e4dc2cf576",
    "Autoridade Certificadora Raiz Brasileira v12": "d8478e37ce19c690cf657381e68fe600e4e1a042536830f06847e03e554c4b01",
}


def load():
    text = TRUST.read_text(encoding="utf-8")
    assert text.startswith("/* Generated by scripts/build_icp_brasil_trust.py")
    start = text.index("Object.freeze(") + len("Object.freeze(")
    return json.loads(text[start:text.rindex(")")])


def test_anchors_are_exactly_the_pinned_roots():
    data = load()
    got = {a["name"]: hashlib.sha256(base64.b64decode(a["der"])).hexdigest() for a in data["anchors"]}
    assert got == PINS, got
    assert all(a["sha256"] == PINS[a["name"]] for a in data["anchors"])


def test_intermediates_are_not_anchors():
    data = load()
    anchor_der = {a["der"] for a in data["anchors"]}
    assert data["intermediates"] and not any(i["der"] in anchor_der for i in data["intermediates"])


def test_page_loads_the_list_before_the_signature_module():
    page = (ROOT / "labs" / "pdf" / "index.html").read_text(encoding="utf-8")
    assert page.index('src="trust/icp-brasil.js"') < page.index('src="sign.js"')


if __name__ == "__main__":
    test_anchors_are_exactly_the_pinned_roots()
    test_intermediates_are_not_anchors()
    test_page_loads_the_list_before_the_signature_module()
    print("PDF tools ICP-Brasil trust list contract: OK")
