(function(g){'use strict';
const NS=g.InkDOS2Epub=g.InkDOS2Epub||{};
function blockOf(node,surface){let el=node&&node.nodeType===1?node:node&&node.parentElement;while(el&&el!==surface&&!el.matches?.('[data-anchor]'))el=el.parentElement;return el&&el!==surface&&el.matches('[data-anchor]')?el:null}
function textOffset(block,node,offset){try{const r=document.createRange();r.selectNodeContents(block);r.setEnd(node,offset);return r.toString().length}catch(_){return 0}}
function capture(surface){const sel=getSelection&&getSelection();if(!sel||sel.rangeCount<1||sel.isCollapsed)return null;const r=sel.getRangeAt(0);if(!surface.contains(r.commonAncestorContainer))return null;const startBlock=blockOf(r.startContainer,surface),endBlock=blockOf(r.endContainer,surface);if(!startBlock||!endBlock)return null;const blocks=Array.from(surface.querySelectorAll('[data-anchor]')),a=blocks.indexOf(startBlock),b=blocks.indexOf(endBlock);if(a<0||b<0)return null;const lo=Math.min(a,b),hi=Math.max(a,b),forward=a<=b;const segments=[];for(let i=lo;i<=hi;i++){const block=blocks[i],len=(block.textContent||'').length;let start=0,end=len;if(block===startBlock)start=textOffset(block,r.startContainer,r.startOffset);if(block===endBlock)end=textOffset(block,r.endContainer,r.endOffset);if(!forward){if(block===endBlock)start=textOffset(block,r.endContainer,r.endOffset);if(block===startBlock)end=textOffset(block,r.startContainer,r.startOffset)}start=Math.max(0,Math.min(len,start));end=Math.max(start,Math.min(len,end));if(end>start)segments.push({anchor:block.dataset.anchor||'',start,end})}return segments.length?segments:null}
function unwrap(surface){for(const m of Array.from(surface.querySelectorAll('mark[data-inkdos-highlight]'))){const p=m.parentNode;while(m.firstChild)p.insertBefore(m.firstChild,m);p.removeChild(m);p.normalize()}}
function point(block,offset){const walker=document.createTreeWalker(block,NodeFilter.SHOW_TEXT);let n,acc=0,last=null;while((n=walker.nextNode())){last=n;const len=n.nodeValue.length;if(offset<=acc+len)return {node:n,offset:Math.max(0,offset-acc)};acc+=len}return last?{node:last,offset:last.nodeValue.length}:null}
function wrap(block,start,end,color,id){if(end<=start)return;const a=point(block,start),b=point(block,end);if(!a||!b)return;try{const r=document.createRange();r.setStart(a.node,a.offset);r.setEnd(b.node,b.offset);if(r.collapsed)return;const mark=document.createElement('mark');mark.dataset.inkdosHighlight=id;mark.dataset.highlightColor=color;mark.className='inkdos-highlight highlight-'+color;const frag=r.extractContents();mark.append(frag);r.insertNode(mark)}catch(_){}}
function render(surface,highlights){unwrap(surface);const map=new Map();for(const h of highlights||[])for(const s of h.segments||[]){if(!map.has(s.anchor))map.set(s.anchor,[]);map.get(s.anchor).push({start:s.start,end:s.end,color:h.color,id:h.id})}for(const [anchor,segs] of map){const esc=(g.CSS&&CSS.escape)?CSS.escape(anchor):anchor.replace(/["\\]/g,'\\$&'),block=surface.querySelector('[data-anchor="'+esc+'"]');if(!block)continue;segs.sort((x,y)=>y.start-x.start||y.end-x.end);for(const s of segs)wrap(block,s.start,s.end,s.color,s.id)}}
NS.ReaderAnnotations={capture,render,unwrap};
})(globalThis);
