(function(global){'use strict';
const NS=global.InkDOS2Epub=global.InkDOS2Epub||{},P=NS.ContentProjector;
function fail(code,message){const e=new Error(message);e.code=code;throw e}
function abort(signal){if(signal&&signal.aborted)fail('aborted','EPUB operation aborted')}
function stripDoctype(text){if(/<!ENTITY/i.test(text))fail('xml-entity','XML entity declarations are not allowed');if(/<!DOCTYPE[^>]*\[/i.test(text))fail('xml-doctype','XML internal subsets are not allowed');return text.replace(/<!DOCTYPE[^>]*>/ig,'')}
function decodeXmlText(bytes,label){
 const v=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes||0);let encoding='utf-8',start=0;
 if(v.length>=2&&v[0]===0xff&&v[1]===0xfe){encoding='utf-16le';start=2}
 else if(v.length>=2&&v[0]===0xfe&&v[1]===0xff){encoding='utf-16be';start=2}
 else if(v.length>=2&&v[0]===0x3c&&v[1]===0x00)encoding='utf-16le';
 else if(v.length>=2&&v[0]===0x00&&v[1]===0x3c)encoding='utf-16be';
 try{
  if(encoding==='utf-16le')return new TextDecoder('utf-16le',{fatal:true}).decode(v.subarray(start));
  if(encoding==='utf-16be')return new TextDecoder('utf-16be',{fatal:true}).decode(v.subarray(start));
  return new TextDecoder('utf-8',{fatal:true}).decode(v);
 }catch(_){fail('xml-encoding',label+' is not valid UTF-8/UTF-16 XML')}
}
function parseXml(bytes,label){const text=decodeXmlText(bytes,label);const safe=stripDoctype(text);const doc=new DOMParser().parseFromString(safe,'application/xml');if(Array.from(doc.getElementsByTagName('*')).some(x=>String(x.localName||'').toLowerCase()==='parsererror'))fail('xml-parse','Invalid '+label);return doc}
function els(root,name){return Array.from(root.getElementsByTagName('*')).filter(x=>String(x.localName||'').toLowerCase()===name)}
function attr(el,name){if(!el)return null;for(const a of Array.from(el.attributes||[]))if(a.localName===name)return a.value;return null}
function dirname(path){const i=path.lastIndexOf('/');return i<0?'':path.slice(0,i+1)}
function safeDecode(s){try{return decodeURIComponent(s)}catch(_){return s}}
function normalizeResolved(raw){const s=String(raw||'');if(!s||/[\x00-\x1f\x7f]/.test(s)||s.includes('\\')||s.startsWith('/')||/^[A-Za-z]:/.test(s))fail('resource-path','Unsafe EPUB resource path');const out=[];for(const part of s.split('/')){if(!part||part==='.')continue;if(part==='..'){if(!out.length)fail('resource-path','EPUB resource escapes package root');out.pop()}else out.push(part)}if(!out.length)fail('resource-path','EPUB resource path resolves to empty');return out.join('/')}
function resolve(baseFile,href){const raw=String(href||'').trim(),hash=raw.indexOf('#'),beforeHash=hash>=0?raw.slice(0,hash):raw,query=beforeHash.indexOf('?'),pathPart=query>=0?beforeHash.slice(0,query):beforeHash,fragment=hash>=0?safeDecode(raw.slice(hash+1)):'';if(!pathPart)return {path:baseFile,fragment};if(/^[A-Za-z][A-Za-z0-9+.-]*:/.test(pathPart)||pathPart.startsWith('//'))return {external:true,href:raw};const joined=dirname(baseFile)+safeDecode(pathPart);return {path:normalizeResolved(joined),fragment}}
function textFirst(doc,name){const e=els(doc,name)[0];return e?(e.textContent||'').trim():''}
function propertyTokens(v){return new Set(String(v||'').trim().split(/\s+/).filter(Boolean))}
async function build(pkg,options={}){const signal=options.signal||null;abort(signal);const cdoc=parseXml(await pkg.read('META-INF/container.xml',{signal}),'container.xml'),rootfile=els(cdoc,'rootfile')[0],opfPath=attr(rootfile,'full-path');if(!opfPath)fail('package','EPUB rootfile is missing');const root=normalizeResolved(safeDecode(opfPath));if(!pkg.has(root))fail('package','EPUB package document is missing: '+root);abort(signal);const opf=parseXml(await pkg.read(root,{signal}),'package document');const title=textFirst(opf,'title')||'Untitled EPUB',manifest=new Map();for(const item of els(opf,'item')){const id=attr(item,'id'),href=attr(item,'href'),mediaType=(attr(item,'media-type')||'').toLowerCase(),fallback=attr(item,'fallback')||'',properties=propertyTokens(attr(item,'properties'));if(!id||!href)continue;const r=resolve(root,href);if(r.external)continue;if(manifest.has(id))fail('manifest','Duplicate manifest id: '+id);manifest.set(id,{id,href,path:r.path,mediaType,fallback,properties})}if(!manifest.size)fail('manifest','EPUB manifest is empty');function resolveSpineItem(item){let candidate=item;const seen=new Set();while(candidate){if(seen.has(candidate.id))fail('spine-fallback','EPUB manifest fallback cycle at: '+candidate.id);seen.add(candidate.id);if(candidate.mediaType==='application/xhtml+xml')return candidate;const fallbackId=String(candidate.fallback||'').trim();if(!fallbackId)return null;candidate=manifest.get(fallbackId);if(!candidate)fail('spine-fallback','EPUB manifest fallback is missing: '+fallbackId)}return null}const spine=[];for(const ref of els(opf,'itemref')){const idref=attr(ref,'idref'),item=manifest.get(idref);if(!item)fail('spine','Spine references missing manifest id: '+idref);const resolved=resolveSpineItem(item);if(!resolved)continue;spine.push({...resolved,linear:(attr(ref,'linear')||'yes').toLowerCase()!=='no'})}if(!spine.length)fail('spine','EPUB has no readable XHTML spine items');
  function resolveResourceFrom(base,href){const r=resolve(base,href);if(r.external||!r.path||!pkg.has(r.path))return null;const item=Array.from(manifest.values()).find(x=>x.path===r.path);if(!item)return null;return {path:r.path,mediaType:item.mediaType,fragment:r.fragment||''}}
  function resolveLinkFrom(base,href){const r=resolve(base,href);if(r.external)return {kind:'external',href:String(href)};if(!r.path||!pkg.has(r.path))return null;return {kind:'internal',path:r.path,fragment:r.fragment||''}}
  const chapters=[];for(let i=0;i<spine.length;i++){abort(signal);const item=spine[i];if(!pkg.has(item.path))fail('spine','Spine document is missing: '+item.path);const doc=parseXml(await pkg.read(item.path,{signal}),'spine XHTML '+item.path);const blocks=P.projectDocument(doc,{anchorPrefix:'s'+i+':',resolveResource:href=>resolveResourceFrom(item.path,href),resolveLink:href=>resolveLinkFrom(item.path,href)});if(!blocks.length)continue;const firstHeading=blocks.find(b=>b.type==='heading');chapters.push({id:'spine-'+i,spineIndex:i,path:item.path,title:firstHeading?firstHeading.runs.filter(r=>r.kind==='text').map(r=>r.text).join('').trim()||('Chapter '+(i+1)):('Chapter '+(i+1)),blocks})}if(!chapters.length)fail('content','EPUB has no readable projected content');
  let toc=[];const navItem=Array.from(manifest.values()).find(x=>x.properties.has('nav'));if(navItem&&pkg.has(navItem.path)){try{const navDoc=parseXml(await pkg.read(navItem.path,{signal}),'navigation document'),navs=els(navDoc,'nav'),tocNav=navs.find(n=>String(attr(n,'type')||'').split(/\s+/).includes('toc'))||navs[0];if(tocNav){for(const a of els(tocNav,'a')){const label=(a.textContent||'').replace(/\s+/g,' ').trim(),href=attr(a,'href');const r=resolve(navItem.path,href);if(label&&r&&!r.external&&pkg.has(r.path))toc.push({label,path:r.path,fragment:r.fragment||''})}}}catch(_){toc=[]}}
  if(!toc.length)toc=chapters.map(c=>({label:c.title,path:c.path,fragment:''}));
  return Object.freeze({title,rootfile:root,manifest:Object.freeze(Array.from(manifest.values()).map(x=>Object.freeze({...x,properties:Object.freeze(Array.from(x.properties))}))),spine:Object.freeze(spine.map(x=>Object.freeze({...x,properties:Object.freeze(Array.from(x.properties))}))),chapters:Object.freeze(chapters.map(c=>Object.freeze({...c,blocks:Object.freeze(c.blocks.map(b=>Object.freeze({...b,runs:Object.freeze(b.runs.map(r=>Object.freeze({...r})))})))}))),toc:Object.freeze(toc.map(x=>Object.freeze({...x}))),sourceBytes:pkg.sourceBytes.slice(0),sourceSize:pkg.inputBytes});
}
NS.BookModel={build,parseXml,decodeXmlText,resolve};
})(globalThis);