(function(global){'use strict';
const NS=global.InkDOS2Documents=global.InkDOS2Documents||{},$=id=>document.getElementById(id),PX_PER_CM=96/2.54;
function clamp(v,min,max,fallback){v=Number(v);return Number.isFinite(v)?Math.max(min,Math.min(max,v)):fallback}
function create({state,session,pagesHost,surface,editor,navigation,chrome}={}){let formatBtn=null,formatPopover=null,layoutBtn=null,layoutPanel=null,reflowing=false,numberObserver=null;
 function active(){return !!session.active}
 function position(anchor,panel){if(!anchor||!panel||panel.hidden)return;const a=anchor.getBoundingClientRect(),w=panel.offsetWidth||320,h=panel.offsetHeight||420;panel.style.left=Math.max(8,Math.min(innerWidth-w-8,a.left))+'px';panel.style.top=Math.max(8,Math.min(innerHeight-h-8,a.bottom+6))+'px'}
 function closeAll(){if(formatPopover)formatPopover.hidden=true;if(layoutPanel)layoutPanel.hidden=true}
 function selectedBlocks(){const r=(()=>{const sel=getSelection();if(sel&&sel.rangeCount){const x=sel.getRangeAt(0);if(pagesHost.contains(x.commonAncestorContainer))return x}return null})();const out=new Set();if(r)pagesHost.querySelectorAll('.page-content p,.page-content h1,.page-content h2,.page-content h3,.page-content li,.page-content td').forEach(b=>{try{if(r.intersectsNode(b))out.add(b)}catch(_){}});if(!out.size){const b=editor.currentSelectionBlock?.()||editor.selectionBlock?.();if(b)out.add(b)}return [...out]}
 function markFormatting(){selectedBlocks().forEach(b=>b.dataset.d1Formatting='1')}
 function applyCommand(command,value){if(!active())return;editor.rememberSelection();editor.cmd(command,value);markFormatting()}
 function applyHighlight(value){if(!active())return;editor.rememberSelection();editor.restoreSelection();let ok=false;try{ok=document.execCommand('hiliteColor',false,value)}catch(_){}if(!ok)try{document.execCommand('backColor',false,value)}catch(_){}editor.rememberSelection();markFormatting();editor.markDirty();chrome.status('Highlight applied')}
 function insertToolbarControls(){const bar=$('formatbar'),spacer=bar?.querySelector('.toolbar-end-spacer');if(!bar||!spacer||$('d1FormatBtn'))return;const sep=document.createElement('span');sep.className='separator';sep.dataset.d1='1';formatBtn=document.createElement('button');formatBtn.id='d1FormatBtn';formatBtn.type='button';formatBtn.className='fmt-btn';formatBtn.title='Text color and effects';formatBtn.setAttribute('aria-label','Text color and effects');formatBtn.textContent='Aa';layoutBtn=document.createElement('button');layoutBtn.id='d1LayoutBtn';layoutBtn.type='button';layoutBtn.className='fmt-btn';layoutBtn.title='Page layout';layoutBtn.setAttribute('aria-label','Page layout');layoutBtn.textContent='Page';bar.insertBefore(sep,spacer);bar.insertBefore(formatBtn,spacer);bar.insertBefore(layoutBtn,spacer)}
 function buildFormatPopover(){if($('d1FormatPopover')){formatPopover=$('d1FormatPopover');return}formatPopover=document.createElement('section');formatPopover.id='d1FormatPopover';formatPopover.className='d1-popover';formatPopover.hidden=true;formatPopover.setAttribute('aria-label','Text color and effects');formatPopover.innerHTML='<div class="d1-head"><strong>Text formatting</strong><button id="d1FormatClose" class="d1-close" type="button" aria-label="Close">×</button></div><div class="d1-format-row"><label class="d1-color">Text <input id="d1FontColor" type="color" value="#202124"></label><label class="d1-color">Highlight <input id="d1HighlightColor" type="color" value="#ffff00"></label></div><div class="d1-actions"><button id="d1Strike" class="d1-action" type="button">Strikethrough</button><button id="d1Sub" class="d1-action" type="button">Subscript</button><button id="d1Super" class="d1-action" type="button">Superscript</button></div>';document.querySelector('.app-shell')?.append(formatPopover);
 $('d1FormatClose').onclick=()=>formatPopover.hidden=true;for(const id of ['d1FontColor','d1HighlightColor','d1Strike','d1Sub','d1Super'])$(id).addEventListener('pointerdown',()=>editor.rememberSelection());$('d1FontColor').onchange=e=>applyCommand('foreColor',e.target.value);$('d1HighlightColor').onchange=e=>applyHighlight(e.target.value);$('d1Strike').onclick=()=>applyCommand('strikeThrough');$('d1Sub').onclick=()=>applyCommand('subscript');$('d1Super').onclick=()=>applyCommand('superscript')}
 function currentSpec(){return NS.PageSpec.normalize(state.currentPageSpec||surface.currentPages?.()[0]?._pageSpec||NS.PageSpec.defaultSpec())}
 function sizeFor(name){if(name==='a4')return{widthPx:21*PX_PER_CM,heightPx:29.7*PX_PER_CM};if(name==='legal')return{widthPx:8.5*96,heightPx:14*96};return{widthPx:8.5*96,heightPx:11*96}}
 function detectSize(spec){const portrait=[Math.min(spec.widthPx,spec.heightPx),Math.max(spec.widthPx,spec.heightPx)],candidates=[['letter',816,1056],['a4',21*PX_PER_CM,29.7*PX_PER_CM],['legal',816,1344]];let best='letter',d=Infinity;for(const [name,w,h] of candidates){const x=Math.abs(portrait[0]-Math.min(w,h))+Math.abs(portrait[1]-Math.max(w,h));if(x<d){d=x;best=name}}return best}
 function setLayoutFields(){const s=currentSpec();$('d1PageSize').value=detectSize(s);$('d1Orientation').value=s.widthPx>s.heightPx?'landscape':'portrait';$('d1MarginTop').value=(s.marginTopPx/PX_PER_CM).toFixed(2);$('d1MarginRight').value=(s.marginRightPx/PX_PER_CM).toFixed(2);$('d1MarginBottom').value=(s.marginBottomPx/PX_PER_CM).toFixed(2);$('d1MarginLeft').value=(s.marginLeftPx/PX_PER_CM).toFixed(2);$('d1HeaderText').value=s.headerText||'';$('d1FooterText').value=s.footerText||'';$('d1PageNumber').checked=!!s.pageNumber}
 function specFromFields(){const base=currentSpec(),sz=sizeFor($('d1PageSize').value),land=$('d1Orientation').value==='landscape',widthPx=land?Math.max(sz.widthPx,sz.heightPx):Math.min(sz.widthPx,sz.heightPx),heightPx=land?Math.min(sz.widthPx,sz.heightPx):Math.max(sz.widthPx,sz.heightPx),marginTopPx=clamp($('d1MarginTop').value,0.25,6,2.54)*PX_PER_CM,marginRightPx=clamp($('d1MarginRight').value,0.25,6,2.54)*PX_PER_CM,marginBottomPx=clamp($('d1MarginBottom').value,0.25,6,2.54)*PX_PER_CM,marginLeftPx=clamp($('d1MarginLeft').value,0.25,6,2.54)*PX_PER_CM;return NS.PageSpec.normalize({...base,widthPx,heightPx,marginTopPx,marginRightPx,marginBottomPx,marginLeftPx,contentWidthPx:Math.max(96,widthPx-marginLeftPx-marginRightPx),contentHeightPx:Math.max(96,heightPx-marginTopPx-marginBottomPx),orientation:land?'landscape':'portrait',headerText:String($('d1HeaderText').value||'').slice(0,500),footerText:String($('d1FooterText').value||'').slice(0,500),pageNumber:!!$('d1PageNumber').checked})}
 function blockNode(item){if(item.dataset?.blockIndex!==undefined||item.dataset?.sourceIndex!==undefined)return item.firstElementChild||item;return item}
 function collectBlocks(overrideSpec=null){const blocks=[];let index=0;for(const page of surface.currentPages()){const spec=overrideSpec||page._pageSpec||state.currentPageSpec||NS.PageSpec.defaultSpec(),content=page.querySelector('.page-content');for(const item of Array.from(content?.children||[])){const node=blockNode(item),clone=node.cloneNode(true);clone.classList?.remove('d1-page-break-marker');const raw=item.dataset?.sourceIndex,subRaw=item.dataset?.sourceSubIndex;blocks.push({index:index++,html:clone.outerHTML||clone.innerHTML,text:String(clone.innerText||clone.textContent||''),sourceIndex:raw!==undefined&&raw!==''?Number(raw):null,sourceSubIndex:subRaw!==undefined&&subRaw!==''?Number(subRaw):0,hardPageBreakBefore:node.dataset?.pageBreakBefore==='1',softPageBreakBefore:false,sectionStart:false,pageSpec:spec})}}return blocks}
 async function reflow(overrideSpec=null){if(reflowing||!active())return;reflowing=true;try{editor.rememberSelection();const models=await NS.PaginationEngine.paginate(collectBlocks(overrideSpec),overrideSpec||currentSpec());if(!models.length)throw new Error('Document reflow produced no pages.');state.pageModels=models;surface.render(models);syncPageNumbers();editor.markDirty()}finally{reflowing=false}}
 function syncPageNumbers(){for(const page of surface.currentPages()){const spec=NS.PageSpec.normalize(page._pageSpec||state.currentPageSpec),existing=page.querySelector('.d1-page-number');if(!spec.pageNumber){existing?.remove();continue}let footer=page.querySelector('.page-footer');if(!footer){footer=document.createElement('div');footer.className='page-footer';footer.contentEditable='false';page.appendChild(footer)}let span=footer.querySelector('.d1-page-number');if(!span){span=document.createElement('span');span.className='d1-page-number';footer.appendChild(span)}span.textContent=String(page.dataset.page||'')}}
 async function applyLayout(){if(!active())return;const previous=currentSpec(),next=specFromFields(),hfChanged=previous.headerText!==next.headerText||previous.footerText!==next.footerText||!!previous.pageNumber!==!!next.pageNumber;pagesHost.dataset.d1LayoutDirty='1';if(hfChanged)pagesHost.dataset.d1HeaderFooterDirty='1';await reflow(next);layoutPanel.hidden=true;chrome.status('Page layout applied')}
 async function insertPageBreak(){if(!active())return;const b=editor.currentSelectionBlock?.()||editor.selectionBlock?.();if(!b){chrome.status('Place the cursor in a paragraph first');return}b.dataset.pageBreakBefore='1';b.classList.add('d1-page-break-marker');pagesHost.dataset.d1LayoutDirty='1';await reflow();layoutPanel.hidden=true;chrome.status('Page break inserted')}
 function exportPdf(){if(!active())return;closeAll();chrome.status('Print dialog opened · choose Save as PDF');setTimeout(()=>global.print(),20)}
 function buildLayoutPanel(){if($('d1LayoutPanel')){layoutPanel=$('d1LayoutPanel');return}layoutPanel=document.createElement('section');layoutPanel.id='d1LayoutPanel';layoutPanel.className='d1-layout-panel';layoutPanel.hidden=true;layoutPanel.setAttribute('aria-label','Page layout');layoutPanel.innerHTML='<div class="d1-head"><strong>Page layout</strong><button id="d1LayoutClose" class="d1-close" type="button" aria-label="Close">×</button></div><div class="d1-section"><div class="d1-grid"><label class="d1-field">Paper size<select id="d1PageSize"><option value="letter">Letter</option><option value="a4">A4</option><option value="legal">Legal</option></select></label><label class="d1-field">Orientation<select id="d1Orientation"><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label><label class="d1-field">Top margin (cm)<input id="d1MarginTop" type="number" min="0.25" max="6" step="0.1"></label><label class="d1-field">Right margin (cm)<input id="d1MarginRight" type="number" min="0.25" max="6" step="0.1"></label><label class="d1-field">Bottom margin (cm)<input id="d1MarginBottom" type="number" min="0.25" max="6" step="0.1"></label><label class="d1-field">Left margin (cm)<input id="d1MarginLeft" type="number" min="0.25" max="6" step="0.1"></label></div></div><div class="d1-section"><div class="d1-grid"><label class="d1-field full">Header<input id="d1HeaderText" type="text" maxlength="500" placeholder="Optional header text"></label><label class="d1-field full">Footer<input id="d1FooterText" type="text" maxlength="500" placeholder="Optional footer text"></label><label class="d1-field full"><span><input id="d1PageNumber" type="checkbox"> Show page number in footer</span></label></div></div><div class="d1-section"><div class="d1-actions"><button id="d1ApplyLayout" class="d1-action primary" type="button">Apply layout</button><button id="d1PageBreak" class="d1-action" type="button">Insert page break</button><button id="d1ExportPdf" class="d1-action" type="button">Print / Export PDF</button></div><p class="d1-note">Print / Export PDF opens the browser print sheet; choose Save as PDF when the host provides it.</p></div>';document.querySelector('.app-shell')?.append(layoutPanel);$('d1LayoutClose').onclick=()=>layoutPanel.hidden=true;$('d1ApplyLayout').onclick=()=>applyLayout().catch(e=>{console.error(e);chrome.status('Page layout failed')});$('d1PageBreak').onclick=()=>insertPageBreak().catch(e=>{console.error(e);chrome.status('Page break failed')});$('d1ExportPdf').onclick=exportPdf}
 function installReplace(){const host=$('searchPanel');if(!host||$('d1ReplaceInput'))return;const box=document.createElement('div');box.className='d1-replace';box.innerHTML='<input id="d1ReplaceInput" type="text" placeholder="Replace with"><button id="d1ReplaceNext" type="button">Replace</button><button id="d1ReplaceAll" type="button">All</button>';host.querySelector('.search-box')?.insertAdjacentElement('afterend',box);function query(){return String($('searchInput')?.value||'').trim()}$('d1ReplaceNext').onclick=()=>{if(!active())return;const q=query();if(!q)return;navigation.search(q);const mark=pagesHost.querySelector('mark[data-search].active-hit')||pagesHost.querySelector('mark[data-search]');if(!mark){chrome.status('No match to replace');return}mark.replaceWith(document.createTextNode($('d1ReplaceInput').value||''));mark.parentElement?.normalize?.();editor.markDirty();navigation.search(q);chrome.status('One match replaced')};$('d1ReplaceAll').onclick=()=>{if(!active())return;const q=query();if(!q)return;navigation.search(q);const marks=[...pagesHost.querySelectorAll('mark[data-search]')];if(!marks.length){chrome.status('No matches to replace');return}const value=$('d1ReplaceInput').value||'';for(const mark of marks)mark.replaceWith(document.createTextNode(value));pagesHost.querySelectorAll('.page-content').forEach(x=>x.normalize());editor.markDirty();navigation.search(q);chrome.status(`${marks.length} match${marks.length===1?'':'es'} replaced`)};global.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='h'){e.preventDefault();$('contextBtn')?.click();document.querySelector('[data-panel="searchPanel"]')?.click();setTimeout(()=>$('d1ReplaceInput')?.focus(),40)}})}
 function install(){insertToolbarControls();buildFormatPopover();buildLayoutPanel();installReplace();formatBtn.onclick=()=>{if(!active())return;layoutPanel.hidden=true;formatPopover.hidden=!formatPopover.hidden;if(!formatPopover.hidden)position(formatBtn,formatPopover)};layoutBtn.onclick=()=>{if(!active())return;formatPopover.hidden=true;layoutPanel.hidden=!layoutPanel.hidden;if(!layoutPanel.hidden){setLayoutFields();position(layoutBtn,layoutPanel)}};global.addEventListener('resize',()=>{if(formatPopover&&!formatPopover.hidden)position(formatBtn,formatPopover);if(layoutPanel&&!layoutPanel.hidden)position(layoutBtn,layoutPanel)},{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});numberObserver=new MutationObserver(()=>syncPageNumbers());numberObserver.observe(pagesHost,{childList:true,subtree:false});syncPageNumbers()}
 return Object.freeze({install,closeAll,reflow,syncPageNumbers,inspect:()=>Object.freeze({active:active(),reflowing,pageCount:surface.currentPages().length})})}
NS.D1Tools=Object.freeze({create});
})(globalThis);
