(function(global){'use strict';
const NS=global.InkDOS2Documents=global.InkDOS2Documents||{},$=id=>document.getElementById(id);
function create({state,session,pagesHost,surface,editor,navigation,chrome,d1}={}){let button=null,panel=null,counter=0;
 function active(){return !!session.active}
 function position(){if(!button||!panel||panel.hidden)return;const a=button.getBoundingClientRect(),w=panel.offsetWidth||380,h=panel.offsetHeight||600;panel.style.left=Math.max(8,Math.min(innerWidth-w-8,a.left))+'px';panel.style.top=Math.max(8,Math.min(innerHeight-h-8,a.bottom+6))+'px'}
 function close(){if(panel)panel.hidden=true}
 function blockFor(node){const el=node?.nodeType===3?node.parentElement:node;return el?.closest?.('.page-content p,.page-content h1,.page-content h2,.page-content h3,.page-content h4,.page-content li,.page-content td')||null}
 function selectedRange(){editor.restoreSelection?.();const sel=getSelection();if(!sel||!sel.rangeCount)return null;const r=sel.getRangeAt(0);return pagesHost.contains(r.commonAncestorContainer)?r:null}
 function mark(block){if(block){block.dataset.d2Rich='1';editor.rememberSelection?.();editor.markDirty();}}
 function uid(prefix){counter++;return prefix+'-'+Date.now().toString(36)+'-'+counter.toString(36)}
 function setSpellcheck(on){pagesHost.querySelectorAll('.page-content').forEach(x=>x.spellcheck=!!on);pagesHost.dataset.d2Spellcheck=on?'1':'0';chrome.status(on?'Browser spellcheck enabled':'Browser spellcheck disabled')}
 function addComment(){if(!active())return;const text=String($('d2CommentText')?.value||'').trim();if(!text){chrome.status('Enter a comment first');return}const r=selectedRange();if(!r||r.collapsed){chrome.status('Select text for the comment');return}const start=blockFor(r.startContainer),end=blockFor(r.endContainer);if(!start||start!==end){chrome.status('Comments currently require a selection inside one paragraph');return}const span=document.createElement('span');span.className='d2-comment';span.dataset.d2CommentId=uid('comment');span.dataset.d2CommentText=text;try{span.append(r.extractContents());r.insertNode(span);const sel=getSelection();sel.removeAllRanges();const nr=document.createRange();nr.selectNodeContents(span);sel.addRange(nr);editor.rememberSelection?.();$('d2CommentText').value='';mark(start);renderComments();chrome.status('Comment added')}catch(error){console.error(error);chrome.status('Comment could not be added to this selection')}}
 function removeComment(id){const span=pagesHost.querySelector('[data-d2-comment-id="'+CSS.escape(id)+'"]');if(!span)return;const block=blockFor(span),parent=span.parentNode;while(span.firstChild)parent.insertBefore(span.firstChild,span);span.remove();parent.normalize?.();mark(block);renderComments();chrome.status('Comment removed')}
 function renderComments(){const host=$('d2CommentsList');if(!host)return;host.replaceChildren();const comments=[...pagesHost.querySelectorAll('[data-d2-comment-id]')];if(!comments.length){host.innerHTML='<div class="d2-note">No comments in this document.</div>';return}for(const span of comments){const card=document.createElement('div');card.className='d2-comment-card';const strong=document.createElement('strong');strong.textContent=(span.textContent||'').trim().slice(0,80)||'Commented text';const body=document.createElement('div');body.textContent=span.dataset.d2CommentText||'';const del=document.createElement('button');del.type='button';del.textContent='Remove';del.onclick=()=>removeComment(span.dataset.d2CommentId);card.append(strong,body,del);host.append(card)}}
 function renumberFootnotes(){[...pagesHost.querySelectorAll('[data-d2-footnote-id]')].forEach((x,i)=>{x.textContent=String(i+1);x.dataset.d2FootnoteNumber=String(i+1)})}
 function addFootnote(){if(!active())return;const text=String($('d2FootnoteText')?.value||'').trim();if(!text){chrome.status('Enter footnote text first');return}const r=selectedRange();if(!r){chrome.status('Place the cursor where the footnote belongs');return}const block=blockFor(r.startContainer);if(!block){chrome.status('Place the cursor inside document text');return}r.deleteContents();const sup=document.createElement('sup');sup.className='d2-footnote-ref';sup.contentEditable='false';sup.dataset.d2FootnoteId=uid('footnote');sup.dataset.d2FootnoteText=text;sup.textContent='1';r.insertNode(sup);r.setStartAfter(sup);r.collapse(true);const sel=getSelection();sel.removeAllRanges();sel.addRange(r);editor.rememberSelection?.();$('d2FootnoteText').value='';mark(block);renumberFootnotes();chrome.status('Footnote inserted')}
 function cleanHeadingText(h){const c=h.cloneNode(true);c.querySelectorAll('.list-label,[data-d2-footnote-id],mark[data-search]').forEach(x=>x.remove());return String(c.innerText||c.textContent||'').trim()}
 async function updateToc(){if(!active())return;pagesHost.querySelectorAll('[data-d2-toc-role]').forEach(x=>x.remove());const headings=[...pagesHost.querySelectorAll('.page-content h1,.page-content h2,.page-content h3,.page-content h4')].filter(h=>!h.dataset.d2TocRole&&cleanHeadingText(h));if(!headings.length){chrome.status('Add headings before creating a table of contents');return}const first=pagesHost.querySelector('.page-content');if(!first)return;const frag=document.createDocumentFragment(),title=document.createElement('p');title.className='d2-toc-title';title.dataset.d2TocRole='title';title.dataset.d2Style='toc-title';title.textContent='Table of Contents';frag.append(title);for(const h of headings){const level=h.tagName==='H1'?0:h.tagName==='H2'?1:h.tagName==='H3'?2:3,p=document.createElement('p');p.className='d2-toc-entry';p.dataset.d2TocRole='entry';p.dataset.d2TocLevel=String(level);p.dataset.d2Style='toc'+Math.min(3,level+1);p.style.marginLeft=(level*18)+'px';const t=document.createElement('span');t.className='d2-toc-text';t.textContent=cleanHeadingText(h);const n=document.createElement('span');n.className='d2-toc-page';n.textContent=h.closest('.doc-page')?.dataset.page||'';p.append(t,n);frag.append(p)}first.prepend(frag);editor.markDirty();if(d1?.reflow)await d1.reflow();chrome.status('Table of contents updated')}
 function clearStyle(block){block.classList.remove('d2-style-subtitle','d2-style-quote');delete block.dataset.d2Style;block.style.removeProperty('font-size');block.style.removeProperty('font-style')}
 function applyStyle(){if(!active())return;const block=editor.currentSelectionBlock?.()||editor.selectionBlock?.();if(!block){chrome.status('Place the cursor in a paragraph');return}const value=$('d2Style')?.value||'normal';editor.rememberSelection?.();clearStyle(block);if(value==='heading3'){document.execCommand('formatBlock',false,'h4');const next=editor.currentSelectionBlock?.()||block;next.dataset.d2Style='Heading3';mark(next)}else if(value==='subtitle'){document.execCommand('formatBlock',false,'p');const next=editor.currentSelectionBlock?.()||block;next.classList.add('d2-style-subtitle');next.dataset.d2Style='Subtitle';mark(next)}else if(value==='quote'){document.execCommand('formatBlock',false,'p');const next=editor.currentSelectionBlock?.()||block;next.classList.add('d2-style-quote');next.dataset.d2Style='Quote';mark(next)}else{document.execCommand('formatBlock',false,'p');const next=editor.currentSelectionBlock?.()||block;delete next.dataset.d2Style;mark(next)}chrome.status('Paragraph style applied')}
 function currentCell(){return (editor.currentSelectionBlock?.()||editor.selectionBlock?.())?.closest?.('td,th')||null}
 function dirtyTable(table){if(!table)return;table.dataset.d2TableDirty='1';editor.markDirty();}
 function mergeRight(){const cell=currentCell();if(!cell||!cell.nextElementSibling){chrome.status('Place the cursor in a cell with a cell to its right');return}const right=cell.nextElementSibling;while(right.firstChild)cell.append(right.firstChild);cell.colSpan=(cell.colSpan||1)+(right.colSpan||1);right.remove();dirtyTable(cell.closest('table'));chrome.status('Cells merged')}
 function deleteRow(){const cell=currentCell(),row=cell?.parentElement,table=cell?.closest('table');if(!row||!table){chrome.status('Place the cursor inside a table');return}if(table.rows.length<=1){chrome.status('A table must keep at least one row');return}row.remove();dirtyTable(table);chrome.status('Row deleted')}
 function deleteColumn(){const cell=currentCell(),table=cell?.closest('table');if(!cell||!table){chrome.status('Place the cursor inside a table');return}const index=cell.cellIndex;if(Math.max(...[...table.rows].map(r=>r.cells.length))<=1){chrome.status('A table must keep at least one column');return}for(const row of [...table.rows]){const target=row.cells[Math.min(index,row.cells.length-1)];if(target)target.remove()}dirtyTable(table);chrome.status('Column deleted')}
 function insertControls(){const bar=$('formatbar'),spacer=bar?.querySelector('.toolbar-end-spacer');if(!bar||!spacer||$('d2P1Btn'))return;const sep=document.createElement('span');sep.className='separator';sep.dataset.d2='1';button=document.createElement('button');button.id='d2P1Btn';button.className='fmt-btn';button.type='button';button.title='Review and document structure';button.setAttribute('aria-label','Review and document structure');button.textContent='P1';bar.insertBefore(sep,spacer);bar.insertBefore(button,spacer)}
 function buildPanel(){if($('d2Panel')){panel=$('d2Panel');return}panel=document.createElement('section');panel.id='d2Panel';panel.className='d2-panel';panel.hidden=true;panel.setAttribute('aria-label','Review and document structure');panel.innerHTML='<div class="d2-head"><strong>Document P1</strong><button id="d2Close" class="d2-close" type="button" aria-label="Close">×</button></div><div class="d2-section"><div class="d2-section-title">Proofing</div><label class="d2-native-spellcheck"><input id="d2Spellcheck" type="checkbox" checked> Browser spellcheck</label><p class="d2-note">Spelling suggestions are provided locally by the host browser when available.</p></div><div class="d2-section"><div class="d2-section-title">Comments</div><div class="d2-row"><label class="d2-field">Comment<input id="d2CommentText" type="text" maxlength="1000" placeholder="Comment on selected text"></label><button id="d2AddComment" class="primary" type="button">Add</button></div><div id="d2CommentsList" class="d2-comments-list"></div></div><div class="d2-section"><div class="d2-section-title">Footnotes</div><div class="d2-row"><label class="d2-field">Footnote text<input id="d2FootnoteText" type="text" maxlength="2000" placeholder="Footnote text"></label><button id="d2AddFootnote" type="button">Insert</button></div></div><div class="d2-section"><div class="d2-section-title">Table of contents</div><div class="d2-row"><button id="d2UpdateToc" type="button">Insert / Update TOC</button></div><p class="d2-note">The TOC is regenerated from document headings and current page positions.</p></div><div class="d2-section"><div class="d2-section-title">Paragraph styles</div><div class="d2-row"><label class="d2-field">Style<select id="d2Style"><option value="normal">Normal</option><option value="heading3">Heading 3</option><option value="subtitle">Subtitle</option><option value="quote">Quote</option></select></label><button id="d2ApplyStyle" type="button">Apply</button></div></div><div class="d2-section"><div class="d2-section-title">Table tools</div><div class="d2-row"><button id="d2MergeRight" type="button">Merge right</button><button id="d2DeleteRow" type="button">Delete row</button><button id="d2DeleteColumn" type="button">Delete column</button></div></div>';document.querySelector('.app-shell')?.append(panel);$('d2Close').onclick=close;$('d2Spellcheck').onchange=e=>setSpellcheck(e.target.checked);$('d2AddComment').onpointerdown=()=>editor.rememberSelection?.();$('d2AddComment').onclick=addComment;$('d2AddFootnote').onpointerdown=()=>editor.rememberSelection?.();$('d2AddFootnote').onclick=addFootnote;$('d2UpdateToc').onclick=()=>updateToc().catch(e=>{console.error(e);chrome.status('TOC update failed')});$('d2ApplyStyle').onpointerdown=()=>editor.rememberSelection?.();$('d2ApplyStyle').onclick=applyStyle;$('d2MergeRight').onclick=mergeRight;$('d2DeleteRow').onclick=deleteRow;$('d2DeleteColumn').onclick=deleteColumn;renderComments()}
 function install(){insertControls();buildPanel();button.onclick=()=>{if(!active())return;d1?.closeAll?.();panel.hidden=!panel.hidden;if(!panel.hidden){renderComments();renumberFootnotes();position()}};global.addEventListener('resize',()=>{if(panel&&!panel.hidden)position()},{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});new MutationObserver(()=>{renumberFootnotes();if(panel&&!panel.hidden)renderComments()}).observe(pagesHost,{childList:true,subtree:true})}
 return Object.freeze({install,close,renderComments,renumberFootnotes,updateToc,inspect:()=>Object.freeze({comments:pagesHost.querySelectorAll('[data-d2-comment-id]').length,footnotes:pagesHost.querySelectorAll('[data-d2-footnote-id]').length,tocEntries:pagesHost.querySelectorAll('[data-d2-toc-role="entry"]').length})})}
NS.D2Tools=Object.freeze({create});
})(globalThis);
