(function(global){'use strict';
const NS=global.InkDOS2Documents=global.InkDOS2Documents||{};
function create({pagesHost}={}){const $=id=>document.getElementById(id);let hits=[],activeHit=-1;
 const escapeHtml=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function buildPageList(){const list=$('pageList');list.innerHTML='';Array.from(pagesHost.querySelectorAll('.doc-page')).forEach((page,i)=>{const b=document.createElement('button');b.className='page-thumb';b.innerHTML='<div class="thumb-sheet">'+escapeHtml((page.querySelector('.page-content')?.innerText||'').slice(0,600))+'</div><span class="thumb-label">Page '+(i+1)+'</span>';b.onclick=()=>page.closest('.page-shell').scrollIntoView({block:'start'});list.appendChild(b)})}
 function buildOutline(items){const list=$('outlineList');list.innerHTML='';if(!items.length){list.innerHTML='<p class="muted">No headings were found.</p>';return}for(const it of items){const b=document.createElement('button');b.className='outline-item level-'+Math.min(3,it.level);b.textContent=it.text;b.onclick=()=>pagesHost.querySelector('[data-block-index="'+it.blockIndex+'"]')?.scrollIntoView({block:'center'});list.appendChild(b)}}
 function clearSearch(){pagesHost.querySelectorAll('mark[data-search]').forEach(m=>m.replaceWith(document.createTextNode(m.textContent)));pagesHost.querySelectorAll('.page-content').forEach(x=>x.normalize());hits=[];activeHit=-1}
 function search(q){clearSearch();$('searchResults').innerHTML='';q=String(q||'').trim();if(!q){$('searchCount').textContent='0 results';return}const needle=q.toLocaleLowerCase(),walker=document.createTreeWalker(pagesHost,NodeFilter.SHOW_TEXT,{acceptNode(n){return n.parentElement&&!['SCRIPT','STYLE','MARK'].includes(n.parentElement.tagName)&&n.nodeValue.toLocaleLowerCase().includes(needle)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}}),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const text=node.nodeValue,low=text.toLocaleLowerCase();let pos=0,at=low.indexOf(needle),frag=document.createDocumentFragment();while(at>=0){frag.append(text.slice(pos,at));const m=document.createElement('mark');m.dataset.search='1';m.textContent=text.slice(at,at+q.length);frag.append(m);hits.push(m);pos=at+q.length;at=low.indexOf(needle,pos)}frag.append(text.slice(pos));node.replaceWith(frag)}$('searchCount').textContent=hits.length+' result'+(hits.length===1?'':'s');hits.forEach((m,i)=>{const b=document.createElement('button');b.className='search-result';b.textContent='Page '+(m.closest('.doc-page')?.dataset.page||'?')+' · '+(m.parentElement.innerText||m.textContent).trim().slice(0,80);b.onclick=()=>focusHit(i);$('searchResults').appendChild(b)});if(hits.length)focusHit(0)}
 function focusHit(i){if(!hits.length)return;activeHit=(i+hits.length)%hits.length;hits.forEach((m,j)=>m.classList.toggle('active-hit',j===activeHit));hits[activeHit].scrollIntoView({block:'center'});$('searchCount').textContent=(activeHit+1)+' of '+hits.length}
 function installTabs(){document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));document.querySelectorAll('.side-panel').forEach(p=>p.classList.toggle('active',p.id===t.dataset.panel));if(t.dataset.panel==='searchPanel')setTimeout(()=>$('searchInput').focus(),30)});let st=0;$('searchInput').oninput=()=>{clearTimeout(st);st=setTimeout(()=>search($('searchInput').value),160)};$('nextHit').onclick=()=>focusHit(activeHit+1);$('prevHit').onclick=()=>focusHit(activeHit-1)}
 return Object.freeze({buildPageList,buildOutline,clearSearch,search,focusHit,installTabs});
}
NS.NavigationPanel=Object.freeze({create});
})(globalThis);
