(function(global){'use strict';
const NS=global.InkDOS2Documents=global.InkDOS2Documents||{};
function create(){let panel=null,activeResolve=null,previousFocus=null;
 function ensure(){if(panel)return panel;panel=document.createElement('div');panel.id='sessionReplacePanel';panel.className='error-overlay';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','sessionReplaceTitle');panel.innerHTML='<div class="error-card session-replace-card"><h2 id="sessionReplaceTitle">Unsaved changes</h2><p id="sessionReplaceMessage"></p><div class="error-actions"><button id="sessionReplaceCancel" type="button">Cancel</button><button id="sessionReplaceDiscard" type="button">Discard</button><button id="sessionReplaceSave" type="button" class="retry-open">Save</button></div></div>';document.body.appendChild(panel);panel.querySelector('#sessionReplaceCancel').addEventListener('click',()=>finish('cancel'));panel.querySelector('#sessionReplaceDiscard').addEventListener('click',()=>finish('discard'));panel.querySelector('#sessionReplaceSave').addEventListener('click',()=>finish('save'));panel.addEventListener('pointerdown',e=>{if(e.target===panel)finish('cancel')});panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();finish('cancel')}});return panel}
 function finish(value){if(!activeResolve)return;const resolve=activeResolve;activeResolve=null;panel.hidden=true;const focus=previousFocus;previousFocus=null;resolve(value);requestAnimationFrame(()=>focus?.focus?.({preventScroll:true}))}
 function decide({title='Unsaved changes',message='This document has unsaved changes.'}={}){ensure();if(activeResolve)finish('cancel');previousFocus=document.activeElement;panel.querySelector('#sessionReplaceTitle').textContent=title;panel.querySelector('#sessionReplaceMessage').textContent=message;panel.hidden=false;return new Promise(resolve=>{activeResolve=resolve;requestAnimationFrame(()=>panel.querySelector('#sessionReplaceCancel').focus({preventScroll:true}))})}
 async function confirm(options={}){return(await decide(options))==='discard'}
 let askPanel=null,askResolve=null,askFocus=null;
 function ensureAsk(){if(askPanel)return askPanel;askPanel=document.createElement('div');askPanel.id='inkdosAskPanel';askPanel.className='error-overlay';askPanel.hidden=true;askPanel.setAttribute('role','dialog');askPanel.setAttribute('aria-modal','true');askPanel.setAttribute('aria-labelledby','inkdosAskTitle');askPanel.innerHTML='<form class="error-card ask-card" novalidate><h2 id="inkdosAskTitle"></h2><p id="inkdosAskMessage"></p><div class="ask-fields"></div><div class="error-actions"><button id="inkdosAskCancel" type="button">Cancel</button><button id="inkdosAskConfirm" type="submit" class="retry-open">OK</button></div></form>';document.body.appendChild(askPanel);const form=askPanel.querySelector('form');form.addEventListener('submit',e=>{e.preventDefault();const values={};for(const input of form.querySelectorAll('.ask-fields input'))values[input.name]=input.value;finishAsk(values)});askPanel.querySelector('#inkdosAskCancel').addEventListener('click',()=>finishAsk(null));askPanel.addEventListener('pointerdown',e=>{if(e.target===askPanel)finishAsk(null)});askPanel.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();finishAsk(null)}});return askPanel}
 function finishAsk(value){if(!askResolve)return;const resolve=askResolve;askResolve=null;askPanel.hidden=true;const focus=askFocus;askFocus=null;resolve(value);requestAnimationFrame(()=>focus?.focus?.({preventScroll:true}))}
 function ask({title='',message='',fields=[],confirmLabel='OK'}={}){ensureAsk();if(askResolve)finishAsk(null);askFocus=document.activeElement;askPanel.querySelector('#inkdosAskTitle').textContent=title;const msg=askPanel.querySelector('#inkdosAskMessage');msg.textContent=message;msg.hidden=!message;askPanel.querySelector('#inkdosAskConfirm').textContent=confirmLabel;const host=askPanel.querySelector('.ask-fields');host.replaceChildren();fields.forEach((field,index)=>{const label=document.createElement('label');label.className='ask-field';const text=document.createElement('span');text.textContent=field.label||field.name;const input=document.createElement('input');input.name=field.name;input.id='inkdosAskField'+index;input.type=field.type||'text';input.value=field.value??'';input.autocomplete='off';if(field.inputMode)input.inputMode=field.inputMode;label.append(text,input);host.appendChild(label)});askPanel.hidden=false;return new Promise(resolve=>{askResolve=resolve;requestAnimationFrame(()=>{const first=host.querySelector('input');first?.focus({preventScroll:true});first?.select?.()})})}
 return Object.freeze({decide,confirm,ask,get isOpen(){return !!(panel&&!panel.hidden)}})}
NS.SessionDialog=Object.freeze({create});
})(globalThis);
