(function(global){'use strict';
const NS=global.InkDOS2Documents=global.InkDOS2Documents||{};
function create(){let panel=null,activeResolve=null,previousFocus=null;
 function ensure(){if(panel)return panel;panel=document.createElement('div');panel.id='sessionReplacePanel';panel.className='error-overlay';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','sessionReplaceTitle');panel.innerHTML='<div class="error-card session-replace-card"><h2 id="sessionReplaceTitle">Unsaved changes</h2><p id="sessionReplaceMessage"></p><div class="error-actions"><button id="sessionReplaceCancel" type="button">Cancel</button><button id="sessionReplaceDiscard" type="button">Discard</button><button id="sessionReplaceSave" type="button" class="retry-open">Save</button></div></div>';document.body.appendChild(panel);panel.querySelector('#sessionReplaceCancel').addEventListener('click',()=>finish('cancel'));panel.querySelector('#sessionReplaceDiscard').addEventListener('click',()=>finish('discard'));panel.querySelector('#sessionReplaceSave').addEventListener('click',()=>finish('save'));panel.addEventListener('pointerdown',e=>{if(e.target===panel)finish('cancel')});panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();finish('cancel')}});return panel}
 function finish(value){if(!activeResolve)return;const resolve=activeResolve;activeResolve=null;panel.hidden=true;const focus=previousFocus;previousFocus=null;resolve(value);requestAnimationFrame(()=>focus?.focus?.({preventScroll:true}))}
 function decide({title='Unsaved changes',message='This document has unsaved changes.'}={}){ensure();if(activeResolve)finish('cancel');previousFocus=document.activeElement;panel.querySelector('#sessionReplaceTitle').textContent=title;panel.querySelector('#sessionReplaceMessage').textContent=message;panel.hidden=false;return new Promise(resolve=>{activeResolve=resolve;requestAnimationFrame(()=>panel.querySelector('#sessionReplaceCancel').focus({preventScroll:true}))})}
 async function confirm(options={}){return(await decide(options))==='discard'}
 return Object.freeze({decide,confirm,get isOpen(){return !!(panel&&!panel.hidden)}})}
NS.SessionDialog=Object.freeze({create});
})(globalThis);
