(function(global){'use strict';
const NS=global.InkDOS2Documents=global.InkDOS2Documents||{};
function create(){let panel=null,activeResolve=null,previousFocus=null;
 function ensure(){if(panel)return panel;panel=document.createElement('div');panel.id='sessionReplacePanel';panel.className='error-overlay';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','sessionReplaceTitle');panel.innerHTML='<div class="error-card session-replace-card"><h2 id="sessionReplaceTitle">Unsaved changes</h2><p id="sessionReplaceMessage"></p><div class="error-actions"><button id="sessionReplaceCancel" type="button">Cancel</button><button id="sessionReplaceConfirm" type="button" class="retry-open">Continue</button></div></div>';document.body.appendChild(panel);panel.querySelector('#sessionReplaceCancel').addEventListener('click',()=>finish(false));panel.querySelector('#sessionReplaceConfirm').addEventListener('click',()=>finish(true));panel.addEventListener('pointerdown',e=>{if(e.target===panel)finish(false)});panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();finish(false)}});return panel}
 function finish(value){if(!activeResolve)return;const resolve=activeResolve;activeResolve=null;panel.hidden=true;const focus=previousFocus;previousFocus=null;resolve(!!value);requestAnimationFrame(()=>focus?.focus?.({preventScroll:true}))}
 function confirm({title='Unsaved changes',message='This document has unsaved changes.',confirmLabel='Continue'}={}){ensure();if(activeResolve)finish(false);previousFocus=document.activeElement;panel.querySelector('#sessionReplaceTitle').textContent=title;panel.querySelector('#sessionReplaceMessage').textContent=message;panel.querySelector('#sessionReplaceConfirm').textContent=confirmLabel;panel.hidden=false;return new Promise(resolve=>{activeResolve=resolve;requestAnimationFrame(()=>panel.querySelector('#sessionReplaceCancel').focus({preventScroll:true}))})}
 return Object.freeze({confirm,get isOpen(){return !!(panel&&!panel.hidden)}})}
NS.SessionDialog=Object.freeze({create});
})(globalThis);
