(function(global){'use strict';
const NS=global.InkDOS2Documents=global.InkDOS2Documents||{};
function create({state,session,viewport,pagesHost,welcome,zoom,navigation}={}){const $=id=>document.getElementById(id);
 function applyPageSpec(page,spec){spec=NS.PageSpec.normalize(spec);page._pageSpec=spec;page.style.width=spec.widthPx+'px';page.style.height=spec.heightPx+'px';page.style.padding=spec.marginTopPx+'px '+spec.marginRightPx+'px '+spec.marginBottomPx+'px '+spec.marginLeftPx+'px';page.style.fontFamily=JSON.stringify(spec.fontFamily||'Calibri')+',Arial,sans-serif';page.style.fontSize=spec.fontSizePt+'pt';page.style.lineHeight=String(spec.lineHeight||1.15);page.style.setProperty('--doc-margin-left',spec.marginLeftPx+'px');page.style.setProperty('--doc-margin-right',spec.marginRightPx+'px')}
 function applyContentSpec(content,spec){spec=NS.PageSpec.normalize(spec);content.style.width=spec.contentWidthPx+'px';content.style.height=spec.contentHeightPx+'px';content.style.minHeight=spec.contentHeightPx+'px'}
 function currentPages(){return Array.from(pagesHost.querySelectorAll('.doc-page'))}
 function countWords(text){const m=String(text||'').trim().match(/[\p{L}\p{N}]+(?:[’'\-][\p{L}\p{N}]+)*/gu);return m?m.length:0}
 function selectedText(){const sel=getSelection();if(!sel||!sel.rangeCount)return'';const r=sel.getRangeAt(0);return pagesHost.contains(r.commonAncestorContainer)?String(sel):''}
 function updateStats(){const text=Array.from(pagesHost.querySelectorAll('.page-content')).map(x=>x.innerText).join('\n');const words=countWords(text),chars=text.length,sw=countWords(selectedText());$('pageStatus').textContent=state.pageModels.length?'Page '+state.currentPage+' of '+state.pageModels.length+' · '+words+' words · '+chars+' characters'+(sw?' · '+sw+' selected':''):'—'}
 function bindPageObserver(){state.resetPageObserver();if(typeof IntersectionObserver!=='function')return;state.pageObserver=new IntersectionObserver(entries=>{let best=null;for(const e of entries)if(e.isIntersecting&&(!best||e.intersectionRatio>best.intersectionRatio))best=e;if(best){state.currentPage=Number(best.target.dataset.page)||1;state.currentPageSpec=best.target._pageSpec||state.currentPageSpec;zoom.setCurrentSpec(state.currentPageSpec);updateStats();document.querySelectorAll('.page-thumb').forEach((b,i)=>b.classList.toggle('active',i===state.currentPage-1))}},{root:viewport,threshold:[.15,.35,.6]});currentPages().forEach(p=>state.pageObserver.observe(p))}
 function render(models){pagesHost.replaceChildren();models.forEach((entry,pi)=>{const spec=NS.PageSpec.normalize(entry.spec),shell=document.createElement('section');shell.className='page-shell';shell.dataset.page=String(pi+1);const page=document.createElement('article');page.className='page doc-page';page.dataset.page=String(pi+1);page.dataset.nodeId='doc-'+session.documentId+'-page-'+(pi+1);applyPageSpec(page,spec);NS.DrawingLayout?.appendPageArtwork(page,spec);if(spec.headerText){const h=document.createElement('div');h.className='page-header';h.contentEditable='false';h.textContent=spec.headerText;page.appendChild(h)}const pc=document.createElement('div');pc.className='page-content';applyContentSpec(pc,spec);entry.items.forEach(b=>{const wrap=document.createElement('div');wrap.dataset.blockIndex=String(b.index);if(Number.isFinite(b.sourceIndex))wrap.dataset.sourceIndex=String(b.sourceIndex);if(Number.isFinite(b.sourceSubIndex))wrap.dataset.sourceSubIndex=String(b.sourceSubIndex);wrap.innerHTML=b.html;pc.appendChild(wrap)});pc.contentEditable='true';pc.spellcheck=true;page.appendChild(pc);if(spec.footerText){const f=document.createElement('div');f.className='page-footer';f.contentEditable='false';f.textContent=spec.footerText;page.appendChild(f)}shell.appendChild(page);pagesHost.appendChild(shell)});welcome.hidden=true;pagesHost.hidden=false;state.currentPage=1;state.currentPageSpec=models[0]?.spec||NS.PageSpec.defaultSpec();zoom.setCurrentSpec(state.currentPageSpec);bindPageObserver();navigation.buildPageList();navigation.buildOutline(state.outline);zoom.apply();updateStats()}
 return Object.freeze({applyPageSpec,applyContentSpec,currentPages,updateStats,bindPageObserver,render});
}
NS.PageSurface=Object.freeze({create});
})(globalThis);
