(function(root){'use strict';
const NS=root.InkDOS2Spreadsheets=root.InkDOS2Spreadsheets||{};
function isError(v){return typeof v==='string'&&v.startsWith('#')}
function encodeRef(r,c){return root.LocalXLSX.encodeRef(r,c)}
function splitArgs(text){const out=[];let q='',depth=0,quote=false;for(const ch of String(text)){if(ch==='"')quote=!quote;if(!quote){if(ch==='(')depth++;else if(ch===')')depth--;else if((ch===','||ch===';')&&depth===0){out.push(q);q='';continue}}q+=ch}out.push(q);return out}
function sheetByName(book,name,current){if(!name)return current;return book.sheets.find(s=>String(s.name).toLowerCase()===String(name).toLowerCase())||null}
function parseRef(token,book,current){let s=String(token||'').trim().replace(/\$/g,''),sheetName='';const bang=s.lastIndexOf('!');if(bang>=0){sheetName=s.slice(0,bang).replace(/^'(.*)'$/,'$1').replace(/''/g,"'");s=s.slice(bang+1)}if(!/^[A-Z]{1,3}\d+$/i.test(s))return null;const sheet=sheetByName(book,sheetName,current);if(!sheet)return{error:'#REF!'};return{sheet,ref:s.toUpperCase()}}
function parseRange(token,book,current){const parts=String(token||'').split(':');if(parts.length!==2)return null;const a=parseRef(parts[0],book,current),b=parseRef(parts[1].includes('!')?parts[1]:(parts[0].includes('!')?parts[0].split('!')[0]+'!'+parts[1]:parts[1]),book,current);if(!a||!b)return null;if(a.error||b.error)return{error:'#REF!'};const p1=root.LocalXLSX.decodeRef(a.ref),p2=root.LocalXLSX.decodeRef(b.ref);if(a.sheet!==b.sheet)return{error:'#REF!'};return{sheet:a.sheet,range:{r1:Math.min(p1.r,p2.r),c1:Math.min(p1.c,p2.c),r2:Math.max(p1.r,p2.r),c2:Math.max(p1.c,p2.c)}}}
function valueOf(book,sheet,ref,stack){const id=sheet.name+'!'+ref;if(stack.has(id))return'#CYCLE!';const cell=sheet.cells.get(ref);if(!cell)return 0;if(!cell.f)return cell.v??0;stack.add(id);const v=evaluate(book,sheet,cell.f,stack);stack.delete(id);return v}
function argValues(book,current,arg,stack){const text=String(arg||'').trim();const range=parseRange(text,book,current);if(range){if(range.error)return[range.error];const vals=[];for(let r=range.range.r1;r<=range.range.r2;r++)for(let c=range.range.c1;c<=range.range.c2;c++)vals.push(valueOf(book,range.sheet,encodeRef(r,c),stack));return vals}const ref=parseRef(text,book,current);if(ref)return[ref.error||valueOf(book,ref.sheet,ref.ref,stack)];if(/^".*"$/.test(text))return[text.slice(1,-1).replace(/""/g,'"')];if(/^(TRUE|FALSE)$/i.test(text))return[/^TRUE$/i.test(text)];const n=Number(text.replace(',','.'));return Number.isFinite(n)?[n]:[text]}
function evaluate(book,current,formula,stack=new Set()){let f=String(formula||'').trim().replace(/^=/,'');if(!f)return'';if(/#REF!/i.test(f))return'#REF!';const direct=parseRef(f,book,current);if(direct)return direct.error||valueOf(book,direct.sheet,direct.ref,stack);const call=/^([A-Z][A-Z0-9_.]*)\((.*)\)$/i.exec(f);if(call){const fn=call[1].toUpperCase(),args=splitArgs(call[2]);if(fn==='IF'){const cond=argValues(book,current,args[0],stack)[0];return cond?argValues(book,current,args[1],stack)[0]:argValues(book,current,args[2],stack)[0]}const vals=args.flatMap(a=>argValues(book,current,a,stack));const err=vals.find(isError);if(err)return err;const nums=vals.map(Number).filter(Number.isFinite);switch(fn){case'SUM':return nums.reduce((a,b)=>a+b,0);case'AVERAGE':return nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:'#DIV/0!';case'MIN':return nums.length?Math.min(...nums):0;case'MAX':return nums.length?Math.max(...nums):0;case'COUNT':return nums.length;case'PRODUCT':return nums.length?nums.reduce((a,b)=>a*b,1):0;default:return null}}
 let error='';const arithmetic=f.replace(/(?:(?:'[^']+'|[A-Za-z0-9_ .-]+)!)?\$?[A-Z]{1,3}\$?\d+/g,t=>{const ref=parseRef(t,book,current);if(ref?.error){error=ref.error;return'0'}const v=ref?valueOf(book,ref.sheet,ref.ref,stack):0;if(isError(v)){error=v;return'0'}return Number.isFinite(Number(v))?String(Number(v)):'0'});if(error)return error;if(/^[0-9+\-*/%^(). %]+$/.test(arithmetic)){try{return root.InkDOS2SpreadsheetFormulaMath.evaluateArithmetic(arithmetic)}catch(_){return'#VALUE!'}}const n=Number(f.replace(',','.'));return Number.isFinite(n)?n:null}
function recalculate(book){for(let pass=0;pass<4;pass++)for(const sheet of book.sheets)for(const[ref,cell]of sheet.cells){if(!cell?.f)continue;const v=evaluate(book,sheet,cell.f,new Set([sheet.name+'!'+ref]));if(v!==null&&v!==undefined){cell.calculatedRaw=v;cell.calculated=v;cell.display=String(v)}}}
NS.FormulaEvaluator=Object.freeze({evaluate,recalculate,isError,parseRef,parseRange});
})(globalThis);
