(function(root){'use strict';
const NS=root.InkDOS2Spreadsheets=root.InkDOS2Spreadsheets||{};
function isError(v){return typeof v==='string'&&v.startsWith('#')}
function encodeRef(r,c){return root.LocalXLSX.encodeRef(r,c)}
function splitArgs(text){const out=[];let q='',depth=0,quote=false;for(const ch of String(text)){if(ch==='"')quote=!quote;if(!quote){if(ch==='(')depth++;else if(ch===')')depth--;else if((ch===','||ch===';')&&depth===0){out.push(q);q='';continue}}q+=ch}out.push(q);return out}
function sheetByName(book,name,current){if(!name)return current;return book.sheets.find(s=>String(s.name).toLowerCase()===String(name).toLowerCase())||null}
function parseRef(token,book,current){let s=String(token||'').trim().replace(/\$/g,''),sheetName='';const bang=s.lastIndexOf('!');if(bang>=0){sheetName=s.slice(0,bang).replace(/^'(.*)'$/,'$1').replace(/''/g,"'");s=s.slice(bang+1)}if(!/^[A-Z]{1,3}\d+$/i.test(s))return null;const sheet=sheetByName(book,sheetName,current);if(!sheet)return{error:'#REF!'};return{sheet,ref:s.toUpperCase()}}
function parseRange(token,book,current){const parts=String(token||'').split(':');if(parts.length!==2)return null;const a=parseRef(parts[0],book,current),b=parseRef(parts[1].includes('!')?parts[1]:(parts[0].includes('!')?parts[0].split('!')[0]+'!'+parts[1]:parts[1]),book,current);if(!a||!b)return null;if(a.error||b.error)return{error:'#REF!'};const p1=root.LocalXLSX.decodeRef(a.ref),p2=root.LocalXLSX.decodeRef(b.ref);if(a.sheet!==b.sheet)return{error:'#REF!'};return{sheet:a.sheet,range:{r1:Math.min(p1.r,p2.r),c1:Math.min(p1.c,p2.c),r2:Math.max(p1.r,p2.r),c2:Math.max(p1.c,p2.c)}}}
// During recalculate(), ctx lets formula cells that did not need recalculation answer with their last result and
// memoizes each dirty formula once (only when no cycle was met, since cycle results depend on the entry point).
let ctx=null;
function valueOf(book,sheet,ref,stack){const id=sheet.name+'!'+ref;if(stack.has(id)){if(ctx)ctx.cycles++;return'#CYCLE!'}const cell=sheet.cells.get(ref);if(!cell)return 0;if(!cell.f)return cell.v??0;if(ctx){if(!ctx.dirty.has(id)&&ctx.last.has(id))return ctx.last.get(id);if(ctx.memo.has(id))return ctx.memo.get(id)}const cycles=ctx?ctx.cycles:0;stack.add(id);const v=evaluate(book,sheet,cell.f,stack);stack.delete(id);if(ctx&&ctx.cycles===cycles)ctx.memo.set(id,v);return v}
function argValues(book,current,arg,stack){const text=String(arg||'').trim();const range=parseRange(text,book,current);if(range){if(range.error)return[range.error];const vals=[];for(let r=range.range.r1;r<=range.range.r2;r++)for(let c=range.range.c1;c<=range.range.c2;c++)vals.push(valueOf(book,range.sheet,encodeRef(r,c),stack));return vals}const ref=parseRef(text,book,current);if(ref)return[ref.error||valueOf(book,ref.sheet,ref.ref,stack)];if(/^".*"$/.test(text))return[text.slice(1,-1).replace(/""/g,'"')];if(/^(TRUE|FALSE)$/i.test(text))return[/^TRUE$/i.test(text)];const n=Number(text.replace(',','.'));return Number.isFinite(n)?[n]:[text]}
function finiteResult(value){return Number.isFinite(value)?value:'#NUM!'}
function aggregateArgValues(book,current,arg,stack){const text=String(arg||'').trim(),range=parseRange(text,book,current);if(range){if(range.error)return[range.error];const vals=[];for(let r=range.range.r1;r<=range.range.r2;r++)for(let c=range.range.c1;c<=range.range.c2;c++){const cell=range.sheet.cells.get(encodeRef(r,c));if(!cell)continue;const v=valueOf(book,range.sheet,encodeRef(r,c),stack);if(isError(v)){vals.push(v);continue}if(typeof v==='number'&&Number.isFinite(v))vals.push(v)}return vals}const ref=parseRef(text,book,current);if(ref){if(ref.error)return[ref.error];const cell=ref.sheet.cells.get(ref.ref);if(!cell)return[];const v=valueOf(book,ref.sheet,ref.ref,stack);if(isError(v))return[v];return typeof v==='number'&&Number.isFinite(v)?[v]:[]}return argValues(book,current,arg,stack)}
function evaluate(book,current,formula,stack=new Set()){let f=String(formula||'').trim().replace(/^=/,'');if(!f)return'';if(/#REF!/i.test(f))return'#REF!';const direct=parseRef(f,book,current);if(direct)return direct.error||valueOf(book,direct.sheet,direct.ref,stack);const call=/^([A-Z][A-Z0-9_.]*)\((.*)\)$/i.exec(f);if(call){const fn=call[1].toUpperCase(),args=splitArgs(call[2]);if(fn==='IF'){const cond=argValues(book,current,args[0],stack)[0];if(isError(cond))return cond;if(typeof cond!=='boolean'&&(typeof cond!=='number'||!Number.isFinite(cond)))return'#VALUE!';return cond?argValues(book,current,args[1],stack)[0]:argValues(book,current,args[2],stack)[0]}const vals=args.flatMap(a=>aggregateArgValues(book,current,a,stack));const err=vals.find(isError);if(err)return err;const nums=vals.map(Number).filter(Number.isFinite);switch(fn){case'SUM':return finiteResult(nums.reduce((a,b)=>a+b,0));case'AVERAGE':return nums.length?finiteResult(nums.reduce((a,b)=>a+b,0)/nums.length):'#DIV/0!';case'MIN':return nums.length?Math.min(...nums):0;case'MAX':return nums.length?Math.max(...nums):0;case'COUNT':return nums.length;case'PRODUCT':return nums.length?finiteResult(nums.reduce((a,b)=>a*b,1)):0;default:return null}}
 let error='';const arithmetic=f.replace(/(?:(?:'[^']+'|[A-Za-z0-9_ .-]+)!)?\$?[A-Z]{1,3}\$?\d+/g,t=>{const ref=parseRef(t,book,current);if(ref?.error){error=ref.error;return'0'}const cell=ref?.sheet?.cells?.get(ref.ref),v=ref?valueOf(book,ref.sheet,ref.ref,stack):0;if(isError(v)){error=v;return'0'}if(cell&&!cell.f&&(cell.t==='s'||cell.t==='b'||cell.t==='e')){error='#VALUE!';return'0'}if(typeof v!=='number'||!Number.isFinite(v)){error='#VALUE!';return'0'}return String(v)});if(error)return error;if(/^[0-9+\-*/%^(). %]+$/.test(arithmetic)){try{return root.InkDOS2SpreadsheetFormulaMath.evaluateArithmetic(arithmetic)}catch(_){return'#VALUE!'}}const n=Number(f.replace(',','.'));return Number.isFinite(n)?n:null}
// Recalculation follows the dependency graph like Excel: cells whose value, type or formula changed since the last
// recalculation, and the formulas that depend on them (directly, through ranges, across sheets), are recalculated;
// every other formula keeps its result. Each formula is evaluated once. The first recalculation of a workbook, a
// change to its sheets or a very large change recalculates everything.
const FULL_RECALC_CHANGES=20000,states=new WeakMap();
const REF_TOKEN=/((?:'(?:[^']|'')+'|[A-Za-z0-9_ .-]+)!)?\$?([A-Za-z]{1,3})\$?(\d+)(?::(?:(?:'(?:[^']|'')+'|[A-Za-z0-9_.-]+)!)?\$?([A-Za-z]{1,3})\$?(\d+))?/g;
function prefixSheet(book,current,prefix){if(!prefix)return current;let name=prefix.slice(0,-1).trim();if(name.startsWith("'")&&name.endsWith("'"))name=name.slice(1,-1).replace(/''/g,"'");return sheetByName(book,name,current)}
function colIndex(letters){let c=0;for(const ch of letters.toUpperCase())c=c*26+ch.charCodeAt(0)-64;return c-1}
function formulaDeps(book,sheet,formula){const cells=[],ranges=[];REF_TOKEN.lastIndex=0;let m;const f=String(formula||'');while((m=REF_TOKEN.exec(f))){const target=prefixSheet(book,sheet,m[1]);if(!target)continue;const c1=colIndex(m[2]),r1=Number(m[3])-1;if(m[4]){const c2=colIndex(m[4]),r2=Number(m[5])-1;ranges.push({sheet:target.name,r1:Math.min(r1,r2),r2:Math.max(r1,r2),c1:Math.min(c1,c2),c2:Math.max(c1,c2)})}else cells.push(target.name+'!'+encodeRef(r1,c1))}return{cells,ranges}}
function newState(book){return{sheets:book.sheets.slice(),inputs:new Map(),formulas:new Map(),dependents:new Map(),rangeIndex:new Map(),last:new Map(),epoch:0}}
function sameSheets(st,book){if(st.sheets.length!==book.sheets.length)return false;for(let i=0;i<book.sheets.length;i++)if(st.sheets[i]!==book.sheets[i]||st.sheetNames?.[i]!==book.sheets[i].name)return false;return true}
function unlink(st,id){const rec=st.formulas.get(id);if(!rec)return;for(const dep of rec.cells){const set=st.dependents.get(dep);if(set){set.delete(id);if(!set.size)st.dependents.delete(dep)}}for(const q of rec.ranges){const cols=st.rangeIndex.get(q.sheet);if(!cols)continue;for(let c=q.c1;c<=q.c2;c++){const list=cols.get(c);if(list){const i=list.indexOf(q);if(i>=0)list.splice(i,1)}}}st.formulas.delete(id)}
function link(st,book,sheet,ref,id,formula){const deps=formulaDeps(book,sheet,formula),rec={sheet,ref,cells:deps.cells,ranges:deps.ranges};for(const dep of rec.cells){let set=st.dependents.get(dep);if(!set)st.dependents.set(dep,set=new Set());set.add(id)}for(const q of rec.ranges){q.formula=id;let cols=st.rangeIndex.get(q.sheet);if(!cols)st.rangeIndex.set(q.sheet,cols=new Map());for(let c=q.c1;c<=q.c2;c++){let list=cols.get(c);if(!list)cols.set(c,list=[]);list.push(q)}}st.formulas.set(id,rec)}
function dirtyFrom(st,changed){const dirty=new Set(),queued=new Set(changed),queue=changed.slice();while(queue.length){const id=queue.pop();if(st.formulas.has(id))dirty.add(id);const add=fid=>{if(!queued.has(fid)){queued.add(fid);queue.push(fid)}};const set=st.dependents.get(id);if(set)for(const fid of set)add(fid);const bang=id.lastIndexOf('!'),cols=st.rangeIndex.get(id.slice(0,bang));if(cols){const p=root.LocalXLSX.decodeRef(id.slice(bang+1)),list=p&&cols.get(p.c);if(list)for(const q of list)if(p.r>=q.r1&&p.r<=q.r2)add(q.formula)}}return dirty}
// keepCached (used when a workbook opens): formula cells keep the result saved in the file instead of being
// re-evaluated, so functions the evaluator lacks cannot replace a correct value with an error; edits recalculate as before.
function recalculate(book,{keepCached=false}={}){if(!book?.sheets)return;let st=states.get(book),full=!st||!sameSheets(st,book);if(full){st=newState(book);st.sheetNames=book.sheets.map(s=>s.name);states.set(book,st)}const epoch=++st.epoch,changed=[];
 for(const sheet of book.sheets){let inputs=st.inputs.get(sheet.name),seen=0;if(!inputs)st.inputs.set(sheet.name,inputs=new Map());
  for(const[ref,cell]of sheet.cells){seen++;const f=cell?.f||'',t=cell?.t,v=cell?.v,rec=inputs.get(ref);if(rec&&rec.f===f&&rec.t===t&&Object.is(rec.v,v)&&!(f&&cell.calculated===undefined&&st.last.get(sheet.name+'!'+ref)!=null)){rec.epoch=epoch;continue}const id=sheet.name+'!'+ref;if(!rec||rec.f!==f){unlink(st,id);if(f){link(st,book,sheet,ref,id,f);st.formulas.get(id).formula=f}}if(rec){rec.f=f;rec.t=t;rec.v=v;rec.epoch=epoch}else inputs.set(ref,{f,t,v,epoch});changed.push(id)}
  if(inputs.size>seen)for(const[ref,rec]of inputs)if(rec.epoch!==epoch){const id=sheet.name+'!'+ref;inputs.delete(ref);unlink(st,id);st.last.delete(id);changed.push(id)}}
 const dirty=full||changed.length>FULL_RECALC_CHANGES?new Set(st.formulas.keys()):dirtyFrom(st,changed);if(!dirty.size)return;
 ctx={dirty,last:st.last,memo:new Map(),cycles:0};try{for(const id of dirty){const rec=st.formulas.get(id),cell=rec&&rec.sheet.cells.get(rec.ref);if(!cell?.f)continue;if(keepCached&&cell.calculated===undefined&&cell.v!==undefined&&cell.v!==null&&cell.v!==''){st.last.set(id,cell.v);continue}const v=ctx.memo.has(id)?ctx.memo.get(id):evaluate(book,rec.sheet,cell.f,new Set([id]));st.last.set(id,v);if(v!==null&&v!==undefined){cell.calculatedRaw=v;cell.calculated=v;cell.display=typeof v==='number'&&typeof NS.FormulaDisplay==='function'?NS.FormulaDisplay(v,cell):String(v)}}}finally{ctx=null}}
NS.FormulaEvaluator=Object.freeze({evaluate,recalculate,isError,parseRef,parseRange});
})(globalThis);
