(function(g){'use strict';
const NS=g.InkDOS2Epub=g.InkDOS2Epub||{},LIBRARY_RENDER_LIMIT=500;
function create({elements:E,session,reader}={}){
 if(!E||!session||!reader)throw new Error('ReaderNavigationTools requires elements, session and reader');
 const state=session.state,$=id=>document.getElementById(id),ui={};let index=null,results=[],resultIndex=-1,returnStack=[],libraryFilter='all',bookmarkNoteTarget=null;
 function currentLocator(){return reader.capture()||state.locator}
 function blockFor(loc){if(!state.book||!loc)return null;for(let i=0;i<state.book.chapters.length;i++){const ch=state.book.chapters[i],b=ch.blocks.find(x=>x.id===loc.anchor);if(b)return {chapter:ch,chapterNo:i+1,block:b}}return null}
 function bookmarkLabel(loc){const hit=blockFor(loc);if(!hit)return 'Chapter '+(loc.chapter||1);const text=NS.EpubNavigationIndex.blockText(hit.block);return (hit.chapter.title+(text?' — '+text:'')).slice(0,150)}
 function sameLoc(a,b){return !!(a&&b&&a.anchor===b.anchor)}
 function pushReturn(){const loc=currentLocator();if(loc&&!sameLoc(loc,returnStack[returnStack.length-1])){returnStack.push({...loc});if(returnStack.length>20)returnStack.shift()}syncBack()}
 function syncBack(){if(ui.back)ui.back.disabled=!returnStack.length}
 function navigate(loc,label){if(!loc)return false;const here=currentLocator();if(!sameLoc(here,loc))pushReturn();if(!reader.goLocator(loc)){reader.notice('This reading position is no longer available.');return false}reader.notice(label||'Opened reading position',1200);syncBookmarkButton();return true}
 function goBack(){const loc=returnStack.pop();syncBack();if(loc&&reader.goLocator(loc)){reader.notice('Returned to previous reading position',1200);syncBookmarkButton()}}
 function showTab(name){for(const b of ui.tabs)b.classList.toggle('active',b.dataset.navTab===name);for(const p of ui.panels)p.hidden=p.dataset.navPanel!==name;if(name==='bookmarks')renderBookmarks();if(name==='library')renderLibrary();if(name==='search')setTimeout(()=>ui.searchInput.focus(),0)}
 function openNavigation(tab){reader.openNavigationSheet();showTab(tab)}
 function syncBookmarkButton(){if(!ui.bookmarkBtn)return;const loc=currentLocator(),saved=!!(loc&&state.bookmarks.some(b=>b.anchor===loc.anchor));ui.bookmarkBtn.classList.toggle('active',saved);ui.bookmarkBtn.setAttribute('aria-pressed',String(saved));ui.bookmarkBtn.title=saved?'Remove bookmark':'Add bookmark'}
 async function toggleBookmark(){if(!state.book){reader.notice('Open an EPUB first.');return}const loc=currentLocator();if(!loc)return;const r=session.toggleBookmark(loc,bookmarkLabel(loc));if(!r)return;await session.persist().catch(()=>{});renderBookmarks();syncBookmarkButton();renderLibrary();reader.notice(r.added?'Bookmark added':'Bookmark removed',1400)}
 async function removeBookmark(id){if(!session.removeBookmark(id))return;await session.persist().catch(()=>{});renderBookmarks();syncBookmarkButton();renderLibrary();reader.notice('Bookmark removed',1200)}
 function startBookmarkNote(bm){bookmarkNoteTarget=bm.id;ui.libraryCompose.hidden=false;ui.libraryComposeLabel.textContent='New note for '+(bm.label||('Chapter '+bm.chapter));ui.libraryDraft.value='';openNavigation('library');setTimeout(()=>ui.libraryDraft.focus(),0)}
 function renderBookmarks(){ui.bookmarkList.replaceChildren();ui.bookmarkEmpty.hidden=!!state.bookmarks.length;for(const bm of state.bookmarks.slice().sort((a,b)=>a.chapter-b.chapter||String(a.createdAt).localeCompare(String(b.createdAt)))){const row=document.createElement('div');row.className='epub-nav-row has-note-action';const open=document.createElement('button');open.type='button';open.className='epub-nav-open';const title=document.createElement('strong');title.textContent=bm.label||('Chapter '+bm.chapter);const meta=document.createElement('small');meta.textContent='Chapter '+bm.chapter;open.append(title,meta);open.addEventListener('click',()=>navigate(bm,'Bookmark opened'));const note=document.createElement('button');note.type='button';note.className='epub-nav-note';note.setAttribute('aria-label','Add note to bookmark');note.title='Add note';note.textContent='N';note.addEventListener('click',()=>startBookmarkNote(bm));const del=document.createElement('button');del.type='button';del.className='epub-nav-delete';del.setAttribute('aria-label','Remove bookmark');del.textContent='×';del.addEventListener('click',()=>removeBookmark(bm.id));row.append(open,note,del);ui.bookmarkList.append(row)}}
 function renderResults(){ui.searchResults.replaceChildren();ui.searchStatus.textContent=!state.book?'Open a book to search.':!ui.searchInput.value.trim()?'':results.length+(results.length===1?' result':' results')+(results.length>=NS.EpubNavigationIndex.MAX_RESULTS?' (limit)':'');results.forEach((r,i)=>{const b=document.createElement('button');b.type='button';b.className='epub-search-result'+(i===resultIndex?' current':'');const h=document.createElement('strong');h.textContent=r.chapterTitle||('Chapter '+r.chapter);const s=document.createElement('span');s.textContent=r.snippet;const m=document.createElement('small');m.textContent='Chapter '+r.chapter;b.append(h,s,m);b.addEventListener('click',()=>{resultIndex=i;navigate(r,'Search result opened');renderResults()});ui.searchResults.append(b)});ui.searchPrev.disabled=!results.length;ui.searchNext.disabled=!results.length}
 function runSearch(){if(!state.book||!index){results=[];resultIndex=-1;return renderResults()}const q=ui.searchInput.value.trim();results=q?index.search(q):[];resultIndex=results.length?0:-1;renderResults()}
 function stepResult(delta){if(!results.length)return;resultIndex=(resultIndex+delta+results.length)%results.length;const r=results[resultIndex];navigate(r,'Search result '+(resultIndex+1)+' of '+results.length);renderResults();const active=ui.searchResults.children[resultIndex];active?.scrollIntoView({block:'nearest'})}
 function anchorElement(anchor){if(!anchor)return null;const esc=(g.CSS&&CSS.escape)?CSS.escape(anchor):String(anchor).replace(/["\\]/g,'\\$&');return E.surface.querySelector('[data-anchor="'+esc+'"]')}
 function quoteForSegments(segments){const parts=[];for(const s of segments||[]){const el=anchorElement(s.anchor);if(!el)continue;const text=el.textContent||'';parts.push(text.slice(Math.max(0,s.start||0),Math.max(0,s.end||0)))}return parts.join(' ').replace(/\s+/g,' ').trim().slice(0,600)}
 function locatorForAnchor(anchor,start=0,end=0){const hit=blockFor({anchor});if(!hit)return null;return {anchor,chapter:hit.chapterNo,path:hit.chapter.path,fragment:hit.block.sourceId||'',start,end}}
 async function afterNoteMutation(message){await session.persist().catch(()=>{});renderLibrary();reader.notice(message,1600);reader.prepareExport()}
 async function savePassageNote(){const text=ui.passageNoteDraft.value.trim(),segments=state.selection;if(!segments||!segments.length){reader.notice('Select text in the book first.');return}if(!text){reader.notice('Enter a note first.');return}const first=segments[0],loc=locatorForAnchor(first.anchor,first.start,first.end);if(!loc){reader.notice('The selected passage could not be located.');return}const note=session.addNote({...loc,source:'passage',quote:quoteForSegments(segments),text});if(!note){reader.notice(state.notes.length>=NS.AnnotationStore.MAX_NOTES?'Note limit reached.':'Could not save this note.');return}ui.passageNoteDraft.value='';E.highlight.hidden=true;await afterNoteMutation('Note saved')}
 async function saveBookmarkNote(){const bm=state.bookmarks.find(b=>b.id===bookmarkNoteTarget),text=ui.libraryDraft.value.trim();if(!bm){cancelBookmarkNote();reader.notice('This bookmark is no longer available.');return}if(!text){reader.notice('Enter a note first.');return}const note=session.addNote({anchor:bm.anchor,start:0,end:0,chapter:bm.chapter,path:bm.path,fragment:bm.fragment,source:'bookmark',bookmarkId:bm.id,quote:bm.label,text});if(!note){reader.notice(state.notes.length>=NS.AnnotationStore.MAX_NOTES?'Note limit reached.':'Could not save this note.');return}cancelBookmarkNote();await afterNoteMutation('Bookmark note saved')}
 function cancelBookmarkNote(){bookmarkNoteTarget=null;ui.libraryDraft.value='';ui.libraryCompose.hidden=true}
 async function deleteNote(id){if(!session.removeNote(id))return;await afterNoteMutation('Note deleted')}
 function editNote(row,note){if(row.querySelector('.epub-note-editor'))return;const editor=document.createElement('div');editor.className='epub-note-editor';const input=document.createElement('textarea');input.maxLength=NS.AnnotationStore.MAX_NOTE_CHARS;input.value=note.text;input.setAttribute('aria-label','Edit note');const actions=document.createElement('div');actions.className='epub-note-edit-actions';const save=document.createElement('button');save.type='button';save.textContent='Save';const cancel=document.createElement('button');cancel.type='button';cancel.textContent='Cancel';actions.append(save,cancel);editor.append(input,actions);row.append(editor);save.addEventListener('click',async()=>{const text=input.value.trim();if(!text){reader.notice('A note cannot be empty.');return}const next=session.updateNote(note.id,text);if(!next){reader.notice('Could not update this note.');return}await afterNoteMutation('Note updated')});cancel.addEventListener('click',()=>editor.remove());setTimeout(()=>{input.focus();input.setSelectionRange(input.value.length,input.value.length)},0)}
 function highlightEntry(h){const first=h.segments&&h.segments[0];if(!first)return null;const loc=locatorForAnchor(first.anchor,first.start,first.end);if(!loc)return null;return {kind:'highlight',id:h.id,chapter:loc.chapter,loc,quote:quoteForSegments(h.segments),color:h.color}}
 function noteEntry(n){return {kind:'note',id:n.id,chapter:Number(n.chapter)||1,loc:n,quote:n.quote||'',note:n}}
 function renderLibrary(){if(!ui.libraryList)return;ui.libraryList.replaceChildren();const highlights=state.annotations.map(highlightEntry).filter(Boolean),notes=state.notes.map(noteEntry),all=[...highlights,...notes].sort((a,b)=>a.chapter-b.chapter||a.kind.localeCompare(b.kind));const filtered=all.filter(x=>libraryFilter==='all'||libraryFilter===x.kind),shown=filtered.slice(0,LIBRARY_RENDER_LIMIT);ui.libraryEmpty.hidden=!!shown.length;ui.libraryStatus.textContent=highlights.length+' highlight'+(highlights.length===1?'':'s')+' · '+notes.length+' note'+(notes.length===1?'':'s')+(filtered.length>LIBRARY_RENDER_LIMIT?' · showing first '+LIBRARY_RENDER_LIMIT:'');for(const b of ui.libraryFilters)b.classList.toggle('active',b.dataset.libraryFilter===libraryFilter);for(const item of shown){const row=document.createElement('div');row.className='epub-library-entry';const head=document.createElement('div');head.className='epub-library-head';const open=document.createElement('button');open.type='button';open.className='epub-library-open';const title=document.createElement('strong');title.textContent=item.kind==='note'?'Note · Chapter '+item.chapter:'Highlight · '+item.color+' · Chapter '+item.chapter;const quote=document.createElement('span');quote.textContent=item.quote||'(no text preview)';open.append(title,quote);open.addEventListener('click',()=>navigate(item.loc,item.kind==='note'?'Note opened':'Highlight opened'));head.append(open);if(item.kind==='note'){const actions=document.createElement('div');actions.className='epub-library-actions';const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.addEventListener('click',()=>editNote(row,item.note));const del=document.createElement('button');del.type='button';del.textContent='Delete';del.addEventListener('click',()=>deleteNote(item.id));actions.append(edit,del);head.append(actions);const body=document.createElement('p');body.className='epub-library-note';body.textContent=item.note.text;row.append(head,body)}else row.append(head);ui.libraryList.append(row)}}
 function installLibraryUi(){
  const tabsHost=E.toc.querySelector('.epub-nav-tabs');if(!tabsHost)return;const tab=document.createElement('button');tab.type='button';tab.dataset.navTab='library';tab.textContent='Library';tabsHost.insertBefore(tab,tabsHost.querySelector('[data-nav-tab="search"]'));
  const panel=document.createElement('div');panel.className='epub-nav-panel';panel.dataset.navPanel='library';panel.hidden=true;panel.innerHTML='<div class="epub-library-filters" role="group" aria-label="Reading library filter"><button type="button" class="active" data-library-filter="all">All</button><button type="button" data-library-filter="highlight">Highlights</button><button type="button" data-library-filter="note">Notes</button></div><div id="libraryStatus" class="epub-search-status"></div><div id="libraryCompose" class="epub-library-compose" hidden><strong id="libraryComposeLabel">New bookmark note</strong><textarea id="libraryDraft" maxlength="4000" placeholder="Write a note" aria-label="Bookmark note"></textarea><div><button id="librarySaveNote" type="button">Save note</button><button id="libraryCancelNote" type="button">Cancel</button></div></div><div id="libraryEmpty" class="epub-nav-empty">No highlights or notes yet.</div><div id="libraryList" class="epub-library-list"></div>';
  E.toc.append(panel);
  const passage=document.createElement('div');passage.className='epub-passage-note';passage.innerHTML='<label for="passageNoteDraft">Note on selected text</label><textarea id="passageNoteDraft" maxlength="4000" placeholder="Write a note" aria-label="Note on selected text"></textarea><button id="passageNoteSave" type="button">Add note</button>';
  const sheetNote=E.highlight.querySelector('.sheet-note');E.highlight.insertBefore(passage,sheetNote||null);
  if(!document.getElementById('epubE2Styles')){const style=document.createElement('style');style.id='epubE2Styles';style.textContent='.epub-nav-tabs{grid-template-columns:repeat(4,1fr)}.epub-nav-row.has-note-action{grid-template-columns:minmax(0,1fr) 38px 38px}.epub-nav-note{border:0;background:transparent;color:var(--muted);font-weight:800}.epub-nav-note:hover,.epub-nav-note:focus-visible{background:var(--epub-accent-soft);outline:none}.epub-passage-note,.epub-library-compose{display:grid;gap:7px;padding-top:9px;border-top:1px solid var(--line)}.epub-passage-note label,.epub-library-compose strong{font-size:12px;color:var(--muted)}.epub-passage-note textarea,.epub-library-compose textarea,.epub-note-editor textarea{width:100%;min-height:72px;resize:vertical;border:1px solid var(--line);border-radius:10px;background:var(--chrome);color:var(--text);padding:8px;font:inherit;line-height:1.35;outline:none}.epub-passage-note textarea:focus,.epub-library-compose textarea:focus,.epub-note-editor textarea:focus{border-color:var(--epub-accent)}.epub-passage-note button,.epub-library-compose button,.epub-note-edit-actions button,.epub-library-actions button,.epub-library-filters button{min-height:34px;border:1px solid var(--line);border-radius:9px;background:var(--chrome);color:var(--text);font-weight:650}.epub-library-compose>div,.epub-note-edit-actions,.epub-library-actions{display:flex;gap:6px}.epub-library-filters{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.epub-library-filters button.active{background:var(--epub-accent-soft);border-color:var(--epub-accent)}.epub-library-list{display:grid;max-height:360px;overflow:auto}.epub-library-entry{border-bottom:1px solid var(--line);padding:7px 0}.epub-library-head{display:flex;align-items:flex-start;gap:6px}.epub-library-open{min-width:0;flex:1;border:0;background:transparent;color:var(--text);text-align:left;padding:5px 7px;display:grid;gap:4px}.epub-library-open strong{font-size:12px}.epub-library-open span{font-size:11px;color:var(--muted);line-height:1.35;overflow:hidden;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical}.epub-library-open:hover,.epub-library-open:focus-visible{background:var(--epub-accent-soft);outline:none}.epub-library-actions{padding:4px}.epub-library-actions button{min-height:30px;font-size:10px;padding:0 7px}.epub-library-note{margin:2px 7px 7px;font-size:12px;line-height:1.4;white-space:pre-wrap}.epub-note-editor{display:grid;gap:6px;padding:7px}.epub-note-edit-actions{justify-content:flex-end}@media(max-width:640px){.epub-nav-tabs{grid-template-columns:repeat(2,1fr)}.epub-library-list{max-height:26vh}}';document.head.append(style)}
 }
 function rebuild(){index=state.book?NS.EpubNavigationIndex.create(state.book):null;results=[];resultIndex=-1;returnStack=[];ui.searchInput.value='';cancelBookmarkNote();renderResults();renderBookmarks();renderLibrary();syncBookmarkButton();syncBack();showTab('contents');if(state.annotationDirty&&!state.exportReady)reader.prepareExport()}
 function install(){
  ui.bookmarkBtn=$('bookmarkBtn');ui.searchBtn=$('searchBtn');ui.bookmarkList=$('bookmarkList');ui.bookmarkEmpty=$('bookmarkEmpty');ui.searchInput=$('bookSearchInput');ui.searchPrev=$('searchPrev');ui.searchNext=$('searchNext');ui.searchStatus=$('searchStatus');ui.searchResults=$('searchResults');ui.back=$('readingBackBtn');installLibraryUi();ui.tabs=Array.from(document.querySelectorAll('[data-nav-tab]'));ui.panels=Array.from(document.querySelectorAll('[data-nav-panel]'));ui.libraryList=$('libraryList');ui.libraryEmpty=$('libraryEmpty');ui.libraryStatus=$('libraryStatus');ui.libraryFilters=Array.from(document.querySelectorAll('[data-library-filter]'));ui.libraryCompose=$('libraryCompose');ui.libraryComposeLabel=$('libraryComposeLabel');ui.libraryDraft=$('libraryDraft');ui.librarySave=$('librarySaveNote');ui.libraryCancel=$('libraryCancelNote');ui.passageNoteDraft=$('passageNoteDraft');ui.passageNoteSave=$('passageNoteSave');
  ui.bookmarkBtn.addEventListener('click',toggleBookmark);ui.searchBtn.addEventListener('click',()=>openNavigation('search'));for(const b of ui.tabs)b.addEventListener('click',()=>showTab(b.dataset.navTab));ui.searchInput.addEventListener('input',runSearch);ui.searchInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();stepResult(e.shiftKey?-1:1)}else if(e.key==='Escape'){E.toc.hidden=true}});ui.searchPrev.addEventListener('click',()=>stepResult(-1));ui.searchNext.addEventListener('click',()=>stepResult(1));ui.back.addEventListener('click',goBack);for(const b of ui.libraryFilters)b.addEventListener('click',()=>{libraryFilter=b.dataset.libraryFilter;renderLibrary()});ui.librarySave.addEventListener('click',saveBookmarkNote);ui.libraryCancel.addEventListener('click',cancelBookmarkNote);ui.passageNoteSave.addEventListener('pointerdown',()=>{const seg=NS.ReaderAnnotations.capture(E.surface);if(seg)session.setSelection(seg)});ui.passageNoteSave.addEventListener('click',savePassageNote);document.addEventListener('inkdos:epub-opened',rebuild);document.addEventListener('inkdos:epub-location',syncBookmarkButton);rebuild()
 }
 const api=Object.freeze({openNavigation,showTab,runSearch,stepResult,toggleBookmark,goBack,rebuild,renderLibrary,state:()=>({resultCount:results.length,resultIndex,returnDepth:returnStack.length,indexSize:index?.size||0,libraryCount:(state.annotations?.length||0)+(state.notes?.length||0),noteCount:state.notes?.length||0})});
 return Object.freeze({install,api});
}
NS.ReaderNavigationTools=Object.freeze({create});
})(globalThis);
