(function(g){'use strict';
const NS=g.InkDOS2Epub=g.InkDOS2Epub||{};
function create({elements:E,session,reader}={}){
 if(!E||!session||!reader)throw new Error('ReaderNavigationTools requires elements, session and reader');
 const state=session.state,$=id=>document.getElementById(id),ui={};let index=null,results=[],resultIndex=-1,returnStack=[];
 function currentLocator(){return reader.capture()||state.locator}
 function blockFor(loc){if(!state.book||!loc)return null;for(const ch of state.book.chapters){const b=ch.blocks.find(x=>x.id===loc.anchor);if(b)return {chapter:ch,block:b}}return null}
 function bookmarkLabel(loc){const hit=blockFor(loc);if(!hit)return 'Chapter '+(loc.chapter||1);const text=NS.EpubNavigationIndex.blockText(hit.block);return (hit.chapter.title+(text?' — '+text:'')).slice(0,150)}
 function sameLoc(a,b){return !!(a&&b&&a.anchor===b.anchor)}
 function pushReturn(){const loc=currentLocator();if(loc&&!sameLoc(loc,returnStack[returnStack.length-1])){returnStack.push({...loc});if(returnStack.length>20)returnStack.shift()}syncBack()}
 function syncBack(){if(ui.back)ui.back.disabled=!returnStack.length}
 function navigate(loc,label){if(!loc)return false;const here=currentLocator();if(!sameLoc(here,loc))pushReturn();if(!reader.goLocator(loc)){reader.notice('This reading position is no longer available.');return false}reader.notice(label||'Opened reading position',1200);syncBookmarkButton();return true}
 function goBack(){const loc=returnStack.pop();syncBack();if(loc&&reader.goLocator(loc)){reader.notice('Returned to previous reading position',1200);syncBookmarkButton()}}
 function showTab(name){for(const b of ui.tabs)b.classList.toggle('active',b.dataset.navTab===name);for(const p of ui.panels)p.hidden=p.dataset.navPanel!==name;if(name==='bookmarks')renderBookmarks();if(name==='search')setTimeout(()=>ui.searchInput.focus(),0)}
 function openNavigation(tab){if(E.toc.hidden)E.tocBtn.click();showTab(tab)}
 function syncBookmarkButton(){if(!ui.bookmarkBtn)return;const loc=currentLocator(),saved=!!(loc&&state.bookmarks.some(b=>b.anchor===loc.anchor));ui.bookmarkBtn.classList.toggle('active',saved);ui.bookmarkBtn.setAttribute('aria-pressed',String(saved));ui.bookmarkBtn.title=saved?'Remove bookmark':'Add bookmark'}
 async function toggleBookmark(){if(!state.book){reader.notice('Open an EPUB first.');return}const loc=currentLocator();if(!loc)return;const r=session.toggleBookmark(loc,bookmarkLabel(loc));if(!r)return;await session.persist().catch(()=>{});renderBookmarks();syncBookmarkButton();reader.notice(r.added?'Bookmark added':'Bookmark removed',1400)}
 async function removeBookmark(id){if(!session.removeBookmark(id))return;await session.persist().catch(()=>{});renderBookmarks();syncBookmarkButton();reader.notice('Bookmark removed',1200)}
 function renderBookmarks(){ui.bookmarkList.replaceChildren();ui.bookmarkEmpty.hidden=!!state.bookmarks.length;for(const bm of state.bookmarks.slice().sort((a,b)=>a.chapter-b.chapter||String(a.createdAt).localeCompare(String(b.createdAt)))){const row=document.createElement('div');row.className='epub-nav-row';const open=document.createElement('button');open.type='button';open.className='epub-nav-open';const title=document.createElement('strong');title.textContent=bm.label||('Chapter '+bm.chapter);const meta=document.createElement('small');meta.textContent='Chapter '+bm.chapter;open.append(title,meta);open.addEventListener('click',()=>navigate(bm,'Bookmark opened'));const del=document.createElement('button');del.type='button';del.className='epub-nav-delete';del.setAttribute('aria-label','Remove bookmark');del.textContent='×';del.addEventListener('click',()=>removeBookmark(bm.id));row.append(open,del);ui.bookmarkList.append(row)}}
 function renderResults(){ui.searchResults.replaceChildren();ui.searchStatus.textContent=!state.book?'Open a book to search.':!ui.searchInput.value.trim()?'':results.length+(results.length===1?' result':' results')+(results.length>=NS.EpubNavigationIndex.MAX_RESULTS?' (limit)':'');results.forEach((r,i)=>{const b=document.createElement('button');b.type='button';b.className='epub-search-result'+(i===resultIndex?' current':'');const h=document.createElement('strong');h.textContent=r.chapterTitle||('Chapter '+r.chapter);const s=document.createElement('span');s.textContent=r.snippet;const m=document.createElement('small');m.textContent='Chapter '+r.chapter;b.append(h,s,m);b.addEventListener('click',()=>{resultIndex=i;navigate(r,'Search result opened');renderResults()});ui.searchResults.append(b)});ui.searchPrev.disabled=!results.length;ui.searchNext.disabled=!results.length}
 function runSearch(){if(!state.book||!index){results=[];resultIndex=-1;return renderResults()}const q=ui.searchInput.value.trim();results=q?index.search(q):[];resultIndex=results.length?0:-1;renderResults()}
 function stepResult(delta){if(!results.length)return;resultIndex=(resultIndex+delta+results.length)%results.length;const r=results[resultIndex];navigate(r,'Search result '+(resultIndex+1)+' of '+results.length);renderResults();const active=ui.searchResults.children[resultIndex];active?.scrollIntoView({block:'nearest'})}
 function rebuild(){index=state.book?NS.EpubNavigationIndex.create(state.book):null;results=[];resultIndex=-1;returnStack=[];ui.searchInput.value='';renderResults();renderBookmarks();syncBookmarkButton();syncBack();showTab('contents')}
 function install(){
  ui.bookmarkBtn=$('bookmarkBtn');ui.searchBtn=$('searchBtn');ui.tabs=Array.from(document.querySelectorAll('[data-nav-tab]'));ui.panels=Array.from(document.querySelectorAll('[data-nav-panel]'));ui.bookmarkList=$('bookmarkList');ui.bookmarkEmpty=$('bookmarkEmpty');ui.searchInput=$('bookSearchInput');ui.searchPrev=$('searchPrev');ui.searchNext=$('searchNext');ui.searchStatus=$('searchStatus');ui.searchResults=$('searchResults');ui.back=$('readingBackBtn');
  ui.bookmarkBtn.addEventListener('click',toggleBookmark);ui.searchBtn.addEventListener('click',()=>openNavigation('search'));E.tocBtn.addEventListener('click',()=>{if(!E.toc.hidden)showTab('contents')});for(const b of ui.tabs)b.addEventListener('click',()=>showTab(b.dataset.navTab));ui.searchInput.addEventListener('input',runSearch);ui.searchInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();stepResult(e.shiftKey?-1:1)}else if(e.key==='Escape'){E.toc.hidden=true}});ui.searchPrev.addEventListener('click',()=>stepResult(-1));ui.searchNext.addEventListener('click',()=>stepResult(1));ui.back.addEventListener('click',goBack);document.addEventListener('inkdos:epub-opened',rebuild);document.addEventListener('inkdos:epub-location',syncBookmarkButton);rebuild()
 }
 const api=Object.freeze({openNavigation,showTab,runSearch,stepResult,toggleBookmark,goBack,rebuild,state:()=>({resultCount:results.length,resultIndex,returnDepth:returnStack.length,indexSize:index?.size||0})});
 return Object.freeze({install,api});
}
NS.ReaderNavigationTools=Object.freeze({create});
})(globalThis);
