(function(global){
'use strict';
document.body.dataset.inkdeskDocumentSession='ready';
const MAX_FILE_BYTES=100*1024*1024;
const REMOVED=new Set(['SCRIPT','STYLE','NOSCRIPT','IFRAME','OBJECT','EMBED','FORM','INPUT','BUTTON','TEXTAREA','SELECT','OPTION','AUDIO','VIDEO','SOURCE','CANVAS']);
const ALLOWED=new Set(['ARTICLE','SECTION','DIV','P','H1','H2','H3','H4','H5','H6','UL','OL','LI','BLOCKQUOTE','PRE','CODE','EM','STRONG','B','I','U','S','SMALL','SUB','SUP','BR','HR','FIGURE','FIGCAPTION','IMG','TABLE','THEAD','TBODY','TR','TH','TD']);
const BLOCKS='h1,h2,h3,h4,h5,h6,p,blockquote,pre,ul,ol,figure,table,img,hr';const $=id=>document.getElementById(id);
const E={open:$('openBtn'),openStart:$('openStartBtn'),toc:$('tocBtn'),tocPanel:$('tocPanel'),tocClose:$('tocClose'),tocList:$('tocList'),save:$('saveBtn'),title:$('docTitle'),dirty:$('dirtyMark'),fontDown:$('fontDecrease'),fontUp:$('fontIncrease'),fontLabel:$('fontSizeLabel'),themes:Array.from(document.querySelectorAll('[data-theme]')),meta:$('bookMeta'),start:$('startScreen'),shell:$('readerShell'),prev:$('previousPage'),next:$('nextPage'),surface:$('pageSurface'),content:$('pageContent'),status:$('statusText'),chapter:$('chapterLabel'),counter:$('pageCounter'),zoomOut:$('epubZoomOut'),zoomSlider:$('epubZoomSlider'),zoomIn:$('epubZoomIn'),zoomFit:$('epubFit'),zoomLabel:$('epubZoomLabel'),input:$('fileInput')};
const parser=global.InkDeskEpubParser;if(!parser)throw new Error('The local EPUB parser did not load.');
const state={loaded:false,file:null,fileName:'Untitled.epub',zip:null,book:null,sections:[],cover:'',pages:[],page:0,fontSize:18,theme:'paper',workspaceZoom:100,urls:[],touch:null,timer:0};
const lifecycle=global.InkDeskFileLifecycle.create({onChange(value){E.dirty.hidden=!value.shouldWarnBeforeUnload;E.save.disabled=!state.loaded;document.title=state.fileName+(value.shouldWarnBeforeUnload?' •':'')+' — EPUB Reader'}});
function status(value){E.status.textContent=String(value||'Ready')}
function cleanName(value){let name=String(value||'').trim()||'Untitled.epub';name=name.replace(/[\\/:*?"<>|]+/g,'-');return /\.epub$/i.test(name)?name:name+'.epub'}
function setTitle(value){state.fileName=cleanName(value);E.title.value=state.fileName;document.title=state.fileName+(lifecycle.shouldWarnBeforeUnload()?' •':'')+' — EPUB Reader';return state.fileName}
function commitTitle(){const previous=state.fileName,next=setTitle(E.title.value);if(state.loaded&&next!==previous){if(!lifecycle.shouldWarnBeforeUnload())lifecycle.markDirty();status('Book copy renamed to '+next)}}
function confirmDiscard(){return lifecycle.confirmDiscard('This EPUB has an unsaved renamed copy. Continue and discard it?')}
function releaseUrls(){state.urls.forEach(url=>{try{URL.revokeObjectURL(url)}catch(error){console.debug(error)}});state.urls=[]}
function showReader(){E.start.hidden=true;E.shell.hidden=false;E.toc.disabled=false;E.save.disabled=false;state.loaded=true}
function escapeHtml(value){return String(value||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
async function resourceUrl(path,type){const entry=state.zip.file(parser.normalizePath(path));if(!entry)return'';const bytes=await entry.async('uint8array'),url=URL.createObjectURL(new Blob([bytes],{type:type||parser.mediaTypeForPath(path)}));state.urls.push(url);return url}
function unwrap(element){const parent=element.parentNode;if(!parent)return;while(element.firstChild)parent.insertBefore(element.firstChild,element);element.remove()}
async function sanitize(section,source){const doc=new DOMParser().parseFromString(String(source||''),'text/html'),body=doc.body;Array.from(body.querySelectorAll('*')).forEach(node=>{if(REMOVED.has(node.tagName))node.remove()});for(const image of Array.from(body.querySelectorAll('img'))){const path=parser.resolvePath(section.path,image.getAttribute('src')||'');if(!path){image.remove();continue}const item=Object.values(state.book.manifest).find(candidate=>candidate.path===path),url=await resourceUrl(path,item&&/^image\//i.test(item.mediaType)?item.mediaType:parser.mediaTypeForPath(path));if(!url){image.remove();continue}const alt=image.getAttribute('alt')||'',title=image.getAttribute('title')||'';Array.from(image.attributes).forEach(attribute=>image.removeAttribute(attribute.name));image.src=url;if(alt)image.alt=alt;if(title)image.title=title;image.loading='lazy';image.decoding='async'}Array.from(body.querySelectorAll('*')).reverse().forEach(node=>{if(!node.isConnected)return;if(!ALLOWED.has(node.tagName)){unwrap(node);return}Array.from(node.attributes).forEach(attribute=>{const image=node.tagName==='IMG'&&['src','alt','title','loading','decoding'].includes(attribute.name),cell=['TD','TH'].includes(node.tagName)&&['colspan','rowspan'].includes(attribute.name);if(!image&&!cell)node.removeAttribute(attribute.name)})});return body.innerHTML.trim()}
function capacity(){const width=Math.max(.72,Math.min(1.35,E.surface.clientWidth/820)),height=Math.max(.68,Math.min(1.35,E.surface.clientHeight/760));
const effectiveFont=state.fontSize*(state.workspaceZoom/100);return Math.max(620,Math.round(2450*width*height*(18/effectiveFont)))}
function sectionBlocks(section,index){const holder=document.createElement('div');holder.innerHTML=section.html;let nodes=Array.from(holder.querySelectorAll(BLOCKS)).filter(node=>!node.parentElement||!node.parentElement.closest(BLOCKS));if(!nodes.length&&holder.textContent.trim()){const p=document.createElement('p');p.textContent=holder.textContent.trim();nodes=[p]}return nodes.map(node=>{const text=(node.textContent||'').trim().length,images=node.matches('img')?1:node.querySelectorAll('img').length;return{html:node.outerHTML,units:Math.max(90,text)+images*850+(/^H[1-6]$/.test(node.tagName)?220:0)+(node.tagName==='TABLE'?850:0),section:index,title:section.title}})}
function paginate(){if(!state.sections.length)return;const oldSection=state.pages[state.page]?state.pages[state.page].section:0,limit=capacity(),pages=[];if(state.cover)pages.push({html:'<div class="cover-page">'+state.cover+'</div>',section:-1,title:'Cover'});state.sections.forEach((section,index)=>{let current=[],units=0;const flush=()=>{if(!current.length)return;pages.push({html:'<div class="chapter-kicker">'+escapeHtml(section.title)+'</div>'+current.map(block=>block.html).join(''),section:index,title:section.title});current=[];units=0};sectionBlocks(section,index).forEach(block=>{if(current.length&&units+block.units>limit)flush();current.push(block);units+=block.units});flush()});state.pages=pages.length?pages:[{html:'<p>This EPUB did not contain readable text.</p>',section:0,title:'Book'}];const match=state.pages.findIndex(page=>page.section===oldSection);state.page=match>=0?match:0;renderToc();render()}
function render(){const page=state.pages[state.page];if(!page)return;E.content.innerHTML=page.html;E.content.style.setProperty('--reader-font-size',state.fontSize+'px');E.surface.scrollTop=0;E.prev.disabled=state.page<=0;E.next.disabled=state.page>=state.pages.length-1;E.counter.textContent=(state.page+1)+' / '+state.pages.length;E.chapter.textContent=page.title||'Book';Array.from(E.tocList.querySelectorAll('.toc-item')).forEach(button=>button.classList.toggle('active',Number(button.dataset.section)===page.section));const key=positionKey();if(key)localStorage.setItem(key,String(state.page))}
function go(index){state.page=Math.max(0,Math.min(state.pages.length-1,Number(index)||0));render()}
function renderToc(){E.tocList.replaceChildren();state.sections.forEach((section,index)=>{const page=state.pages.findIndex(value=>value.section===index);if(page<0)return;const button=document.createElement('button');button.type='button';button.className='toc-item';button.dataset.section=String(index);button.textContent=section.title;button.onclick=()=>{toggleToc(false);go(page)};E.tocList.appendChild(button)})}
function toggleToc(force){const open=force===undefined?E.tocPanel.hidden:Boolean(force);E.tocPanel.hidden=!open;E.toc.setAttribute('aria-pressed',String(open))}
function setFont(value){state.fontSize=Math.max(13,Math.min(30,Number(value)||18));E.fontLabel.textContent=state.fontSize+' px';E.fontDown.disabled=state.fontSize<=13;E.fontUp.disabled=state.fontSize>=30;E.content.style.setProperty('--reader-font-size',state.fontSize+'px');localStorage.setItem('inkdesk.epub.fontSize',String(state.fontSize));clearTimeout(state.timer);state.timer=setTimeout(paginate,90)}
function setTheme(value){const allowed=new Set(['paper','sepia','sage','night']);state.theme=allowed.has(value)?value:'paper';document.body.dataset.readerTheme=state.theme;E.themes.forEach(button=>button.classList.toggle('active',button.dataset.theme===state.theme));localStorage.setItem('inkdesk.epub.theme',state.theme)}
function setWorkspaceZoom(value){state.workspaceZoom=Math.max(50,Math.min(160,Math.round((Number(value)||100)/5)*5));E.content.style.zoom=String(state.workspaceZoom/100);
E.zoomSlider.value=String(state.workspaceZoom);E.zoomLabel.textContent=state.workspaceZoom+'%';if(state.loaded){clearTimeout(state.timer);state.timer=setTimeout(paginate,90)}}
function positionKey(){return state.file?'inkdesk.epub.position.'+[state.fileName,state.file.size,state.file.lastModified||0].join('.'):''}
async function coverHtml(){if(!state.book.cover)return'';const url=await resourceUrl(state.book.cover.path,state.book.cover.mediaType||parser.mediaTypeForPath(state.book.cover.path));return url?'<img src="'+url+'" alt="'+escapeHtml(state.book.title)+' cover">':''}
async function openFile(file){if(!(file instanceof Blob))throw new TypeError('An EPUB file is required.');const name=String(file.name||'Untitled.epub');if(!/\.epub$/i.test(name))throw new Error('Choose an EPUB file.');if(!file.size)throw new Error('The selected EPUB is empty or unavailable.');if(file.size>MAX_FILE_BYTES)throw new Error('The selected EPUB is larger than the 100 MB local reader limit.');if(!confirmDiscard())return;status('Opening '+name+'…');releaseUrls();state.file=file;state.fileName=cleanName(name);state.sections=[];state.pages=[];state.page=0;state.zip=await global.JSZip.loadAsync(file);const container=state.zip.file('META-INF/container.xml');if(!container)throw new Error('This archive is missing META-INF/container.xml.');const packagePath=parser.parseContainer(await container.async('string')),packageEntry=state.zip.file(packagePath);if(!packageEntry)throw new Error('The EPUB package document could not be found.');state.book=parser.parsePackage(await packageEntry.async('string'),packagePath);if(!state.book.sections.length)throw new Error('The EPUB spine does not contain readable text sections.');state.cover=await coverHtml();for(const section of state.book.sections){const entry=state.zip.file(section.path);if(!entry)continue;const html=await sanitize(section,await entry.async('string')),probe=document.createElement('div');probe.innerHTML=html;const heading=probe.querySelector('h1,h2,h3,h4,h5,h6');state.sections.push({path:section.path,title:heading&&heading.textContent.trim()?heading.textContent.trim():'Section '+(state.sections.length+1),html})}if(!state.sections.length)throw new Error('InkDesk could not extract readable EPUB sections.');setTitle(name);E.meta.textContent=[state.book.title,state.book.creator].filter(Boolean).join(' · ');showReader();lifecycle.sourceOpened();paginate();const saved=Number(localStorage.getItem(positionKey()));if(Number.isFinite(saved))state.page=Math.max(0,Math.min(state.pages.length-1,saved));render();status('Opened '+state.book.title+' · '+state.sections.length+' sections');E.surface.focus()}
function fallbackDownload(blob,fileName){const anchor=document.createElement('a'),url=URL.createObjectURL(blob);anchor.href=url;anchor.download=fileName;anchor.hidden=true;document.body.appendChild(anchor);try{anchor.click()}finally{anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),15000)}return{fileName,bytes:blob.size}}
function saveCopy(){if(!state.loaded||!state.file)return;commitTitle();status('Saving EPUB copy…');try{const receipt=global.InkDeskRuntime&&typeof global.InkDeskRuntime.requestDownload==='function'?global.InkDeskRuntime.requestDownload(state.file,state.fileName):fallbackDownload(state.file,state.fileName);lifecycle.resetClean();status('Download requested · '+receipt.fileName)}catch(error){lifecycle.exportFailed(error);console.error(error);status('Save failed');global.alert('InkDesk could not save the EPUB copy.\n\n'+(error&&error.message?error.message:error))}}
function openPicker(){if(!confirmDiscard())return;E.input.value='';E.input.click()}
E.open.onclick=openPicker;E.openStart.onclick=openPicker;E.input.onchange=()=>{const file=E.input.files&&E.input.files[0];if(file)openFile(file).catch(error=>{console.error(error);status('Open failed');global.alert('InkDesk could not open this EPUB.\n\n'+(error&&error.message?error.message:error))})};E.title.onfocus=()=>E.title.select();E.title.onblur=commitTitle;E.title.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();E.title.blur()}else if(event.key==='Escape'){event.preventDefault();E.title.value=state.fileName;E.title.blur()}};E.save.onclick=saveCopy;E.toc.onclick=()=>toggleToc();E.tocClose.onclick=()=>toggleToc(false);E.prev.onclick=()=>go(state.page-1);E.next.onclick=()=>go(state.page+1);E.fontDown.onclick=()=>setFont(state.fontSize-1);E.fontUp.onclick=()=>setFont(state.fontSize+1);E.zoomOut.onclick=()=>setWorkspaceZoom(state.workspaceZoom-10);E.zoomSlider.oninput=()=>setWorkspaceZoom(E.zoomSlider.value);E.zoomIn.onclick=()=>setWorkspaceZoom(state.workspaceZoom+10);E.zoomFit.onclick=()=>setWorkspaceZoom(100);E.themes.forEach(button=>button.onclick=()=>setTheme(button.dataset.theme));E.surface.addEventListener('touchstart',event=>{state.touch=event.changedTouches&&event.changedTouches[0]?event.changedTouches[0].clientX:null},{passive:true});E.surface.addEventListener('touchend',event=>{if(state.touch===null)return;const end=event.changedTouches&&event.changedTouches[0]?event.changedTouches[0].clientX:state.touch,delta=end-state.touch;state.touch=null;if(Math.abs(delta)>=45)go(state.page+(delta<0?1:-1))},{passive:true});global.addEventListener('keydown',event=>{if(!state.loaded||document.activeElement===E.title)return;if(event.key==='ArrowRight'||event.key==='PageDown'){event.preventDefault();go(state.page+1)}else if(event.key==='ArrowLeft'||event.key==='PageUp'){event.preventDefault();go(state.page-1)}else if(event.key==='Home'){event.preventDefault();go(0)}else if(event.key==='End'){event.preventDefault();go(state.pages.length-1)}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();saveCopy()}});global.addEventListener('resize',()=>{if(state.loaded){clearTimeout(state.timer);state.timer=setTimeout(paginate,160)}});global.addEventListener('pagehide',releaseUrls);
global.InkDeskWorkspaceOpenFile=openFile;if(global.InkDeskFileRouter)global.InkDeskFileRouter.attachWorkspace({extensions:['epub'],openFile});setTitle('Untitled.epub');setTheme(localStorage.getItem('inkdesk.epub.theme')||'paper');setFont(Number(localStorage.getItem('inkdesk.epub.fontSize'))||18);setWorkspaceZoom(100);E.start.hidden=false;E.shell.hidden=true;E.tocPanel.hidden=true;global.InkDeskEpubDebug=Object.freeze({version:'0.20.0',openFile,saveCopy,getState:()=>({loaded:state.loaded,fileName:state.fileName,title:state.book?state.book.title:'',sections:state.sections.length,pages:state.pages.length,pageIndex:state.page,fontSize:state.fontSize,theme:state.theme,dirty:lifecycle.shouldWarnBeforeUnload()})});})(window);
