(function(){'use strict';
const NS=globalThis.InkDOS2Epub,$=id=>document.getElementById(id);
const E={menu:$('menuBtn'),drawer:$('mainMenu'),backdrop:$('backdrop'),closeMenu:$('closeMenuBtn'),toolbar:$('toolbar'),open:$('openBtn'),openStart:$('openStartBtn'),save:$('saveBtn'),share:$('shareBtn'),file:$('fileInput'),title:$('docTitle'),contentViewport:$('contentViewport'),viewport:$('readerStage'),surface:$('readerSurface'),empty:$('emptyState'),tocBtn:$('tocBtn'),bookmarkBtn:$('bookmarkBtn'),searchBtn:$('searchBtn'),appearanceBtn:$('appearanceBtn'),highlightBtn:$('highlightBtn'),pagesBtn:$('pagesBtn'),scrollBtn:$('scrollBtn'),prev:$('prevBtn'),next:$('nextBtn'),progress:$('progressRange'),progressText:$('progressText'),chapterState:$('chapterState'),appearance:$('appearanceSheet'),appearanceClose:$('appearanceClose'),highlight:$('highlightSheet'),highlightClose:$('highlightClose'),highlightClear:$('highlightClear'),annotationCount:$('annotationCount'),toc:$('tocSheet'),tocClose:$('tocClose'),tocList:$('tocList'),fontDown:$('fontDown'),fontUp:$('fontUp'),fontRange:$('fontRange'),fontValue:$('fontValue'),fontFamily:$('fontFamily')};
const frame=NS.LocalAppFrame.create({menuBtn:E.menu,drawer:E.drawer,backdrop:E.backdrop,closeBtn:E.closeMenu,toolbar:E.toolbar});
const session=NS.BookSession.create(),renderer=NS.ReaderRenderer.create(),controls=NS.ReaderControls.create({elements:E,frame,renderer,session});
const navigation=NS.ReaderNavigationTools.create({elements:E,session,reader:controls.api});
const annotationModes=NS.AnnotationModes.create({reader:controls.api,session,elements:E});annotationModes.install();
const bindings=NS.ReaderBindings.create({elements:E,reader:controls.api,navigation:navigation.api});bindings.install();annotationModes.finalizeLegacySelectionUi();
navigation.install();
globalThis.__InkEpubR4=Object.freeze(Object.assign({},controls.api,{navigation:navigation.api,annotationModes:annotationModes.state}));
NS.LocalAppFrame.installToolbarRail(E.toolbar);
})();
