(function(global){
'use strict';
const VERSION='0.20.0';
function decode(value){return String(value||'').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/&apos;|&#39;/gi,"'").replace(/&amp;/gi,'&')}
function normalizePath(value){const parts=[];String(value||'').replace(/\\/g,'/').split('/').forEach(part=>{if(!part||part==='.')return;if(part==='..'){parts.pop();return}parts.push(part)});return parts.join('/')}
function dirname(value){const path=normalizePath(value),index=path.lastIndexOf('/');return index<0?'':path.slice(0,index)}
function stripFragment(value){return String(value||'').split('#')[0].split('?')[0]}
function resolvePath(baseFile,reference){const ref=stripFragment(reference);if(!ref)return normalizePath(baseFile);if(/^[a-z][a-z0-9+.-]*:/i.test(ref))return'';if(ref.startsWith('/'))return normalizePath(ref.slice(1));const base=dirname(baseFile);return normalizePath((base?base+'/':'')+ref)}
function attributes(tag){const result={},regex=/([:\w.-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g;let match;while((match=regex.exec(String(tag||''))))result[match[1].toLowerCase()]=decode(match[2]!==undefined?match[2]:match[3]);return result}
function firstText(xml,name){const regex=new RegExp('<(?:[\\w.-]+:)?'+name+'\\b[^>]*>([\\s\\S]*?)<\\/(?:[\\w.-]+:)?'+name+'>','i'),match=regex.exec(String(xml||''));return match?decode(match[1].replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()):''}
function tags(xml,name){const result=[],regex=new RegExp('<(?:[\\w.-]+:)?'+name+'\\b[^>]*\\/?>','gi');let match;while((match=regex.exec(String(xml||''))))result.push(match[0]);return result}
function parseContainer(xml){const match=/<(?:[\w.-]+:)?rootfile\b[^>]*>/i.exec(String(xml||''));if(!match)throw new Error('EPUB container.xml does not declare a package file.');const path=normalizePath(attributes(match[0])['full-path']);if(!path)throw new Error('EPUB package path is empty.');return path}
function parsePackage(xml,packagePath){const source=String(xml||''),manifest={};tags(source,'item').forEach(tag=>{const a=attributes(tag);if(!a.id||!a.href)return;manifest[a.id]={id:a.id,href:a.href,path:resolvePath(packagePath,a.href),mediaType:a['media-type']||'',properties:String(a.properties||'').split(/\s+/).filter(Boolean)}});const spine=[];tags(source,'itemref').forEach(tag=>{const id=attributes(tag).idref;if(id)spine.push(id)});let coverId='';const meta=/<(?:[\w.-]+:)?meta\b[^>]*\bname\s*=\s*(?:"cover"|'cover')[^>]*>/i.exec(source);if(meta)coverId=attributes(meta[0]).content||'';if(!coverId)Object.keys(manifest).some(id=>manifest[id].properties.includes('cover-image')?(coverId=id,true):false);const sections=spine.map(id=>manifest[id]||null).filter(item=>item&&(/(?:xhtml|html|xml)/i.test(item.mediaType)||/\.(?:xhtml?|html?)$/i.test(item.path)));return{version:VERSION,packagePath:normalizePath(packagePath),title:firstText(source,'title')||'Untitled book',creator:firstText(source,'creator'),language:firstText(source,'language'),manifest,spine,sections,cover:coverId&&manifest[coverId]?manifest[coverId]:null}}
function mediaTypeForPath(path){const ext=String(path||'').toLowerCase().split('.').pop();return{jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',gif:'image/gif',webp:'image/webp',svg:'image/svg+xml'}[ext]||'application/octet-stream'}
global.InkDOSEpubParser=Object.freeze({version:VERSION,decodeEntities:decode,normalizePath,dirname,stripFragment,resolvePath,parseAttributes:attributes,parseContainer,parsePackage,mediaTypeForPath});
})(typeof window!=='undefined'?window:globalThis);
