(function(global){'use strict';
const NS=global.InkDOS2PdfP4=global.InkDOS2PdfP4||{},$=id=>document.getElementById(id);
function loadScript(src,test){if(test?.())return Promise.resolve();return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('PDF_LOCAL_ASSET_LOAD_FAILED: '+src));document.head.appendChild(s)})}
function afterIdle(timeout=700){return new Promise(resolve=>{if(typeof global.requestIdleCallback==='function')global.requestIdleCallback(()=>resolve(),{timeout});else setTimeout(resolve,90)})}
async function loadReaderTools(){await loadScript('features/reader/reader-runtime.js',()=>!!NS.ReaderRuntime);await loadScript('ui/reader-tools.js',()=>!!NS.ReaderTools)}
async function loadStabilityInfrastructure(){await Promise.all([loadScript('runtime/commands/command-registry.js',()=>!!NS.CommandRegistry),loadScript('ui/command-bindings.js',()=>!!NS.CommandBindings),loadScript('ui/toolbar-rail.js',()=>!!NS.ToolbarRail),loadScript('ui/mode-bindings.js',()=>!!NS.ModeBindings&&!!NS.AnnotationModes)])}
async function loadPageTools(){if(!document.querySelector('link[data-pdf-page-tools]')){const l=document.createElement('link');l.rel='stylesheet';l.href='ui/page-tools.css';l.dataset.pdfPageTools='1';document.head.appendChild(l)}await Promise.all([loadScript('vendor/jszip.min.js',()=>!!global.JSZip),loadScript('vendor/pdf-lib/pdf-lib.min.js',()=>!!global.PDFLib?.PDFDocument)]);await Promise.all([loadScript('engine/page-tools-engine.js',()=>!!NS.PageToolsEngine),loadScript('features/page-tools/page-tools-runtime.js',()=>!!NS.PageToolsRuntime)]);await Promise.all([loadScript('features/page-tools/actions/move-page.js',()=>!!NS.PageMoveAction),loadScript('features/page-tools/actions/rotate-page.js',()=>!!NS.PageRotateAction),loadScript('features/page-tools/actions/delete-page.js',()=>!!NS.PageDeleteAction),loadScript('features/page-tools/actions/extract-page.js',()=>!!NS.PageExtractAction),loadScript('features/page-tools/actions/split-pdf.js',()=>!!NS.PageSplitAction),loadScript('features/page-tools/actions/merge-pdfs.js',()=>!!NS.PageMergeAction)]);await loadScript('ui/page-tools.js',()=>!!NS.PageTools)}
async function boot(){
 await loadStabilityInfrastructure();NS.ToolbarRail.install($('editbar'));NS.PdfWorker.configure();
 const session=new NS.PdfSession(),chrome=NS.ChromeController.create({session}),scheduler=new NS.PageScheduler(9),registry=NS.CommandRegistry.create();
 let commands=null,readerTools=null,pageTools=null,editingActive=false,editingReady=false,editingLoading=false,editingLoadPromise=null,resumeEditingAfterReplace=false,authorizedUnload=false;
 const editBtn=$('editModeBtn'),editLabel=$('editModeLabel');
 const readerProxy=Object.freeze({resetDocument:()=>readerTools?.resetDocument(),syncEnabled:()=>readerTools?.syncEnabled()});
 const pageProxy=Object.freeze({resetDocument:()=>pageTools?.resetDocument(),syncEnabled:()=>pageTools?.syncEnabled()});
 const editor=new NS.PdfjsEditorAdapter({container:$('contentViewport'),viewer:$('pdfStack'),session,chrome,onState:()=>commands?.syncEditor()}),pageLayers=new NS.PdfjsPageLayers({editor}),extensions=new NS.ReviewAnnotations({editor,session,chrome,registry});
 let resolveFirstRender=null;const firstRender=new Promise(resolve=>{resolveFirstRender=resolve});
 let layout=null;
 function syncEditButton(){if(!editBtn)return;const active=!!session.active,loading=active&&editingLoading;editBtn.disabled=!active||loading;editBtn.dataset.editState=!active?'empty':loading?'loading':editingReady?'ready':'available';editBtn.classList.toggle('active',editingActive);editBtn.setAttribute('aria-pressed',String(editingActive));editBtn.setAttribute('aria-busy',String(loading));editBtn.title=!active?'Open a PDF to edit':loading?'Loading editing tools…':editingActive?'Finish editing':'Edit PDF';if(editLabel)editLabel.textContent=editingActive?'Done':loading?'Loading…':'Edit'}
 async function ensureEditingTools(){if(editingReady)return true;if(editingLoadPromise)return editingLoadPromise;editingLoading=true;syncEditButton();editingLoadPromise=(async()=>{try{await loadPageTools();pageTools=NS.PageTools.create({session,getDocument:()=>fileOpen.pdfDocument,fileOpen,editor,chrome,layout,navigation,registry});pageTools.install();if(session.active){pageTools.resetDocument();pageTools.syncEnabled()}editingReady=true;return true}catch(e){console.error('Deferred PDF page tools failed to load',e);chrome.status('Editing tools failed to load');return false}finally{editingLoading=false;editingLoadPromise=null;syncEditButton()}})();return editingLoadPromise}
 async function hydrateView(v){if(!editingActive||!v?.record||!v?.policy||!v?.shell?.isConnected)return;const info={pageNumber:v.n,shell:v.shell,record:v.record,policy:v.policy,viewport:v.record.page.getViewport({scale:v.policy.scale,rotation:v.policy.rotation})};await pageLayers.onPageRendered(info);extensions.onPageRendered(info)}
 async function hydrateEditingLayers(){if(!editingActive||!layout)return;const current=layout.views.get(layout.currentPage);if(current)await hydrateView(current);await Promise.all([...layout.views.values()].filter(v=>v!==current).map(v=>hydrateView(v)))}
 layout=new NS.PageLayout({viewport:$('contentViewport'),stack:$('pdfStack'),onPageChange:n=>commands?.syncPage(),onScaleChange:s=>editor.setScale(s),onPageRendered:async info=>{if(resolveFirstRender){resolveFirstRender(info);resolveFirstRender=null}if(!editingActive)return;await pageLayers.onPageRendered(info);extensions.onPageRendered(info)},onPageUnmount:n=>{extensions.onPageUnmount(n);pageLayers.onPageUnmount(n)}});
 const adapter=new NS.ContentViewportAdapter($('contentViewport'),m=>layout.setMetrics(m)),zoom=new NS.ZoomController(layout,()=>{}),zoomControls=NS.ZoomControls.create({zoom,select:$('zoomSelect')}),navigation=NS.NavigationController.create({layout,chrome,anchor:$('navPanelBtn'),registry}),modeController=NS.ModeController.create({editor,extensions,pageLayers,chrome}),modeBindings=NS.ModeBindings.create({registry,modeController}),annotationModes=NS.AnnotationModes.create({extensions,modeController,chrome});
 const fileOpen=NS.FileOpenController.create({session,fileInput:$('fileInput'),scheduler,layout,chrome,prepareToReplace:()=>{editor.commit();return editor.doc?.annotationStorage.serializable.hash},canReplace:()=>!save.saving,onBeforeReplace:async info=>{resumeEditingAfterReplace=!!info?.internal&&editingActive;editingActive=false;modeController.setMode('view');readerProxy.resetDocument();pageProxy.resetDocument();layout.clearDocument();extensions.setDocument(null);pageLayers.setDocument(null);navigation.close();syncEditButton()},onDocumentOpened:async info=>{const resume=!!info?.internal&&resumeEditingAfterReplace&&editingReady;resumeEditingAfterReplace=false;navigation.setDocument(info.pdfDocument,info.pageCount).catch(()=>{});readerProxy.resetDocument();readerProxy.syncEnabled();pageProxy.resetDocument();pageProxy.syncEnabled();if(resume){pageLayers.setDocument(info.pdfDocument);extensions.setDocument(info.pdfDocument);editingActive=true;modeController.setMode('annotate');queueMicrotask(()=>hydrateEditingLayers().catch(e=>console.warn('PDF edit layer restore failed',e)))}else{editingActive=false;extensions.setDocument(null);pageLayers.setDocument(null);modeController.setMode('view')}syncEditButton()}});
 const save=NS.SaveController.create({session,getDocument:()=>fileOpen.pdfDocument,editor,chrome});
 commands=NS.CommandController.create({session,chrome,fileOpen,save,layout,editor,navigation,modeController,readerTools:readerProxy,pageTools:pageProxy,registry,extensions});
 NS.Appearance.install();fileOpen.install();zoomControls.install();navigation.install();extensions.install();modeController.install();modeBindings.install();commands.install();
 editBtn?.addEventListener('click',async()=>{if(!session.active||editingLoading)return;if(editingActive){editingActive=false;modeController.setMode('view');syncEditButton();return}if(!(await ensureEditingTools()))return;pageLayers.setDocument(fileOpen.pdfDocument);extensions.setDocument(fileOpen.pdfDocument);editingActive=true;modeController.setMode('annotate');syncEditButton();chrome.status('Preparing edit layers…');try{await hydrateEditingLayers();chrome.status('Edit ready')}catch(e){console.error(e);chrome.status('Edit layers failed')}});
 global.InkDOSFileLaunch?.setOpenHandler?.(async file=>{if(!(await commands.authorizeReplacement('open')))return false;return !!(await fileOpen.openFile(file,{authorized:true}))});
 annotationModes.install();global.addEventListener('beforeunload',e=>{authorizedUnload=commands.consumeAuthorizedUnload();if(authorizedUnload){authorizedUnload=false;return}if(commands.hasUnsavedWork()){e.preventDefault();e.returnValue=''}});
 adapter.measure();chrome.title();chrome.dirty();chrome.page(1,0);syncEditButton();
 let firstContentRendered=false;
 if(session.active){
  firstContentRendered=await Promise.race([firstRender.then(()=>true),new Promise(resolve=>setTimeout(()=>resolve(false),2500))]);
  if(!firstContentRendered){await afterIdle(650);await ensureEditingTools()}
 }
 // Empty startup has no document that can resolve firstRender. Keep readiness independent
 // from that document-only signal; direct-launch still follows the content-first path above.
 global.__inkdosPdfEmptyStartupReady=!session.active;
 global.__inkdosPdfFirstRenderState=()=>Object.freeze({sessionActive:!!session.active,firstContentRendered,emptyStartupReady:!!global.__inkdosPdfEmptyStartupReady});
 await afterIdle(900);
 try{await loadReaderTools();readerTools=NS.ReaderTools.create({session,getDocument:()=>fileOpen.pdfDocument,layout,chrome,registry,canRotate:()=>true});readerTools.install();if(session.active){readerTools.resetDocument();readerTools.syncEnabled()}}catch(e){console.error('Deferred PDF reader tools failed to load',e)}
 NS.ReaderCompletionDebug=Object.freeze({get readerTools(){return readerTools},get pageTools(){return pageTools},layout});
 NS.PdfStabilityDebug=Object.freeze({session,editor,pageLayers,extensions,layout,navigation,modeController,modeBindings,annotationModes,fileOpen,save,get readerTools(){return readerTools},get pageTools(){return pageTools},commands,registry,get editingActive(){return editingActive},get editingReady(){return editingReady},get editingLoading(){return editingLoading}})
}
boot().catch(e=>{console.error(e);const status=$('statusText');if(status)status.textContent='PDF workspace failed to initialize'});
})(globalThis);
