(function(global){'use strict';
const SPEC=Object.freeze({
 title:'Plain Text',
 intro:'Use this guide to edit TXT/XML files, control the editor view, work with outlines, and save a local copy.',
 sections:[
  ['Getting started','<p>Create a new text document or open a TXT/XML file from the hamburger menu. The editor keeps the document as plain text rather than applying rich-text formatting.</p>'],
  ['Editing','<p>Type directly in the editor. Undo and redo track text changes. Select All, Copy, Paste, indentation, and list/outline controls operate on the current text selection or line.</p>'],
  ['Find','<p>Use Find to search the current document. Previous and Next move between matches, and the status indicator shows the active match state.</p>'],
  ['View controls','<p>Wrap changes whether long lines wrap visually. The text-size controls change only the editor view; they do not add font information to the TXT/XML file.</p>'],
  ['Lists and outlines','<p>The list tool inserts plain-text outline prefixes such as dashes, bullets, or numbered patterns. Because the file remains plain text, these markers are stored as normal characters.</p>'],
  ['Encoding and line endings','<p>The status bar shows the active encoding and line-ending mode. Keep these indicators in mind when working with files shared between operating systems or XML tooling.</p>'],
  ['Saving and sharing','<p>Save copy exports the current text as a local file. Share uses the available platform sharing path when supported. The source file is not silently overwritten.</p>']
 ]
});
const ICON='<svg viewBox="0 0 24 24" aria-hidden="true" data-icon="CircleHelp"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 1 1 5.83 1c0 2-3 2-3 4"/><path d="M12 17h.01"/></svg>';
function styles(){if(document.getElementById('inkdosAppHelpStyles'))return;const s=document.createElement('style');s.id='inkdosAppHelpStyles';s.textContent='.inkdos-help-menu-list{margin-top:8px;padding-top:8px;border-top:1px solid var(--line,var(--frame-line,#d7dce2))}.inkdos-help-dialog{width:min(720px,calc(100vw - 28px));max-height:min(82vh,760px);padding:0;border:1px solid var(--line,var(--frame-line,#d7dce2));border-radius:16px;background:var(--chrome,var(--frame-chrome,#fff));color:var(--text,var(--frame-text,#202124));box-shadow:0 24px 70px rgba(0,0,0,.28)}.inkdos-help-dialog::backdrop{background:rgba(20,24,31,.48)}.inkdos-help-shell{display:grid;grid-template-rows:auto minmax(0,1fr);max-height:min(82vh,760px)}.inkdos-help-head{display:flex;align-items:center;gap:12px;padding:16px 18px;border-bottom:1px solid var(--line,var(--frame-line,#d7dce2));background:var(--chrome,var(--frame-chrome,#fff));position:sticky;top:0;z-index:1}.inkdos-help-head h2{font:600 18px/1.2 system-ui,sans-serif;margin:0;flex:1}.inkdos-help-close{width:34px;height:34px;border:0;border-radius:10px;background:transparent;color:inherit;font-size:24px;cursor:pointer}.inkdos-help-close:hover,.inkdos-help-close:focus-visible{background:var(--toolbar-hover,var(--frame-hover,rgba(60,64,67,.08)));outline:none}.inkdos-help-body{overflow:auto;padding:18px}.inkdos-help-intro{margin:0 0 16px;color:var(--muted,var(--frame-muted,#5f6368));line-height:1.5}.inkdos-help-card{padding:14px 0;border-top:1px solid var(--line,var(--frame-line,#d7dce2))}.inkdos-help-card:first-of-type{border-top:0}.inkdos-help-card h3{margin:0 0 8px;font:600 15px/1.3 system-ui,sans-serif}.inkdos-help-card p{margin:7px 0;line-height:1.55}@media(max-width:560px){.inkdos-help-dialog{width:calc(100vw - 16px);max-height:88vh}.inkdos-help-shell{max-height:88vh}.inkdos-help-body{padding:14px}}';(document.head||document.documentElement).appendChild(s)}
function install(){if(document.querySelector('[data-inkdos-help-entry]'))return;const drawer=document.querySelector('aside.drawer');if(!drawer)return;styles();const list=document.createElement('div');list.className='menu-list inkdos-help-menu-list';list.innerHTML='<button class="menu-item" type="button" aria-haspopup="dialog" data-inkdos-help-entry>'+ICON+'<span>Help</span><span class="hint"></span></button>';drawer.appendChild(list);const entry=list.querySelector('[data-inkdos-help-entry]'),dialog=document.createElement('dialog');dialog.className='inkdos-help-dialog';dialog.setAttribute('data-inkdos-help-dialog','');dialog.setAttribute('aria-label',SPEC.title+' Help');dialog.innerHTML='<div class="inkdos-help-shell"><header class="inkdos-help-head"><h2>'+SPEC.title+' Help</h2><button class="inkdos-help-close" type="button" aria-label="Close Help" data-inkdos-help-close>×</button></header><div class="inkdos-help-body"><p class="inkdos-help-intro">'+SPEC.intro+'</p>'+SPEC.sections.map(x=>'<section class="inkdos-help-card"><h3>'+x[0]+'</h3>'+x[1]+'</section>').join('')+'</div></div>';document.body.appendChild(dialog);const close=()=>{if(dialog.open&&typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open')};entry.addEventListener('click',()=>{drawer.querySelector('.close-btn')?.click();if(dialog.open)return;if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','')});dialog.querySelector('[data-inkdos-help-close]').addEventListener('click',close);dialog.addEventListener('click',e=>{if(e.target===dialog)close()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
global.InkDOSAppHelp=Object.freeze({title:SPEC.title,install});
})(globalThis);
