(function(global){'use strict';
const NS=global.InkDOS2Presentations=global.InkDOS2Presentations||{};
const DEFAULT_W=12192000,DEFAULT_H=6858000;let seq=0;
const DEFAULT_THEME=Object.freeze({name:'InkDOS',part:'ppt/theme/theme1.xml',colorSchemeName:'InkDOS',fontSchemeName:'InkDOS',colors:Object.freeze({dk1:'#000000',lt1:'#FFFFFF',dk2:'#1F497D',lt2:'#EEECE1',accent1:'#DF542C',accent2:'#4F81BD',accent3:'#9BBB59',accent4:'#8064A2',accent5:'#4BACC6',accent6:'#F79646',hlink:'#0000FF',folHlink:'#800080'}),major:'Aptos Display',minor:'Aptos'});
const uid=p=>`${p}-${Date.now().toString(36)}-${(++seq).toString(36)}`;
const clone=v=>JSON.parse(JSON.stringify(v));
const sane=(v,f)=>Number.isFinite(Number(v))?Number(v):f;
function cloneTheme(input=DEFAULT_THEME){const source=input&&typeof input==='object'?input:DEFAULT_THEME;return {name:String(source.name||DEFAULT_THEME.name),part:String(source.part||DEFAULT_THEME.part),colorSchemeName:String(source.colorSchemeName||DEFAULT_THEME.colorSchemeName),fontSchemeName:String(source.fontSchemeName||DEFAULT_THEME.fontSchemeName),colors:{...DEFAULT_THEME.colors,...(source.colors||{})},major:String(source.major||DEFAULT_THEME.major),minor:String(source.minor||DEFAULT_THEME.minor)}}
function normalizeParagraphs(input,text,fallback={}){
  if(Array.isArray(input)&&input.length){return input.map(p=>({
    align:['left','center','right','justify'].includes(p.align)?p.align:(fallback.align||'left'),
    level:Math.max(0,Math.min(8,sane(p.level,0))),
    bullet:p.bullet||null,
    lineSpacing:sane(p.lineSpacing,1.0),lineSpacingPt:p.lineSpacingPt==null?null:sane(p.lineSpacingPt,null),spaceBeforePt:sane(p.spaceBeforePt,0),spaceAfterPt:sane(p.spaceAfterPt,0),
    runs:Array.isArray(p.runs)&&p.runs.length?p.runs.map(r=>({text:String(r.text??''),fontSizePt:sane(r.fontSizePt,fallback.fontSizePt||24),bold:!!r.bold,italic:!!r.italic,underline:!!r.underline,color:r.color||fallback.color||null,fontFamily:r.fontFamily||fallback.fontFamily||null,charSpacingPt:sane(r.charSpacingPt,fallback.charSpacingPt||0)})):[{text:'',fontSizePt:fallback.fontSizePt||24,bold:!!fallback.bold,italic:!!fallback.italic,underline:false,color:fallback.color||null,fontFamily:fallback.fontFamily||null,charSpacingPt:sane(fallback.charSpacingPt,0)}]
  }))}
  return String(text??'Text').split('\n').map(line=>({align:fallback.align||'left',level:0,bullet:null,lineSpacing:1,lineSpacingPt:null,spaceBeforePt:0,spaceAfterPt:0,runs:[{text:line,fontSizePt:fallback.fontSizePt||24,bold:!!fallback.bold,italic:!!fallback.italic,underline:false,color:fallback.color||null,fontFamily:fallback.fontFamily||null,charSpacingPt:sane(fallback.charSpacingPt,0)}]}));
}
function plainText(paragraphs){return (paragraphs||[]).map(p=>(p.runs||[]).map(r=>r.text||'').join('')).join('\n')}
function textSignature(o={}){return JSON.stringify({text:String(o.text??''),paragraphs:o.paragraphs||[],fontSizePt:sane(o.fontSizePt,24),bold:!!o.bold,italic:!!o.italic,align:o.align||'left',color:o.color||null,fontFamily:o.fontFamily||null,verticalAlign:o.verticalAlign||'top',marginLeftEmu:sane(o.marginLeftEmu,91440),marginRightEmu:sane(o.marginRightEmu,91440),marginTopEmu:sane(o.marginTopEmu,45720),marginBottomEmu:sane(o.marginBottomEmu,45720),wrap:o.wrap||'square',autoFit:o.autoFit||'none',autoFitScale:sane(o.autoFitScale,1),x:sane(o.x,0),y:sane(o.y,0),w:sane(o.w,0),h:sane(o.h,0),rotation:sane(o.rotation,0),fill:o.fill||null,line:o.line||null});}
function textObject(input={}){
  const base={fontSizePt:sane(input.fontSizePt,28),bold:!!input.bold,italic:!!input.italic,align:['left','center','right','justify'].includes(input.align)?input.align:'left',color:input.color||null,fontFamily:input.fontFamily||null};
  const paragraphs=normalizeParagraphs(input.paragraphs,input.text,base);
  return {id:input.id||uid('obj'),type:'text',x:sane(input.x,914400),y:sane(input.y,914400),w:sane(input.w,10058400),h:sane(input.h,1371600),text:plainText(paragraphs),paragraphs,fontSizePt:base.fontSizePt,bold:base.bold,italic:base.italic,align:base.align,color:base.color,fontFamily:base.fontFamily,placeholder:input.placeholder||null,placeholderIdx:input.placeholderIdx??null,rotation:sane(input.rotation,0),verticalAlign:input.verticalAlign||'top',marginLeftEmu:sane(input.marginLeftEmu,91440),marginRightEmu:sane(input.marginRightEmu,91440),marginTopEmu:sane(input.marginTopEmu,45720),marginBottomEmu:sane(input.marginBottomEmu,45720),wrap:input.wrap||'square',autoFit:input.autoFit||'none',autoFitScale:Math.max(.35,Math.min(1.5,sane(input.autoFitScale,1))),fill:input.fill||null,line:input.line||null,opacity:Math.max(0,Math.min(1,sane(input.opacity,1))),richSource:input.richSource||null,sourceRef:input.sourceRef?clone(input.sourceRef):null,sourceSignature:input.sourceSignature||null,importedUnmapped:!!input.importedUnmapped};
}
function imageObject(input={}){return {id:input.id||uid('img'),type:'image',x:sane(input.x,914400),y:sane(input.y,914400),w:sane(input.w,3657600),h:sane(input.h,2057400),src:String(input.src||''),mime:input.mime||'image/png',crop:input.crop||null,rotation:sane(input.rotation,0),opacity:Math.max(0,Math.min(1,sane(input.opacity,1))),line:input.line||null,sourceRef:input.sourceRef?clone(input.sourceRef):null,importedUnmapped:!!input.importedUnmapped};}
function shapeObject(input={}){return {id:input.id||uid('shape'),type:'shape',shapeType:input.shapeType||'rect',x:sane(input.x,914400),y:sane(input.y,914400),w:sane(input.w,3657600),h:sane(input.h,2057400),fill:input.fill||null,line:input.line||null,rotation:sane(input.rotation,0),opacity:Math.max(0,Math.min(1,sane(input.opacity,1))),sourceRef:input.sourceRef?clone(input.sourceRef):null,importedUnmapped:!!input.importedUnmapped};}
function tableCell(input={}){const paragraphs=normalizeParagraphs(input.paragraphs,input.text||'',{fontSizePt:sane(input.fontSizePt,18),align:input.align||'left',color:input.color||null,fontFamily:input.fontFamily||null});return {text:plainText(paragraphs),paragraphs,fill:input.fill||null,borders:clone(input.borders||{}),verticalAlign:input.verticalAlign||'middle',marginLeftEmu:sane(input.marginLeftEmu,91440),marginRightEmu:sane(input.marginRightEmu,91440),marginTopEmu:sane(input.marginTopEmu,45720),marginBottomEmu:sane(input.marginBottomEmu,45720),colSpan:Math.max(1,sane(input.colSpan,1)),rowSpan:Math.max(1,sane(input.rowSpan,1)),hMerge:!!input.hMerge,vMerge:!!input.vMerge};}
function tableObject(input={}){const columns=(input.columns||[]).map(v=>Math.max(1,sane(v,1))),rows=(input.rows||[]).map(row=>({heightEmu:Math.max(1,sane(row.heightEmu,1)),cells:(row.cells||[]).map(tableCell)}));return {id:input.id||uid('table'),type:'table',x:sane(input.x,914400),y:sane(input.y,914400),w:sane(input.w,5486400),h:sane(input.h,2743200),rotation:sane(input.rotation,0),opacity:Math.max(0,Math.min(1,sane(input.opacity,1))),columns,rows,styleId:String(input.styleId||''),sourceRef:input.sourceRef?clone(input.sourceRef):null,importedUnmapped:input.importedUnmapped!==false,pptP2Imported:!!input.pptP2Imported};}
function blankSlide(index=1,{widthEmu=DEFAULT_W,heightEmu=DEFAULT_H,theme=DEFAULT_THEME}={}){return {id:uid('slide'),slideNumber:index,widthEmu,heightEmu,background:'#ffffff',theme:cloneTheme(theme),sourcePart:null,duplicateSourcePart:null,objects:[textObject({x:914400,y:685800,w:10058400,h:1100000,text:index===1?'Presentation title':'Slide title',fontSizePt:34,bold:true,align:'center',placeholder:'title'}),textObject({x:1219200,y:2057400,w:9753600,h:2743200,text:index===1?'Tap a text box to edit.':'Add content here',fontSizePt:22,align:'left',placeholder:'body'})]}}
function markImportedUnmapped(slides,kind){if(kind!=='pptx')return;for(const slide of slides||[])for(const o of slide.objects||[])if((o.type==='image'||o.type==='shape')&&!o.sourceRef)o.importedUnmapped=true}
function ensureText(slide,placeholder,text){let o=slide.objects.find(x=>x.type==='text'&&x.placeholder===placeholder);if(!o){o=textObject({text,placeholder,fontSizePt:placeholder==='title'?32:22});slide.objects.push(o)}return o}
function applyBasicLayout(slide,name){if(!slide)return false;const W=slide.widthEmu,H=slide.heightEmu,title=ensureText(slide,'title','Slide title'),body=ensureText(slide,'body','Add content here');title.x=W*.08;title.y=H*.06;title.w=W*.84;title.h=H*.16;title.fontSizePt=name==='section'?36:32;for(const p of title.paragraphs||[])for(const r of p.runs||[])r.fontSizePt=title.fontSizePt;if(name==='twoContent'){body.x=W*.07;body.y=H*.27;body.w=W*.4;body.h=H*.58;let second=slide.objects.find(x=>x.type==='text'&&x.placeholder==='body2');if(!second){second=textObject({text:'Second content',placeholder:'body2',fontSizePt:22});slide.objects.push(second)}second.x=W*.53;second.y=H*.27;second.w=W*.4;second.h=H*.58}else if(name==='section'){body.x=W*.16;body.y=H*.48;body.w=W*.68;body.h=H*.18;body.align='center';for(const p of body.paragraphs||[])p.align='center'}else{body.x=W*.1;body.y=H*.27;body.w=W*.8;body.h=H*.58}return true}
class PresentationSession{
 constructor(){this.sessionId=uid('session');this.operationId=0;this.revision=0;this.fileName='Untitled.pptx';this.sourceKind='none';this.sourceBytes=new Uint8Array();this.sourceSlideParts=[];this.sourceBaselineSlides=[];this.slides=[];this.currentSlideId=null;this.dirty=false;this.compatibility=[]}
 beginOperation(){return ++this.operationId}
 replaceCandidate(candidate,op){if(op!==this.operationId)return false;this.fileName=candidate.fileName||'Presentation.pptx';this.sourceKind=candidate.sourceKind||'pptx';this.sourceBytes=new Uint8Array(candidate.sourceBytes||[]);this.slides=clone(candidate.slides||[]);markImportedUnmapped(this.slides,this.sourceKind);this.sourceSlideParts=clone(candidate.sourceSlideParts||this.slides.map(s=>s.sourcePart).filter(Boolean));this.sourceBaselineSlides=clone(this.slides);this.currentSlideId=this.slides[0]?.id||null;this.compatibility=clone(candidate.compatibility||[]);this.dirty=false;this.revision++;this.renumber();return true}
 resetNew(){this.operationId++;this.sourceKind='new';this.sourceBytes=new Uint8Array();this.sourceSlideParts=[];this.sourceBaselineSlides=[];this.fileName='Untitled.pptx';this.slides=[blankSlide(1)];this.currentSlideId=this.slides[0].id;this.compatibility=[];this.dirty=false;this.revision++;this.renumber()}
 renumber(){this.slides.forEach((s,i)=>s.slideNumber=i+1)}
 get active(){return this.sourceKind!=='none'&&this.slides.length>0&&!!this.currentSlideId&&this.slides.some(s=>s.id===this.currentSlideId)}
 get currentIndex(){const i=this.slides.findIndex(s=>s.id===this.currentSlideId);return i<0?0:i}
 get currentSlide(){return this.slides[this.currentIndex]||null}
 setCurrentByIndex(index){if(!this.slides.length)return false;const i=Math.max(0,Math.min(this.slides.length-1,Number(index)||0));this.currentSlideId=this.slides[i].id;return true}
 setCurrentById(id){if(!this.slides.some(s=>s.id===id))return false;this.currentSlideId=id;return true}
 markDirty(){this.dirty=true;this.revision++}
 snapshot(){return {fileName:this.fileName,sourceKind:this.sourceKind,slides:clone(this.slides),currentSlideId:this.currentSlideId,dirty:this.dirty,compatibility:clone(this.compatibility)}}
 restore(snapshot,{dirty=true}={}){this.fileName=snapshot.fileName;this.sourceKind=snapshot.sourceKind;this.slides=clone(snapshot.slides);this.currentSlideId=this.slides.some(s=>s.id===snapshot.currentSlideId)?snapshot.currentSlideId:this.slides[0]?.id||null;this.compatibility=clone(snapshot.compatibility||[]);this.dirty=dirty;this.renumber();this.revision++}
 addSlide(afterIndex=this.currentIndex){if(!this.active)return null;const slide=blankSlide(1,{widthEmu:this.currentSlide?.widthEmu||DEFAULT_W,heightEmu:this.currentSlide?.heightEmu||DEFAULT_H,theme:this.currentSlide?.theme||DEFAULT_THEME});this.slides.splice(Math.min(this.slides.length,afterIndex+1),0,slide);this.renumber();this.currentSlideId=slide.id;return slide}
 duplicateCurrent(){const src=this.currentSlide;if(!src)return null;const slide=clone(src);slide.id=uid('slide');slide.duplicateSourcePart=this.sourceKind==='pptx'?(src.sourcePart||src.duplicateSourcePart||null):null;slide.sourcePart=null;slide.objects=slide.objects.map(o=>({...o,id:uid(o.type==='image'?'img':o.type==='shape'?'shape':o.type==='table'?'table':'obj')}));this.slides.splice(this.currentIndex+1,0,slide);this.renumber();this.currentSlideId=slide.id;return slide}
 deleteCurrent(){if(this.slides.length<=1)return false;const i=this.currentIndex;this.slides.splice(i,1);this.renumber();this.currentSlideId=this.slides[Math.min(i,this.slides.length-1)].id;return true}
 moveCurrent(delta){if(!this.active)return false;const from=this.currentIndex,to=Math.max(0,Math.min(this.slides.length-1,from+(Number(delta)||0)));if(to===from)return false;const [slide]=this.slides.splice(from,1);this.slides.splice(to,0,slide);this.renumber();this.currentSlideId=slide.id;return true}
 addText(){const slide=this.currentSlide;if(!slide)return null;const o=textObject({x:slide.widthEmu*.18,y:slide.heightEmu*.32,w:slide.widthEmu*.64,h:slide.heightEmu*.18,text:'New text',fontSizePt:24,align:'center'});slide.objects.push(o);return o}
 addImage({src,mime='image/png',widthEmu=null,heightEmu=null}={}){const slide=this.currentSlide;if(!slide||!src)return null;const w=Math.min(slide.widthEmu*.55,Math.max(slide.widthEmu*.18,sane(widthEmu,slide.widthEmu*.42))),h=Math.min(slide.heightEmu*.62,Math.max(slide.heightEmu*.18,sane(heightEmu,slide.heightEmu*.42))),o=imageObject({src,mime,x:(slide.widthEmu-w)/2,y:(slide.heightEmu-h)/2,w,h});slide.objects.push(o);return o}
 addShape(shapeType='rect'){const slide=this.currentSlide;if(!slide)return null;const o=shapeObject({shapeType:['rect','roundRect','ellipse','line'].includes(shapeType)?shapeType:'rect',x:slide.widthEmu*.28,y:slide.heightEmu*.32,w:slide.widthEmu*.44,h:shapeType==='line'?12700:slide.heightEmu*.28,fill:shapeType==='line'?null:'#DCE6F5',line:{color:'#5B6B82',widthEmu:19050}});slide.objects.push(o);return o}
 applyLayout(name='titleContent'){return applyBasicLayout(this.currentSlide,['titleContent','twoContent','section'].includes(name)?name:'titleContent')}
 acceptConfirmedPptx(bytes,receipt={}){if(this.sourceKind!=='pptx')return false;this.sourceBytes=new Uint8Array(bytes||[]);const slideMap=new Map((receipt.slideMappings||[]).map(x=>[x.slideId,x.slidePart]));for(const slide of this.slides){if(slideMap.has(slide.id))slide.sourcePart=slideMap.get(slide.id);delete slide.duplicateSourcePart;for(const obj of slide.objects||[])if(obj.sourceRef&&slide.sourcePart)obj.sourceRef.slidePart=slide.sourcePart}for(const mapping of receipt.objectMappings||receipt.insertedMappings||[]){const slide=this.slides.find(s=>s.id===mapping.slideId),obj=slide?.objects.find(o=>o.id===mapping.objectId);if(obj){obj.sourceRef={slidePart:mapping.slidePart,shapeId:String(mapping.shapeId),editable:true};obj.importedUnmapped=false}}for(const slide of this.slides)for(const obj of slide.objects||[]){if(obj.type==='text'&&obj.sourceRef)obj.sourceSignature=textSignature(obj);if(obj.type==='table')delete obj.pptP2StructureOps}this.sourceSlideParts=this.slides.map(s=>s.sourcePart).filter(Boolean);this.sourceBaselineSlides=clone(this.slides);this.dirty=false;this.revision++;return true}
}
NS.PresentationSession=PresentationSession;
NS.PresentationModel=Object.freeze({DEFAULT_W,DEFAULT_H,DEFAULT_THEME,cloneTheme,textObject,imageObject,shapeObject,tableCell,tableObject,blankSlide,clone,plainText,normalizeParagraphs,textSignature,applyBasicLayout});
})(globalThis);