(function(g){'use strict';
const NS=g.InkDOS2=g.InkDOS2||{};
const LIST_MARKERS=Object.freeze({dash:Object.freeze(['-','•','▪']),bullet:Object.freeze(['•','◦','▪'])});
function parseListLine(line){const tabs=(String(line).match(/^\t*/)||[''])[0];const rest=String(line).slice(tabs.length);let m=rest.match(/^(\d+)\.\s+(.*)$/u);if(m)return {indent:tabs.length,marker:m[1]+'.',kind:'number',content:m[2],prefixLength:tabs.length+m[1].length+2};m=rest.match(/^([a-z])\.\s+(.*)$/iu);if(m)return {indent:tabs.length,marker:m[1].toLowerCase()+'.',kind:'alpha',content:m[2],prefixLength:tabs.length+3};m=rest.match(/^([-•◦▪])\s+(.*)$/u);if(m)return {indent:tabs.length,marker:m[1],kind:m[1]==='-'?'dash':m[1]==='•'?'bullet':m[1]==='◦'?'hollow':'square',content:m[2],prefixLength:tabs.length+2};return {indent:tabs.length,marker:null,kind:null,content:rest,prefixLength:tabs.length}}
function directFamily(p){if(!p.marker)return null;if(p.kind==='number'||p.kind==='alpha')return 'number';if(p.kind==='hollow')return 'bullet';if(p.indent===0&&p.kind==='dash')return 'dash';if(p.indent===0&&p.kind==='bullet')return 'bullet';return null}
function inferFamily(lines,index,p=parseListLine(lines[index])){const direct=directFamily(p);if(direct)return direct;for(let i=index-1;i>=0;i--){const q=parseListLine(lines[i]);if(!lines[i].trim())break;if(q.indent<p.indent&&q.marker){const fam=directFamily(q);if(fam)return fam;if(q.kind==='number'||q.kind==='alpha')return 'number'}if(q.indent===0&&!q.marker)break}if(p.kind==='bullet')return p.indent>0?'dash':'bullet';if(p.kind==='square')return 'bullet';return 'dash'}
function alphaMarker(n){const x=Math.max(1,n);return String.fromCharCode(96+((x-1)%26)+1)+'.'}
function ordinalAt(lines,index,level){let count=0;for(let i=index-1;i>=0;i--){const p=parseListLine(lines[i]);if(!lines[i].trim())break;const fam=inferFamily(lines,i,p);if(fam!=='number'){if(p.indent<=level)break;continue}if(level===0){if(p.indent===0)count++;else if(p.indent<level)break}else if(level===1){if(p.indent===0)break;if(p.indent===1)count++}}return count+1}
function markerFor(family,level,lines,index){const l=Math.max(0,Math.min(2,level));if(family==='number'){if(l===0)return ordinalAt(lines,index,0)+'.';if(l===1)return alphaMarker(ordinalAt(lines,index,1));return '-'}return LIST_MARKERS[family][l]}
function renderListLine(indent,family,content,lines,index){const level=Math.max(0,Math.min(2,indent));return '\t'.repeat(level)+markerFor(family,level,lines,index)+' '+content}
function normalizeNumberOutline(lines,anchorIndex){let start=anchorIndex,end=anchorIndex;while(start>0&&lines[start-1].trim()&&inferFamily(lines,start-1,parseListLine(lines[start-1]))==='number')start--;while(end+1<lines.length&&lines[end+1].trim()&&inferFamily(lines,end+1,parseListLine(lines[end+1]))==='number')end++;let top=0,sub=0;for(let i=start;i<=end;i++){const p=parseListLine(lines[i]);if(inferFamily(lines,i,p)!=='number')continue;const level=Math.max(0,Math.min(2,p.indent));let marker;if(level===0){top++;sub=0;marker=top+'.'}else if(level===1){sub++;marker=alphaMarker(sub)}else marker='-';lines[i]='\t'.repeat(level)+marker+' '+p.content}return {start,end}}
NS.TxtOutlineModel=Object.freeze({parseListLine,directFamily,inferFamily,alphaMarker,ordinalAt,markerFor,renderListLine,normalizeNumberOutline});
})(globalThis);
