(function(root){'use strict';
const NS=root.InkDOS2Spreadsheets=root.InkDOS2Spreadsheets||{};
function colName(n){let s='';while(n>=0){s=String.fromCharCode(n%26+65)+s;n=Math.floor(n/26)-1}return s}
function ref(r,c){return colName(c)+(r+1)}
function bytesOf(input){if(input instanceof Uint8Array)return input;if(input instanceof ArrayBuffer)return new Uint8Array(input);if(ArrayBuffer.isView(input))return new Uint8Array(input.buffer,input.byteOffset,input.byteLength);throw new TypeError('Delimited text input must be bytes')}
function decode(input){const bytes=bytesOf(input);let encoding='utf-8',offset=0,bom=false;if(bytes.length>=3&&bytes[0]===0xEF&&bytes[1]===0xBB&&bytes[2]===0xBF){bom=true;offset=3}else if(bytes.length>=2&&bytes[0]===0xFF&&bytes[1]===0xFE){bom=true;encoding='utf-16le';offset=2}else if(bytes.length>=2&&bytes[0]===0xFE&&bytes[1]===0xFF){bom=true;encoding='utf-16be';offset=2}const text=new TextDecoder(encoding,{fatal:false}).decode(bytes.subarray(offset));return{text,encoding,bom}}
function parseRows(text,delimiter){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'){if(text[i+1]==='"'){field+='"';i++}else quoted=false}else field+=ch;continue}if(ch==='"'&&field===''){quoted=true;continue}if(ch===delimiter){row.push(field);field='';continue}if(ch==='\r'||ch==='\n'){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(field);rows.push(row);row=[];field='';continue}field+=ch}if(quoted)throw new Error('Unterminated quoted field in delimited text');if(field!==''||row.length||!rows.length){row.push(field);rows.push(row)}return rows}
function blankBook(fileName){return{zip:null,sheets:[{name:'Sheet1',state:'visible',path:'',xml:'',cells:new Map(),originalCells:new Map(),merges:[],originalMerges:[],widths:{},originalWidths:{},heights:{},originalHeights:{},defaultColWidth:68,defaultRowHeight:20,drawings:[],tables:[],maxR:99,maxC:25}],active:0,fileName,loaded:true,legacy:false,images:[]}}
function sourceKind(delimiter,fileName){if(delimiter==='\t'||/\.tsv$/i.test(fileName||''))return'tsv';return'csv'}
function parse(input,{delimiter=',',fileName='Untitled.csv'}={}){if(delimiter!==','&&delimiter!=='\t')throw new Error('Only CSV and TSV delimiters are supported');const decoded=decode(input),rows=parseRows(decoded.text,delimiter),book=blankBook(fileName),sheet=book.sheets[0];let cols=0;rows.forEach((values,r)=>{cols=Math.max(cols,values.length);values.forEach((value,c)=>{if(value==='')return;sheet.cells.set(ref(r,c),{v:value,f:'',styleId:0,style:{font:{},border:{}},t:'s',display:value})})});sheet.delimitedMeta={rows:rows.length,cols,bom:decoded.bom,encoding:decoded.encoding,delimiter};book.delimitedMeta={rows:rows.length,cols,bom:decoded.bom,encoding:decoded.encoding,delimiter};return{book,bom:decoded.bom,encoding:decoded.encoding,sourceKind:sourceKind(delimiter,fileName)}}
function decodeRef(cellRef){const m=/^([A-Z]+)(\d+)$/i.exec(cellRef||'');if(!m)return null;let c=0;for(const ch of m[1].toUpperCase())c=c*26+ch.charCodeAt(0)-64;return{r:Number(m[2])-1,c:c-1}}
function bounds(sheet,meta){let rows=Math.max(0,Number(meta?.rows)||0),cols=Math.max(0,Number(meta?.cols)||0);for(const key of sheet.cells.keys()){const p=decodeRef(key);if(!p)continue;rows=Math.max(rows,p.r+1);cols=Math.max(cols,p.c+1)}return{rows,cols}}
function fieldText(value,delimiter){const s=String(value??'');return(s.includes('"')||s.includes(delimiter)||/[\r\n]/.test(s))?'"'+s.replace(/"/g,'""')+'"':s}
function encodeUtf16(text,bigEndian){const out=new Uint8Array(text.length*2);for(let i=0;i<text.length;i++){const code=text.charCodeAt(i);if(bigEndian){out[i*2]=code>>8;out[i*2+1]=code&255}else{out[i*2]=code&255;out[i*2+1]=code>>8}}return out}
function encodedParts(text,encoding,bom){if(encoding==='utf-16le'){const body=encodeUtf16(text,false);return bom?[new Uint8Array([0xFF,0xFE]),body]:[body]}if(encoding==='utf-16be'){const body=encodeUtf16(text,true);return bom?[new Uint8Array([0xFE,0xFF]),body]:[body]}const body=new TextEncoder().encode(text);return bom?[new Uint8Array([0xEF,0xBB,0xBF]),body]:[body]}
function serialize(book,{delimiter=',',bom,encoding}={}){if(delimiter!==','&&delimiter!=='\t')throw new Error('Only CSV and TSV delimiters are supported');const sheet=book?.sheets?.[book.active||0]||book?.sheets?.[0];if(!sheet)throw new Error('No worksheet is available for delimited export');const meta=sheet.delimitedMeta||book.delimitedMeta||{},shape=bounds(sheet,meta),lines=[];for(let r=0;r<shape.rows;r++){const fields=[];for(let c=0;c<shape.cols;c++){const cell=sheet.cells.get(ref(r,c));fields.push(fieldText(cell?.v??'',delimiter))}lines.push(fields.join(delimiter))}const text=lines.join('\r\n')+(shape.rows?'\r\n':'');const actualBom=bom==null?!!meta.bom:!!bom,actualEncoding=encoding||meta.encoding||'utf-8',mime=delimiter==='\t'?'text/tab-separated-values;charset=utf-8':'text/csv;charset=utf-8';return new Blob(encodedParts(text,actualEncoding,actualBom),{type:mime})}
NS.DelimitedText=Object.freeze({parse,serialize});
})(globalThis);
