(function(global){'use strict';
const NS=global.InkDOS2Presentations=global.InkDOS2Presentations||{},EMU=12700,TABLE_TEXT_LIMIT=20000;
function create({session,stage,shell,canvas,selection,history,onModelChange}={}){let editBefore=null,gesture=null;
 function findObject(id){return session.currentSlide?.objects.find(o=>o.id===id)||null}
 function borderStyle(line){if(!line?.color)return 'none';return `${Math.max(1,(line.widthEmu||12700)/EMU)}px solid ${line.color}`}
 function baseBox(el,o){el.dataset.objectId=o.id;el.style.left=(o.x/EMU)+'px';el.style.top=(o.y/EMU)+'px';el.style.width=(o.w/EMU)+'px';el.style.height=(o.h/EMU)+'px';el.style.opacity=String(o.opacity??1);el.style.transform=o.rotation?`rotate(${o.rotation}deg)`:'none';el.style.transformOrigin='center center'}
 function renderParagraphs(host,o){host.replaceChildren();const pars=Array.isArray(o.paragraphs)&&o.paragraphs.length?o.paragraphs:NS.PresentationModel.normalizeParagraphs(null,o.text,o);for(const p of pars){const line=document.createElement('div');line.className='slide-paragraph';line.style.textAlign=p.align||o.align||'left';if(o.wrap==='none')line.style.whiteSpace='nowrap';line.style.paddingLeft=(Math.max(0,p.level||0)*18)+'px';const lineFont=Math.max(1,...(p.runs||[]).map(r=>(r.fontSizePt||o.fontSizePt||24)*(o.autoFitScale||1)));line.style.fontSize=lineFont+'px';line.style.lineHeight=(p.lineSpacingPt!=null?p.lineSpacingPt*(o.autoFitScale||1):lineFont*(p.lineSpacing||1.0))+'px';if(p.spaceBeforePt)line.style.marginTop=p.spaceBeforePt+'px';if(p.spaceAfterPt)line.style.marginBottom=p.spaceAfterPt+'px';if(p.bullet){const bullet=document.createElement('span');bullet.className='slide-bullet';bullet.textContent=p.bullet+' ';line.appendChild(bullet)}for(const r of p.runs||[]){const span=document.createElement('span');span.textContent=r.text||'';span.style.fontSize=((r.fontSizePt||o.fontSizePt||24)*(o.autoFitScale||1))+'px';span.style.fontWeight=r.bold?'700':'400';span.style.fontStyle=r.italic?'italic':'normal';span.style.textDecoration=r.underline?'underline':'none';if(r.color)span.style.color=r.color;if(r.fontFamily)span.style.fontFamily=`${JSON.stringify(r.fontFamily)}, Arial, sans-serif`;if(Number.isFinite(Number(r.charSpacingPt))&&Number(r.charSpacingPt)!==0)span.style.letterSpacing=(Number(r.charSpacingPt)*(o.autoFitScale||1))+'px';line.appendChild(span)}host.appendChild(line)}}
 function selectObject(o,e){e?.stopPropagation?.();selection.select(o.id);syncSelection()}
 function applyCellBorder(cell,side,line){if(!line?.color)return;cell.style[`border${side}`]=borderStyle(line)}
 function clone(value){return JSON.parse(JSON.stringify(value))}
 function replaceCellPlainText(cell,value){const next=String(value??'').replace(/\r/g,'').slice(0,TABLE_TEXT_LIMIT);if(String(cell.text??'')===next)return false;const source=Array.isArray(cell.paragraphs)&&cell.paragraphs.length?cell.paragraphs:[];const lines=next.split('\n');cell.paragraphs=lines.map((line,index)=>{const template=clone(source[Math.min(index,Math.max(0,source.length-1))]||{align:'left',level:0,bullet:null,lineSpacing:1,lineSpacingPt:null,spaceBeforePt:0,spaceAfterPt:0,runs:[{text:'',fontSizePt:18,bold:false,italic:false,underline:false,color:null,fontFamily:null}]});if(!Array.isArray(template.runs)||!template.runs.length)template.runs=[{text:'',fontSizePt:18,bold:false,italic:false,underline:false,color:null,fontFamily:null}];template.runs[0].text=line;for(let i=1;i<template.runs.length;i++)template.runs[i].text='';return template});cell.text=NS.PresentationModel.plainText(cell.paragraphs);return true}
 function renderTable(o){const wrap=document.createElement('div');wrap.className='slide-table';baseBox(wrap,o);wrap.addEventListener('pointerdown',e=>selectObject(o,e));const table=document.createElement('table');table.className='slide-table-grid';const columns=Array.isArray(o.columns)?o.columns:[],totalWidth=Math.max(1,columns.reduce((sum,v)=>sum+(Number(v)||0),0));if(columns.length){const cg=document.createElement('colgroup');for(const width of columns){const col=document.createElement('col');col.style.width=(Math.max(0,Number(width)||0)/totalWidth*100)+'%';cg.appendChild(col)}table.appendChild(cg)}const rows=Array.isArray(o.rows)?o.rows:[],totalHeight=Math.max(1,rows.reduce((sum,row)=>sum+(Number(row.heightEmu)||0),0));const body=document.createElement('tbody');rows.forEach((row,rowIndex)=>{const tr=document.createElement('tr');tr.style.height=(Math.max(0,Number(row.heightEmu)||0)/totalHeight*100)+'%';(row.cells||[]).forEach((cell,columnIndex)=>{if(cell.hMerge||cell.vMerge)return;const td=document.createElement('td');td.className='slide-table-cell';td.dataset.tableRow=String(rowIndex);td.dataset.tableCol=String(columnIndex);if(Number(cell.colSpan)>1)td.colSpan=Math.max(1,Math.round(Number(cell.colSpan)));if(Number(cell.rowSpan)>1)td.rowSpan=Math.max(1,Math.round(Number(cell.rowSpan)));if(cell.fill&&cell.fill!=='none')td.style.background=cell.fill;td.style.verticalAlign=cell.verticalAlign==='top'?'top':cell.verticalAlign==='bottom'?'bottom':'middle';td.style.padding=`${(cell.marginTopEmu||0)/EMU}px ${(cell.marginRightEmu||0)/EMU}px ${(cell.marginBottomEmu||0)/EMU}px ${(cell.marginLeftEmu||0)/EMU}px`;applyCellBorder(td,'Left',cell.borders?.left);applyCellBorder(td,'Right',cell.borders?.right);applyCellBorder(td,'Top',cell.borders?.top);applyCellBorder(td,'Bottom',cell.borders?.bottom);const content=document.createElement('div');content.className='table-cell-content';const canEdit=session.sourceKind==='pptx'&&!!o.pptP2Imported&&!!o.sourceRef&&!cell.hMerge&&!cell.vMerge;content.contentEditable=canEdit?'true':'false';content.spellcheck=canEdit;renderParagraphs(content,{...cell,fontSizePt:18,autoFitScale:1,wrap:'square'});content.addEventListener('pointerdown',e=>{e.stopPropagation();selection.select(o.id);syncSelection()});if(canEdit){content.addEventListener('focus',()=>{selection.select(o.id);editBefore=session.snapshot();syncSelection()});content.addEventListener('blur',()=>{const before=editBefore;editBefore=null;if(!before)return;const changed=replaceCellPlainText(cell,content.innerText.replace(/\r/g,''));if(changed&&history.commitFromBefore('Edit table cell',before))onModelChange?.({renderThumbs:true})})}td.appendChild(content);tr.appendChild(td)});body.appendChild(tr)});table.appendChild(body);wrap.appendChild(table);return wrap}
 function render(){const slide=session.currentSlide;if(!slide){canvas.replaceChildren();return}const w=slide.widthEmu/EMU,h=slide.heightEmu/EMU;canvas.style.width=w+'px';canvas.style.height=h+'px';canvas.style.background=slide.background||'#fff';canvas.style.backgroundImage=slide.backgroundImage?`url(${JSON.stringify(slide.backgroundImage)})`:'none';canvas.style.backgroundSize='cover';canvas.style.backgroundPosition='center';canvas.dataset.slideId=slide.id;const frag=document.createDocumentFragment();for(const o of slide.objects){if(o.type==='text'){const box=document.createElement('div');box.className='slide-textbox';baseBox(box,o);if(o.fill&&o.fill!=='none')box.style.background=o.fill;box.style.border=borderStyle(o.line);box.style.padding=`${(o.marginTopEmu||0)/EMU}px ${(o.marginRightEmu||0)/EMU}px ${(o.marginBottomEmu||0)/EMU}px ${(o.marginLeftEmu||0)/EMU}px`;box.style.justifyContent=o.verticalAlign==='middle'?'center':o.verticalAlign==='bottom'?'flex-end':'flex-start';box.addEventListener('pointerdown',e=>selectObject(o,e));const content=document.createElement('div');content.className='rich-text-content';if(o.richSource)content.style.minHeight='0';content.contentEditable=session.sourceKind==='ppt'?'false':'true';content.spellcheck=true;renderParagraphs(content,o);content.addEventListener('pointerdown',e=>{e.stopPropagation();selection.select(o.id);syncSelection()});content.addEventListener('focus',()=>{selection.select(o.id);if(session.sourceKind!=='ppt')editBefore=session.snapshot();syncSelection()});content.addEventListener('input',()=>{if(session.sourceKind==='ppt')return;const obj=findObject(o.id);if(obj)obj.text=content.innerText.replace(/\r/g,'')});content.addEventListener('blur',()=>{if(session.sourceKind==='ppt'){editBefore=null;return}const obj=findObject(o.id);if(obj&&obj.text!==NS.PresentationModel.plainText(obj.paragraphs)){obj.paragraphs=NS.PresentationModel.normalizeParagraphs(null,obj.text,obj);obj.richSource=null}if(history.commitFromBefore('Edit text',editBefore))onModelChange?.({renderThumbs:true});editBefore=null});box.appendChild(content);frag.appendChild(box)}
 else if(o.type==='image'){const wrap=document.createElement('div');wrap.className='slide-image';baseBox(wrap,o);wrap.style.border=borderStyle(o.line);wrap.addEventListener('pointerdown',e=>selectObject(o,e));const img=document.createElement('img');img.alt='';img.draggable=false;img.src=o.src||'';const c=o.crop||{},l=Math.max(0,Math.min(.95,c.left||0)),r=Math.max(0,Math.min(.95,c.right||0)),t=Math.max(0,Math.min(.95,c.top||0)),b=Math.max(0,Math.min(.95,c.bottom||0)),vw=Math.max(.01,1-l-r),vh=Math.max(.01,1-t-b);img.style.width=(100/vw)+'%';img.style.height=(100/vh)+'%';img.style.left=(-l/vw*100)+'%';img.style.top=(-t/vh*100)+'%';wrap.appendChild(img);frag.appendChild(wrap)}
 else if(o.type==='shape'){const el=document.createElement('div');el.className='slide-shape';baseBox(el,o);if(o.fill&&o.fill!=='none')el.style.background=o.fill;el.style.border=borderStyle(o.line);if(o.shapeType==='ellipse')el.style.borderRadius='50%';else if(o.shapeType==='roundRect')el.style.borderRadius='12%';else if(o.shapeType==='line'){el.style.height='0';el.style.border='0';el.style.borderTop=borderStyle(o.line||{color:'#000',widthEmu:12700})}el.addEventListener('pointerdown',e=>selectObject(o,e));frag.appendChild(el)}
 else if(o.type==='table'){frag.appendChild(renderTable(o))}}canvas.replaceChildren(frag);syncSelection()}
 function editableGeometry(o){return !!o&&session.sourceKind!=='ppt'&&!o.importedUnmapped}
 function overlayBox(overlay,o){overlay.style.left=(o.x/EMU)+'px';overlay.style.top=(o.y/EMU)+'px';overlay.style.width=Math.max(2,o.w/EMU)+'px';overlay.style.height=Math.max(2,o.h/EMU)+'px';overlay.style.transform=o.rotation?`rotate(${o.rotation}deg)`:'none'}
 function rotatedPoint(x,y,cx,cy,deg){if(!deg)return{x,y};const r=deg*Math.PI/180,dx=x-cx,dy=y-cy,c=Math.cos(r),s=Math.sin(r);return{x:cx+dx*c-dy*s,y:cy+dx*s+dy*c}}
 function positionHandle(h,o){const x=o.x/EMU,y=o.y/EMU,w=o.w/EMU,hh=o.h/EMU,cx=x+w/2,cy=y+hh/2,kind=h.dataset.p1Handle;let px=cx,py=y-18;if(kind==='rotate'){px=x+w;py=y-18}else if(kind==='resize'){px=x+w;py=y+hh}const p=rotatedPoint(px,py,cx,cy,o.rotation||0);h.style.left=p.x+'px';h.style.top=p.y+'px'}
 function positionHandles(o){for(const h of canvas.querySelectorAll('.ppt-p1-handle'))if(h.dataset.objectId===o.id)positionHandle(h,o)}
 function makeHandle(kind,label,o){const h=document.createElement('span');h.className='ppt-p1-handle '+kind;h.dataset.p1Handle=kind;h.dataset.objectId=o.id;h.setAttribute('role','button');h.setAttribute('aria-label',label);positionHandle(h,o);h.addEventListener('pointerdown',startGesture);return h}
 function syncSelection(){canvas.querySelectorAll('[data-object-id]').forEach(el=>el.classList.toggle('selected',el.dataset.objectId===selection.objectId));canvas.querySelector('.ppt-p1-object-overlay')?.remove();canvas.querySelectorAll('.ppt-p1-handle').forEach(h=>h.remove());const o=findObject(selection.objectId);if(!o)return;const overlay=document.createElement('div');overlay.className='ppt-p1-object-overlay'+(editableGeometry(o)?'':' locked');overlay.dataset.objectId=o.id;overlayBox(overlay,o);canvas.appendChild(overlay);if(editableGeometry(o))canvas.append(makeHandle('move','Move object',o),makeHandle('rotate','Rotate object',o),makeHandle('resize','Resize object',o))}
 function coords(e){const slide=session.currentSlide,rect=canvas.getBoundingClientRect();return{x:(e.clientX-rect.left)*slide.widthEmu/Math.max(1,rect.width),y:(e.clientY-rect.top)*slide.heightEmu/Math.max(1,rect.height)}}
 function startGesture(e){if(session.sourceKind==='ppt'||gesture)return;const o=findObject(selection.objectId);if(!editableGeometry(o))return;e.preventDefault();e.stopPropagation();const kind=e.currentTarget.dataset.p1Handle,p=coords(e),before=session.snapshot();gesture={kind,id:o.id,p0:p,x:o.x,y:o.y,w:o.w,h:o.h,rotation:o.rotation||0,before};if(kind==='rotate'){const cx=o.x+o.w/2,cy=o.y+o.h/2;gesture.cx=cx;gesture.cy=cy;gesture.angle0=Math.atan2(p.y-cy,p.x-cx)*180/Math.PI}global.addEventListener('pointermove',moveGesture,{passive:false});global.addEventListener('pointerup',endGesture,{once:true});global.addEventListener('pointercancel',endGesture,{once:true});try{e.currentTarget.setPointerCapture?.(e.pointerId)}catch(_){/* Pointer capture is optional; window listeners keep the gesture active. */}}
 function moveGesture(e){if(!gesture)return;e.preventDefault();const o=findObject(gesture.id);if(!o)return;const p=coords(e),slide=session.currentSlide;if(gesture.kind==='move'){o.x=Math.max(0,Math.min(slide.widthEmu-o.w,gesture.x+(p.x-gesture.p0.x)));o.y=Math.max(0,Math.min(slide.heightEmu-o.h,gesture.y+(p.y-gesture.p0.y)))}else if(gesture.kind==='resize'){const min=254000;o.w=Math.max(min,Math.min(slide.widthEmu-o.x,gesture.w+(p.x-gesture.p0.x)));o.h=Math.max(o.type==='line'?12700:min,Math.min(slide.heightEmu-o.y,gesture.h+(p.y-gesture.p0.y)))}else if(gesture.kind==='rotate'){const a=Math.atan2(p.y-gesture.cy,p.x-gesture.cx)*180/Math.PI;o.rotation=Math.round((gesture.rotation+a-gesture.angle0)*10)/10}const target=canvas.querySelector(`[data-object-id="${CSS.escape(o.id)}"]`),overlay=canvas.querySelector('.ppt-p1-object-overlay');if(target)baseBox(target,o);if(overlay)overlayBox(overlay,o);positionHandles(o)}
 function endGesture(){if(!gesture)return;global.removeEventListener('pointermove',moveGesture);const before=gesture.before,label=gesture.kind==='move'?'Move object':gesture.kind==='resize'?'Resize object':'Rotate object';gesture=null;if(history.commitFromBefore(label,before))onModelChange?.({renderThumbs:true});syncSelection()}
 canvas.addEventListener('pointerdown',e=>{if(e.target===canvas){selection.clear();syncSelection()}});
 return Object.freeze({render,syncSelection,findObject,renderParagraphs})
}
NS.SlideSurface=Object.freeze({create});
})(globalThis);