(function(root){'use strict';
const SUITE_STORAGE_KEY='inkdos2:ui-density',VALID=new Set(['auto','desktop','mobile']),THRESHOLD=900,POINTER_QUERY='(hover: hover) and (pointer: fine)',ATTR='data-ui-density',PREF_ATTR='data-ui-density-preference',APPS=new Set(['documents','spreadsheets','presentations','pdf','epub','txt']);
const doc=typeof document!=='undefined'?document:null;
function workspaceContext(){let parts=[];try{parts=decodeURIComponent(root.location?.pathname||'').split('/').filter(Boolean)}catch(_){}return parts.find(part=>APPS.has(part))||null}
const WORKSPACE=workspaceContext(),STORAGE_KEY=WORKSPACE?'inkdos2:'+WORKSPACE+':ui-density':SUITE_STORAGE_KEY,LEGACY_SUITE_KEY=WORKSPACE?SUITE_STORAGE_KEY:null;
function normalize(value){return VALID.has(value)?value:'auto'}
function currentEnvironment(){const width=doc?.documentElement?.clientWidth||Number(root.innerWidth)||0;let finePointer=false;try{finePointer=typeof root.matchMedia==='function'&&root.matchMedia(POINTER_QUERY).matches}catch(_){}return{width,finePointer}}
function resolve(value='auto',environment={}){const preference=normalize(value);if(preference==='desktop'||preference==='mobile')return preference;const fallback=currentEnvironment(),width=Number(environment.width??fallback.width)||0,finePointer=environment.finePointer==null?!!fallback.finePointer:!!environment.finePointer;return width>=THRESHOLD&&finePointer?'desktop':'mobile'}
function read(){try{const saved=root.localStorage?.getItem(STORAGE_KEY);if(saved!=null)return normalize(saved);if(LEGACY_SUITE_KEY){const legacy=root.localStorage?.getItem(LEGACY_SUITE_KEY);if(legacy!=null){const migrated=normalize(legacy);root.localStorage?.setItem(STORAGE_KEY,migrated);return migrated}}}catch(_){}return'auto'}
let preference=read(),effective=resolve(preference);
function apply(value=preference,environment){preference=normalize(value);effective=resolve(preference,environment||currentEnvironment());const element=doc?.documentElement;if(element){element.setAttribute(ATTR,effective);element.setAttribute(PREF_ATTR,preference)}syncControls();return effective}
function write(value){try{root.localStorage?.setItem(STORAGE_KEY,value)}catch(_){}}
function announce(){try{doc?.dispatchEvent?.(new CustomEvent('inkdos:ui-density',{detail:{preference,effective,workspace:WORKSPACE,storageKey:STORAGE_KEY}}))}catch(_){}}
function set(value){preference=normalize(value);write(preference);apply(preference);announce();return effective}
function syncControls(){if(!doc)return;for(const button of doc.querySelectorAll('[data-inkdos-density-mode]')){const active=button.dataset.inkdosDensityMode===preference;button.setAttribute('aria-checked',String(active));button.classList.toggle('active',active)}}
function densityIcon(mode){if(!doc||!new Set(['desktop','mobile']).has(mode))return null;const svg=doc.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','inkdos-density-icon');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.setAttribute('focusable','false');const body=doc.createElementNS(svg.namespaceURI,'rect');if(mode==='desktop'){body.setAttribute('x','3');body.setAttribute('y','5');body.setAttribute('width','18');body.setAttribute('height','12');body.setAttribute('rx','1.5');const stand=doc.createElementNS(svg.namespaceURI,'path');stand.setAttribute('d','M9 21h6M12 17v4');svg.append(body,stand)}else{body.setAttribute('x','7');body.setAttribute('y','2.5');body.setAttribute('width','10');body.setAttribute('height','19');body.setAttribute('rx','2');const home=doc.createElementNS(svg.namespaceURI,'path');home.setAttribute('d','M10.5 18.5h3');svg.append(body,home)}return svg}
function buttonFor(mode,label,{icon=false}={}){const button=doc.createElement('button');button.type='button';button.dataset.inkdosDensityMode=mode;button.setAttribute('role','menuitemradio');if(icon){const glyph=densityIcon(mode);if(glyph)button.append(glyph);const text=doc.createElement('span');text.textContent=label;button.append(text)}else button.textContent=label;button.addEventListener('click',()=>set(mode));return button}
function installControl(host,{home=false}={}){if(!doc||!host||host.querySelector('[data-inkdos-density-control]'))return null;const wrap=doc.createElement('div');wrap.dataset.inkdosDensityControl='';wrap.className='inkdos-density-control'+(home?' home-density-control':'');if(home){const divider=doc.createElement('div');divider.className='inkdos-density-divider';divider.setAttribute('role','separator');const label=doc.createElement('div');label.className='inkdos-density-label';label.textContent='Interface';host.append(divider,label,wrap);wrap.append(buttonFor('auto','Auto'),buttonFor('desktop','Desktop',{icon:true}),buttonFor('mobile','Smartphone',{icon:true}))}else{const label=doc.createElement('div');label.className='drawer-section-label inkdos-density-label';label.textContent='Interface';host.append(label,wrap);wrap.append(buttonFor('auto','Auto'),buttonFor('desktop','Desktop'),buttonFor('mobile','Smartphone'))}syncControls();return wrap}
function autoInstall(){if(!doc)return;const home=doc.getElementById('appearanceMenu');if(home){installControl(home,{home:true});return}const drawer=doc.getElementById('generalMenu')||doc.querySelector('.drawer');if(drawer)installControl(drawer)}
function sharedBase(){if(!doc)return'';const src=doc.currentScript?.src||'';return src?src.slice(0,src.lastIndexOf('/')+1):''}
const SHARED_BASE=sharedBase();
function registerWorkspaceOffline(){if(!doc||!WORKSPACE||!SHARED_BASE||!root.navigator?.serviceWorker||!/^https?:$/.test(root.location?.protocol||''))return;const base=new URL('../',SHARED_BASE);root.navigator.serviceWorker.register(new URL('service-worker.js',base).href,{scope:base.href,updateViaCache:'none'}).catch(()=>{})}
registerWorkspaceOffline();
function ensureStyle(href,id){if(!doc||!href||doc.getElementById(id))return;const link=doc.createElement('link');link.id=id;link.rel='stylesheet';link.href=href;(doc.head||doc.documentElement).appendChild(link)}
function ensureScript(src,id){if(!doc||!src)return Promise.resolve(null);const existing=doc.getElementById(id);if(existing){if(existing.dataset.loaded==='true')return Promise.resolve(existing);return new Promise((resolve,reject)=>{existing.addEventListener('load',()=>resolve(existing),{once:true});existing.addEventListener('error',reject,{once:true})})}return new Promise((resolve,reject)=>{const script=doc.createElement('script');script.id=id;script.src=src;script.async=false;script.addEventListener('load',()=>{script.dataset.loaded='true';resolve(script)},{once:true});script.addEventListener('error',reject,{once:true});(doc.head||doc.documentElement).appendChild(script)})}
function bootstrapWorkspaceSettings(){if(!doc||!WORKSPACE||!SHARED_BASE)return;ensureStyle(SHARED_BASE+'localization/localization.css','inkdosLocalizationStyles');ensureScript(SHARED_BASE+'localization/ui-localization.js','inkdosLocalizationRuntime').then(()=>ensureScript(SHARED_BASE+'localization/settings-strip.js','inkdosSettingsStripRuntime')).catch(()=>{})}
if(doc?.documentElement)apply(preference);
if(doc){if(doc.readyState==='loading')doc.addEventListener('DOMContentLoaded',autoInstall,{once:true});else autoInstall();bootstrapWorkspaceSettings()}
function refreshAutoDensity(){if(preference!=='auto')return effective;const previous=effective;apply(preference);if(effective!==previous)announce();return effective}
if(typeof root.addEventListener==='function'){
  root.addEventListener('resize',refreshAutoDensity,{passive:true});
  root.addEventListener('storage',event=>{if(event.key!==STORAGE_KEY)return;preference=normalize(event.newValue);apply(preference);announce()});
}
try{if(typeof root.matchMedia==='function'){const pointerQuery=root.matchMedia(POINTER_QUERY);const onPointerChange=()=>refreshAutoDensity();if(typeof pointerQuery.addEventListener==='function')pointerQuery.addEventListener('change',onPointerChange);else if(typeof pointerQuery.addListener==='function')pointerQuery.addListener(onPointerChange)}}catch(_){}
root.InkDOSUiDensity=Object.freeze({STORAGE_KEY,SUITE_STORAGE_KEY,LEGACY_SUITE_KEY,THRESHOLD,POINTER_QUERY,resolve,apply,set,installControl,get workspace(){return WORKSPACE},get preference(){return preference},get effective(){return effective}});
})(globalThis);
