#!/usr/bin/env python3
"""Build labs/pdf/trust/icp-brasil.js from ITI's published ICP-Brasil CA bundle.

Inputs are files downloaded by a maintainer (this script makes no network requests):
  ACcompactado.zip  http://acraiz.icpbrasil.gov.br/credenciadas/CertificadosAC-ICP-Brasil/ACcompactado.zip
  hashsha512.txt    http://acraiz.icpbrasil.gov.br/credenciadas/CertificadosAC-ICP-Brasil/hashsha512.txt

The zip must match the published SHA-512. Trust anchors are selected only by the pinned SHA-256
fingerprints below (document-signing roots; v10 is SSL and v11 is code signing, so they are left
out). Intermediate CAs are kept only when their signature chains to a pinned anchor; they are
path-building candidates, never anchors. Requires the `cryptography` package.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import sys
import zipfile
from pathlib import Path

from cryptography import x509
from cryptography.x509.oid import NameOID

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "labs" / "pdf" / "trust" / "icp-brasil.js"

# SHA-256 of the DER root certificates. v5 is also listed with this fingerprint in Microsoft's
# trusted root program (CCADB report); v6, v7 and v12 come from ITI's bundle only.
ANCHORS = {
    "Autoridade Certificadora Raiz Brasileira v5": "caa53fc6091c6951887c976e378f6ef89aa6377c55d97b6475422b71ed7e9b17",
    "Autoridade Certificadora Raiz Brasileira v6": "3bdb9b509352f1d3d71c2bf64d9a38a4e6cebda27809d77f7ac476cbde6e314a",
    "Autoridade Certificadora Raiz Brasileira v7": "5657e70580eb678983f3ed7dfce091d84cae6549389a47fccda8d0e4dc2cf576",
    "Autoridade Certificadora Raiz Brasileira v12": "d8478e37ce19c690cf657381e68fe600e4e1a042536830f06847e03e554c4b01",
}


def load_certificates(data: bytes) -> list[x509.Certificate]:
    certs = []
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        for name in sorted(archive.namelist()):
            if name.endswith("/"):
                continue
            raw = archive.read(name)
            try:
                certs.append(x509.load_pem_x509_certificate(raw) if b"-----BEGIN" in raw else x509.load_der_x509_certificate(raw))
            except ValueError:
                print(f"skipped unreadable entry {name}", file=sys.stderr)
    return certs


def common_name(cert: x509.Certificate) -> str:
    names = cert.subject.get_attributes_for_oid(NameOID.COMMON_NAME)
    return str(names[0].value) if names else cert.subject.rfc4514_string()


def is_ca(cert: x509.Certificate) -> bool:
    try:
        return bool(cert.extensions.get_extension_for_class(x509.BasicConstraints).value.ca)
    except x509.ExtensionNotFound:
        return False


def issued_by(cert: x509.Certificate, issuer: x509.Certificate) -> bool:
    try:
        cert.verify_directly_issued_by(issuer)
        return True
    except Exception:
        return False


def der(cert: x509.Certificate) -> bytes:
    from cryptography.hazmat.primitives.serialization import Encoding
    return cert.public_bytes(Encoding.DER)


def build(zip_bytes: bytes) -> str:
    certs = load_certificates(zip_bytes)
    by_fp = {hashlib.sha256(der(c)).hexdigest(): c for c in certs}
    missing = [name for name, fp in ANCHORS.items() if fp not in by_fp]
    if missing:
        raise SystemExit(f"pinned anchors missing from the bundle: {missing}")
    anchors = [by_fp[fp] for fp in ANCHORS.values()]
    trusted = list(anchors)
    intermediates: list[x509.Certificate] = []
    pending = [c for c in certs if is_ca(c) and c not in anchors and c.subject != c.issuer]
    grew = True
    while grew:
        grew = False
        for cert in list(pending):
            if any(cert.issuer == t.subject and issued_by(cert, t) for t in trusted):
                intermediates.append(cert); trusted.append(cert); pending.remove(cert); grew = True
    intermediates.sort(key=lambda c: (common_name(c), der(c)))
    payload = {
        "name": "ICP-Brasil",
        "source": "ITI ACcompactado.zip, SHA-512 " + hashlib.sha512(zip_bytes).hexdigest(),
        "anchors": [{"name": common_name(c), "sha256": hashlib.sha256(der(c)).hexdigest(), "der": base64.b64encode(der(c)).decode()} for c in anchors],
        "intermediates": [{"name": common_name(c), "der": base64.b64encode(der(c)).decode()} for c in intermediates],
    }
    body = json.dumps(payload, ensure_ascii=False, indent=1)
    return ("/* Generated by scripts/build_icp_brasil_trust.py; do not edit by hand.\n"
            " * ICP-Brasil document-signing roots (pinned fingerprints) and the intermediate CAs that chain\n"
            " * to them, used offline to build and check certificate paths. Revocation is not included. */\n"
            "globalThis.InkDOSPdfLabTrust = Object.freeze(" + body + ");\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("zip", type=Path)
    parser.add_argument("sha512_file", type=Path)
    parser.add_argument("--check", action="store_true", help="fail if the committed file differs")
    args = parser.parse_args()
    data = args.zip.read_bytes()
    expected = args.sha512_file.read_text(encoding="utf-8").split()[0].lower()
    if hashlib.sha512(data).hexdigest() != expected:
        raise SystemExit("ACcompactado.zip does not match the published SHA-512")
    text = build(data)
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != text:
            raise SystemExit(f"{OUTPUT.relative_to(ROOT)} is stale")
        print("ICP-Brasil trust bundle is current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
