(function(global){'use strict';
const NS=global.InkDOS2Documents;if(!NS)throw new Error('Documents runtime namespace missing.');
const $=id=>document.getElementById(id);
const session=new NS.DocumentSession();
const state=new NS.DocumentState(session);
const viewport=$('viewport'),pagesHost=$('pagesHost'),welcome=$('welcome'),fileInput=$('fileInput');
const adapter=new NS.ContentViewportAdapter(viewport,pagesHost);
let zoomControls=null;
const zoom=new NS.ZoomController(adapter,pagesHost,info=>zoomControls?.update(info));
const navigation=NS.NavigationPanel.create({pagesHost});
const chrome=NS.ChromeController.create({session});
const sessionDialog=NS.SessionDialog.create();
const surface=NS.PageSurface.create({state,session,viewport,pagesHost,welcome,zoom,navigation});
const editor=NS.EditorController.create({state,session,pagesHost,surface,chrome,zoom});
const ruler=NS.RulerController.create({state,editor});
const fileOpen=NS.FileOpenController.create({state,session,fileInput,pagesHost,chrome,surface,editor,sessionDialog});
const saveController=NS.SaveController.create({session,pagesHost,chrome});
zoomControls=NS.ZoomControls.create({zoom});
const commands=NS.CommandController.create({session,pagesHost,chrome,fileOpen,saveController,editor,ruler,navigation,zoom,zoomControls});
chrome.setChooseFile(fileOpen.requestOpen);
NS.Appearance.install();
zoom.install();
fileOpen.install();
commands.install();
chrome.syncDirty();
surface.updateStats();
NS.DocumentsApp=Object.freeze({session,state,zoom,open:fileOpen.openFile,requestOpen:fileOpen.requestOpen,newDocument:fileOpen.requestNew,save:saveController.save});
})(globalThis);
