(function(global){
'use strict';
const W_NS='http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const R_NS='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const PKG_REL_NS='http://schemas.openxmlformats.org/package/2006/relationships';
const esc=s=>String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let writerXmlBudget=null;function parseXml(text,context='DOCX export XML'){if(global.InkDeskRuntime)return global.InkDeskRuntime.parseXml(text,context,writerXmlBudget);const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw new Error('The DOCX XML could not be parsed.');return doc}
function serialize(doc){return new XMLSerializer().serializeToString(doc)}
function childrenNamed(el,name){return Array.from(el&&el.children||[]).filter(x=>x.localName===name)}
function descendants(el,name){return Array.from(el?el.getElementsByTagNameNS('*',name):[])}
function editorNode(item){return item.dataset&&item.dataset.sourceIndex!==undefined?(item.firstElementChild||item):item}
function editorText(el){const clone=el.cloneNode(true);clone.querySelectorAll('.list-label,img,mark[data-search]').forEach(x=>x.remove());return String(clone.innerText||clone.textContent||'').replace(/\u00a0/g,'').replace(/\r/g,'')}
function sourceItems(host){const out=[];for(const page of host.querySelectorAll('.page-content'))for(const item of Array.from(page.children)){const raw=item.dataset&&item.dataset.sourceIndex,sourceIndex=raw!==undefined&&raw!==''?Number(raw):null,subRaw=item.dataset&&item.dataset.sourceSubIndex,sourceSubIndex=subRaw!==undefined&&subRaw!==''?Number(subRaw):0;out.push({sourceIndex:Number.isFinite(sourceIndex)?sourceIndex:null,sourceSubIndex:Number.isFinite(sourceSubIndex)?sourceSubIndex:0,node:editorNode(item)})}return out}
function sourceBlocks(node){if(!node)return[];if(node.localName==='p'||node.localName==='tbl')return[node];if(node.localName==='sdt'){const content=descendants(node,'sdtContent')[0]||node;return Array.from(content.children).filter(x=>x.localName==='p'||x.localName==='tbl')}return[]}
function setTextNode(t,value){t.textContent=value;if(/^\s|\s$/.test(value))t.setAttributeNS('http://www.w3.org/XML/1998/namespace','xml:space','preserve');else t.removeAttributeNS('http://www.w3.org/XML/1998/namespace','space')}
function patchText(container,newText){const nodes=descendants(container,'t'),oldText=nodes.map(x=>x.textContent||'').join('');if(oldText===newText)return false;if(!nodes.length){const doc=container.ownerDocument,p=container.localName==='p'?container:(descendants(container,'p')[0]||container),r=doc.createElementNS(W_NS,'w:r'),t=doc.createElementNS(W_NS,'w:t');setTextNode(t,newText);r.appendChild(t);p.appendChild(r);return true}
 let prefix=0;while(prefix<oldText.length&&prefix<newText.length&&oldText[prefix]===newText[prefix])prefix++;
 let suffix=0;while(suffix<oldText.length-prefix&&suffix<newText.length-prefix&&oldText[oldText.length-1-suffix]===newText[newText.length-1-suffix])suffix++;
 const oldEnd=oldText.length-suffix,newEnd=newText.length-suffix,replacement=newText.slice(prefix,newEnd);let pos=0,first=-1,last=-1;
 const ranges=nodes.map((n,i)=>{const start=pos,end=pos+(n.textContent||'').length;pos=end;if(first<0&&end>=prefix)first=i;if(start<=oldEnd)last=i;return{start,end,text:n.textContent||''}});
 if(first<0)first=nodes.length-1;if(last<first)last=first;
 for(let i=first;i<=last;i++){
  const r=ranges[i];let value='';if(i===first)value+=r.text.slice(0,Math.max(0,prefix-r.start));if(i===first)value+=replacement;if(i===last)value+=r.text.slice(Math.max(0,oldEnd-r.start));setTextNode(nodes[i],value);
 }
 return true
}
function patchTable(xmlTable,htmlTable){const xmlCells=descendants(xmlTable,'tc'),htmlCells=Array.from(htmlTable.querySelectorAll('td,th'));for(let i=0;i<Math.min(xmlCells.length,htmlCells.length);i++)patchText(xmlCells[i],editorText(htmlCells[i]))}
function runXml(node){const text=node.nodeType===3?node.nodeValue:node.textContent||'';if(!text)return'';const el=node.nodeType===1?node:node.parentElement;let r='';if(el){const cs=getComputedStyle(el);if(parseInt(cs.fontWeight)>=600||['B','STRONG'].includes(el.tagName))r+='<w:b/>';if(cs.fontStyle==='italic'||el.tagName==='I')r+='<w:i/>';if((cs.textDecorationLine||'').includes('underline')||el.tagName==='U')r+='<w:u w:val="single"/>';const sz=parseFloat(cs.fontSize);if(sz)r+='<w:sz w:val="'+Math.round(sz*1.5)+'"/><w:szCs w:val="'+Math.round(sz*1.5)+'"/>';const f=(cs.fontFamily||'Calibri').split(',')[0].replace(/["']/g,'');r+='<w:rFonts w:ascii="'+esc(f)+'" w:hAnsi="'+esc(f)+'"/>'}return'<w:r>'+(r?'<w:rPr>'+r+'</w:rPr>':'')+'<w:t xml:space="preserve">'+esc(text)+'</w:t></w:r>'}
function paragraphXml(el){let style='';if(el.tagName==='H1')style='<w:pStyle w:val="Title"/>';else if(el.tagName==='H2')style='<w:pStyle w:val="Heading1"/>';else if(el.tagName==='H3')style='<w:pStyle w:val="Heading2"/>';const cs=getComputedStyle(el),align=cs.textAlign,jc=align==='center'?'<w:jc w:val="center"/>':align==='right'?'<w:jc w:val="right"/>':align==='justify'?'<w:jc w:val="both"/>':'';const ml=parseFloat(cs.marginLeft)||0,mr=parseFloat(cs.marginRight)||0,ti=parseFloat(cs.textIndent)||0,ind=(ml||mr||ti)?'<w:ind w:left="'+Math.round(ml*15)+'" w:right="'+Math.round(mr*15)+'" w:firstLine="'+Math.round(ti*15)+'"/>':'';let runs='';el.childNodes.forEach(n=>{if(n.nodeType===3||(n.nodeType===1&&!['IMG','TABLE','UL','OL'].includes(n.tagName)))runs+=runXml(n)});if(!runs)runs='<w:r><w:t></w:t></w:r>';return'<w:p><w:pPr>'+style+jc+ind+'</w:pPr>'+runs+'</w:p>'}
function tableXml(table){let x='<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders><w:top w:val="single" w:sz="4"/><w:left w:val="single" w:sz="4"/><w:bottom w:val="single" w:sz="4"/><w:right w:val="single" w:sz="4"/><w:insideH w:val="single" w:sz="4"/><w:insideV w:val="single" w:sz="4"/></w:tblBorders></w:tblPr>';for(const tr of table.rows){x+='<w:tr>';for(const td of tr.cells)x+='<w:tc><w:tcPr>'+(td.colSpan>1?'<w:gridSpan w:val="'+td.colSpan+'"/>':'')+'</w:tcPr><w:p><w:r><w:t>'+esc(td.innerText)+'</w:t></w:r></w:p></w:tc>';x+='</w:tr>'}return x+'</w:tbl>'}
function fragmentNode(doc,xml){const wrapper=parseXml('<root xmlns:w="'+W_NS+'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">'+xml+'</root>');return doc.importNode(wrapper.documentElement.firstElementChild,true)}
function xmlForNewNode(node){if(node.tagName==='TABLE')return tableXml(node);if(node.tagName==='UL'||node.tagName==='OL'){let out='',i=1;for(const li of node.children){const p=document.createElement('p');p.textContent=(node.tagName==='OL'?i+'. ':'• ')+li.innerText;i++;out+=paragraphXml(p)}return out}return paragraphXml(node)}
function ensureContentType(zip,ext,mime){const file=zip.file('[Content_Types].xml');if(!file)return Promise.resolve();return file.async('string').then(text=>{const doc=parseXml(text),types=doc.documentElement,exists=Array.from(types.children).some(x=>x.localName==='Default'&&String(x.getAttribute('Extension')).toLowerCase()===ext.toLowerCase());if(!exists){const el=doc.createElementNS(types.namespaceURI,'Default');el.setAttribute('Extension',ext);el.setAttribute('ContentType',mime);types.appendChild(el);zip.file('[Content_Types].xml',serialize(doc))}})}
async function imageData(img){const src=img.dataset&&img.dataset.docxData?img.dataset.docxData:img.src;if(/^data:/i.test(src)){const m=src.match(/^data:([^;,]+)?(;base64)?,(.*)$/s);if(!m)throw new Error('Invalid embedded image data.');const mime=m[1]||'image/png',raw=m[2]?atob(m[3]):decodeURIComponent(m[3]),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return{bytes,mime}}const r=await fetch(src);if(!r.ok)throw new Error('Could not read an inserted image.');return{bytes:new Uint8Array(await r.arrayBuffer()),mime:r.headers.get('content-type')||'image/png'}}
async function addImage(zip,doc,relsDoc,root,img,state){const data=await imageData(img),ext=/jpe?g/i.test(data.mime)?'jpg':/gif/i.test(data.mime)?'gif':'png',name='image'+(++state.imageNumber)+'.'+ext,rid='rId'+(++state.relNumber);zip.file(root+'/media/'+name,data.bytes);await ensureContentType(zip,ext,data.mime);const rel=relsDoc.createElementNS(PKG_REL_NS,'Relationship');rel.setAttribute('Id',rid);rel.setAttribute('Type','http://schemas.openxmlformats.org/officeDocument/2006/relationships/image');rel.setAttribute('Target','media/'+name);relsDoc.documentElement.appendChild(rel);const rect=img.getBoundingClientRect(),ratio=(img.naturalWidth&&img.naturalHeight)?img.naturalHeight/img.naturalWidth:.67,pxW=Math.max(40,rect.width||img.width||img.naturalWidth||300),pxH=Math.max(30,rect.height||img.height||Math.round(pxW*ratio)),cx=Math.round(pxW*9525),cy=Math.round(pxH*9525);return'<w:p><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="'+cx+'" cy="'+cy+'"/><wp:docPr id="'+state.imageNumber+'" name="Picture '+state.imageNumber+'"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="0" name="'+name+'"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="'+rid+'"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="'+cx+'" cy="'+cy+'"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>'}
async function appendNewItem(zip,doc,relsDoc,root,item,state,before){const node=item.node,images=node.tagName==='IMG'?[node]:Array.from(node.querySelectorAll?node.querySelectorAll('img'):[]);if(node.tagName!=='IMG'&&editorText(node).trim())before.parentNode.insertBefore(fragmentNode(doc,xmlForNewNode(node)),before);for(const img of images)before.parentNode.insertBefore(fragmentNode(doc,await addImage(zip,doc,relsDoc,root,img,state)),before)}
async function preserveAndSave(host,name,sourceBuffer,context){writerXmlBudget=global.InkDeskRuntime?global.InkDeskRuntime.createXmlBudget():null;if(global.InkDeskRuntime)global.InkDeskRuntime.validateZipPackage(sourceBuffer,'DOCX source package');const zip=await JSZip.loadAsync(sourceBuffer),beforeInventory=global.InkDeskRuntime?global.InkDeskRuntime.packageInventory(zip):[],mainPath=context.mainPath||'word/document.xml',root=context.root||mainPath.split('/')[0],docFile=zip.file(mainPath);if(!docFile)throw new Error('The original DOCX main document part is missing.');const doc=parseXml(await docFile.async('string')),body=descendants(doc,'body')[0];if(!body)throw new Error('The DOCX body is missing.');const bodyChildren=Array.from(body.children),items=sourceItems(host),bySource=new Map(),newItems=[];for(const item of items){if(item.sourceIndex===null)newItems.push(item);else{if(!bySource.has(item.sourceIndex))bySource.set(item.sourceIndex,[]);bySource.get(item.sourceIndex).push(item)}}
 const rendered=new Set(context.renderedSourceIndexes||[]);for(let index=bodyChildren.length-1;index>=0;index--){const source=bodyChildren[index];if(source.localName==='sectPr'||!rendered.has(index))continue;const current=bySource.get(index);if(!current||!current.length){source.remove();continue}const blocks=sourceBlocks(source);current.sort((a,b)=>a.sourceSubIndex-b.sourceSubIndex);for(const item of current){const target=blocks[item.sourceSubIndex]||blocks[0];if(!target)continue;if(target.localName==='tbl'&&item.node.tagName==='TABLE')patchTable(target,item.node);else patchText(target,editorText(item.node))}}
 let finalSect=Array.from(body.children).reverse().find(x=>x.localName==='sectPr');if(!finalSect){finalSect=doc.createElementNS(W_NS,'w:sectPr');body.appendChild(finalSect)}const relsPath=root+'/_rels/'+mainPath.split('/').pop()+'.rels',relsFile=zip.file(relsPath),relsDoc=relsFile?parseXml(await relsFile.async('string')):parseXml('<?xml version="1.0"?><Relationships xmlns="'+PKG_REL_NS+'"/>'),names=Object.keys(zip.files),imageNumber=Math.max(0,...names.map(n=>{const m=n.match(/\/media\/image(\d+)\./i);return m?Number(m[1]):0})),relNumber=Math.max(0,...Array.from(relsDoc.documentElement.children).map(r=>{const m=String(r.getAttribute('Id')||'').match(/rId(\d+)/i);return m?Number(m[1]):0})),state={imageNumber,relNumber};for(const item of newItems)await appendNewItem(zip,doc,relsDoc,root,item,state,finalSect);zip.file(mainPath,serialize(doc));zip.file(relsPath,serialize(relsDoc));if(global.InkDeskRuntime){const comparison=global.InkDeskRuntime.comparePackageInventory(beforeInventory,global.InkDeskRuntime.packageInventory(zip));if(comparison.removed.length||comparison.duplicates.length)throw new Error('DOCX package preservation check failed: '+comparison.removed.join(', '))}return makeResult(zip,name)}
async function saveNew(host,name){
 const zip=new JSZip(),word=zip.folder('word');
 zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>');
 zip.folder('_rels').file('.rels','<?xml version="1.0"?><Relationships xmlns="'+PKG_REL_NS+'"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');
 const doc=parseXml('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="'+W_NS+'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body><w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>'),body=descendants(doc,'body')[0],finalSect=descendants(body,'sectPr')[0],relsDoc=parseXml('<?xml version="1.0"?><Relationships xmlns="'+PKG_REL_NS+'"/>'),state={imageNumber:0,relNumber:0};
 for(const item of sourceItems(host))await appendNewItem(zip,doc,relsDoc,'word',item,state,finalSect);
 word.file('document.xml',serialize(doc)).file('styles.xml','<?xml version="1.0"?><w:styles xmlns:w="'+W_NS+'"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style></w:styles>');
 word.folder('_rels').file('document.xml.rels',serialize(relsDoc));
 return makeResult(zip,name)
}
async function makeResult(zip,name){const blob=await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',compression:'DEFLATE',compressionOptions:{level:6}}),base=(name||'Document').replace(/\.docx$/i,''),stamp=new Date().toISOString().replace(/[:.]/g,'-').slice(0,19);return{blob,fileName:'Copy of '+base+' '+stamp+'.docx'}}
async function save(host,name,sourceBuffer,context){if(!global.JSZip)throw new Error('DOCX writer library is missing.');return sourceBuffer&&context?preserveAndSave(host,name,sourceBuffer,context):saveNew(host,name)}
global.LocalDocxWriter={save};
})(window);
