(function(global){'use strict';
const NS=global.InkDOS2PdfP4=global.InkDOS2PdfP4||{};
class PageLayout{
 constructor({viewport,stack,onPageChange,onScaleChange,onPageRendered,onPageUnmount}={}){this.viewport=viewport;this.stack=stack;this.scheduler=null;this.pageCount=0;this.currentPage=1;this.metrics=null;this.view={mode:'fit-width',manualScale:1,rotation:0};this.views=new Map();this.generation=0;this.navigationGeneration=0;this.onPageChange=onPageChange||(()=>{});this.onScaleChange=onScaleChange||(()=>{});this.onPageRendered=onPageRendered||(()=>{});this.onPageUnmount=onPageUnmount||(()=>{});this.timer=0;this.scrollLock=false;this._scroll=()=>{clearTimeout(this.timer);this.timer=setTimeout(()=>this.handleScroll(),60)};viewport.addEventListener('scroll',this._scroll,{passive:true});this.pendingMetrics=null;this._focusout=()=>{clearTimeout(this.focusTimer);this.focusTimer=setTimeout(()=>{if(this.pendingMetrics&&!this.isTextEditing()){const m=this.pendingMetrics;this.pendingMetrics=null;this.setMetrics(m)}},0)};viewport.addEventListener('focusout',this._focusout)}
 setDocument(scheduler,count,page=1){this.generation++;this.navigationGeneration++;this.disposeViews();this.scheduler=scheduler;this.pageCount=count||0;this.currentPage=this.normalize(page);this.view.rotation=0;const token=this.navigationGeneration;this.ensureAround(this.currentPage,token).then(()=>{if(token===this.navigationGeneration)this.positionAtCurrent()}).catch(e=>console.error(e))}
 clearDocument(){this.generation++;this.navigationGeneration++;this.disposeViews();this.scheduler=null;this.pageCount=0;this.currentPage=1;this.view.rotation=0;this.viewport.scrollTop=0;this.viewport.scrollLeft=0;this.onPageChange(1)}
 isTextEditing(){const a=document.activeElement;return !!(a&&this.viewport.contains(a)&&(a.isContentEditable||a.matches?.('input,textarea,select')))}
 setMetrics(m){const old=this.metrics;if(old&&m.visible&&old.visible&&m.availableWidth===old.availableWidth&&m.dpr===old.dpr&&this.isTextEditing()){this.pendingMetrics=m;return}this.pendingMetrics=null;this.metrics=m;this.rerenderVisible(true)}
 setView(v){if(this.pendingMetrics){this.metrics=this.pendingMetrics;this.pendingMetrics=null}this.view={mode:v.mode||'fit-width',manualScale:Number(v.manualScale)||1,rotation:NS.PdfPolicy.normalizeRotation(v.rotation??this.view.rotation)};this.rerenderVisible(true)}
 async rotateView(delta=90){this.view.rotation=NS.PdfPolicy.normalizeRotation(this.view.rotation+Number(delta||0));for(const v of this.views.values())v.policy=null;await this.rerenderVisible(true);return this.view.rotation}
 get rotation(){return this.view.rotation||0}
 normalize(n){return Math.max(1,Math.min(this.pageCount||1,Math.trunc(Number(n)||1)))}
 createView(n){const host=document.createElement('div');host.className='pdf-page-host';host.dataset.page=String(n);const shell=document.createElement('section');shell.className='pdf-page-shell';shell.dataset.page=String(n);shell.innerHTML='<div class="pdf-page-placeholder">Loading…</div>';host.append(shell);const renderer=new NS.PageRenderer(shell),v={n,host,shell,renderer,record:null,policy:null};this.views.set(n,v);return v}
 async render(n,gen=this.generation){if(!this.metrics||!this.scheduler)return;const v=this.views.get(n)||this.createView(n),record=await this.scheduler.get(n);if(gen!==this.generation||!this.views.has(n)||this.views.get(n)!==v)return;v.record=record;const policy=NS.PdfPolicy.computePolicy(this.metrics,record.geometry,this.view);if(!policy.suspended&&v.policy?.scale===policy.scale&&v.policy?.cssWidth===policy.cssWidth&&v.policy?.cssHeight===policy.cssHeight&&v.policy?.rotation===policy.rotation&&v.renderDpr===this.metrics.dpr){if(n===this.currentPage)this.onScaleChange(v.policy.scale);return}const renderDpr=this.metrics.dpr;const r=await v.renderer.render({page:record.page,geometry:record.geometry,metrics:this.metrics,view:this.view});if(gen!==this.generation||!this.views.has(n)||this.views.get(n)!==v)return;if(r?.status==='rendered'){v.policy=r.policy;v.renderDpr=renderDpr;await this.onPageRendered({pageNumber:n,shell:v.shell,policy:r.policy,record,viewport:r.viewport});if(gen!==this.generation||!this.views.has(n)||this.views.get(n)!==v)return;if(n===this.currentPage)this.onScaleChange(r.policy.scale)}}
 async ensureAround(center,navToken=this.navigationGeneration){if(!this.metrics||!this.scheduler||!this.pageCount)return;const gen=this.generation,start=Math.max(1,center-3),end=Math.min(this.pageCount,center+4),needed=[];for(let n=start;n<=end;n++){needed.push(n);if(!this.views.has(n))this.createView(n)}for(const n of [...this.views.keys()].sort((a,b)=>a-b)){const v=this.views.get(n);if(!v.host.isConnected){const next=[...this.stack.children].find(el=>Number(el.dataset.page)>n);next?this.stack.insertBefore(v.host,next):this.stack.append(v.host)}}await Promise.all(needed.map(n=>this.render(n,gen)));if(gen!==this.generation)return;if(navToken!==this.navigationGeneration){this.trim(this.currentPage);return}this.trim(this.currentPage);this.mark();this.scheduler.prefetch(this.currentPage)}
 trim(center){const keep=new Set();for(let n=Math.max(1,center-4);n<=Math.min(this.pageCount,center+5);n++)keep.add(n);for(const[n,v]of [...this.views])if(!keep.has(n)){this.onPageUnmount(n);v.renderer.cancel();v.host.remove();this.views.delete(n)}}
 positionAtCurrent({smooth=false}={}){const host=this.views.get(this.currentPage)?.host;if(!host)return;this.scrollLock=true;host.scrollIntoView({block:'start',inline:'center',behavior:smooth?'smooth':'auto'});setTimeout(()=>this.scrollLock=false,smooth?400:80);this.mark()}
 async goToPage(n,{smooth=false}={}){if(!this.pageCount)return;n=this.normalize(n);const token=++this.navigationGeneration;this.currentPage=n;this.onPageChange(n);await this.ensureAround(n,token);if(token!==this.navigationGeneration)return;this.positionAtCurrent({smooth})}
 next(){return this.goToPage(this.currentPage+1)}prev(){return this.goToPage(this.currentPage-1)}mark(){for(const[n,v]of this.views)v.host.classList.toggle('is-current',n===this.currentPage)}
 captureAnchor(){const v=this.views.get(this.currentPage);if(!v?.shell?.isConnected)return null;const vp=this.viewport.getBoundingClientRect(),r=v.shell.getBoundingClientRect();const clientX=vp.left+vp.width*.5,clientY=vp.top+vp.height*.40;const x=Math.max(0,Math.min(1,(clientX-r.left)/Math.max(1,r.width))),y=Math.max(0,Math.min(1,(clientY-r.top)/Math.max(1,r.height)));return {page:this.currentPage,x,y,clientX,clientY}}
 restoreAnchor(a){if(!a)return;const shell=this.views.get(a.page)?.shell;if(!shell?.isConnected)return;const r=shell.getBoundingClientRect(),targetX=r.left+r.width*a.x,targetY=r.top+r.height*a.y;this.viewport.scrollLeft+=targetX-a.clientX;this.viewport.scrollTop+=targetY-a.clientY}
 async rerenderVisible(preserve=false){if(!this.metrics||!this.views.size)return;const anchor=preserve?this.captureAnchor():null,gen=this.generation;this.scrollLock=true;await Promise.all([...this.views.keys()].map(n=>this.render(n,gen)));if(gen!==this.generation)return;this.restoreAnchor(anchor);setTimeout(()=>this.scrollLock=false,80);this.mark()}
 handleScroll(){if(this.scrollLock||!this.views.size)return;const vp=this.viewport.getBoundingClientRect(),y=vp.top+Math.min(vp.height*.35,220);let best=null;for(const[n,v]of this.views){const r=v.host.getBoundingClientRect();if(r.bottom<=vp.top||r.top>=vp.bottom)continue;const d=Math.abs(r.top+Math.min(r.height*.2,100)-y);if(!best||d<best.d)best={n,d}}if(best&&best.n!==this.currentPage){this.currentPage=best.n;this.onPageChange(best.n);this.mark();const token=++this.navigationGeneration;this.ensureAround(best.n,token)}}
 getShell(n){return this.views.get(n)?.shell||null}
 inspect(){return Object.freeze({currentPage:this.currentPage,pageCount:this.pageCount,renderedPages:Object.freeze([...this.views.keys()].sort((a,b)=>a-b)),view:Object.freeze({...this.view}),scale:this.views.get(this.currentPage)?.policy?.scale||0,navigationGeneration:this.navigationGeneration})}
 disposeViews(){this.pendingMetrics=null;for(const[n,v]of this.views){this.onPageUnmount(n);v.renderer.cancel();v.host.remove()}this.views.clear();this.stack.replaceChildren()}
 dispose(){this.viewport.removeEventListener('scroll',this._scroll);clearTimeout(this.timer);clearTimeout(this.focusTimer);this.viewport.removeEventListener('focusout',this._focusout);this.disposeViews()}
}
NS.PageLayout=PageLayout;})(globalThis);
