(function(root){'use strict';
const NS=root.InkDOS2Spreadsheets=root.InkDOS2Spreadsheets||{};
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v))}
function cloneCell(cell){return cell?clone(cell):null}
function snapshotSheet(sheet){return{cells:[...sheet.cells].map(([k,v])=>[k,cloneCell(v)]),merges:[...(sheet.merges||[])],widths:{...(sheet.widths||{})},heights:{...(sheet.heights||{})},maxR:sheet.maxR,maxC:sheet.maxC}}
function restoreSheet(sheet,s){sheet.cells=new Map(s.cells.map(([k,v])=>[k,cloneCell(v)]));sheet.merges=[...s.merges];sheet.widths={...s.widths};sheet.heights={...s.heights};sheet.maxR=s.maxR;sheet.maxC=s.maxC}
function parseInput(value){value=String(value??'');if(value.startsWith('='))return{v:'',f:value.slice(1),t:'n',display:value};const n=Number(value.replace(',','.'));if(value.trim()!==''&&Number.isFinite(n))return{v:n,f:'',t:'n',display:String(n)};return{v:value,f:'',t:'s',display:value}}
class WorkbookEditor{
 constructor({session,selection,history,onChange}={}){this.session=session;this.selection=selection;this.history=history;this.onChange=onChange}
 sheet(){return this.session.activeSheet()}
 ref(r=this.selection.active.r,c=this.selection.active.c){return root.LocalXLSX.encodeRef(r,c)}
 ensureCell(r=this.selection.active.r,c=this.selection.active.c){const s=this.sheet(),k=this.ref(r,c);let cell=s.cells.get(k);if(!cell){cell={v:'',f:'',styleId:0,style:{},t:'s',display:''};s.cells.set(k,cell)}cell.style=cell.style||{};cell.style.font=cell.style.font||{};cell.style.border=cell.style.border||{};return cell}
 selectedRefs(){const q=this.selection.range,out=[];for(let r=q.r1;r<=q.r2;r++)for(let c=q.c1;c<=q.c2;c++)out.push(this.ref(r,c));return out}
 mutate(label,fn,{rebuild=false}={}){const s=this.sheet(),before=snapshotSheet(s),selectionBefore=this.selection.snapshot();fn(s);NS.FormulaEvaluator.recalculate(this.session.book);const after=snapshotSheet(s),selectionAfter=this.selection.snapshot();this.history.push({label,before,after,selectionBefore,selectionAfter});this.session.markDirty();this.onChange?.({label,rebuild});return true}
 applyHistory(action,direction){const s=this.sheet(),snap=direction==='undo'?action.before:action.after,sel=direction==='undo'?action.selectionBefore:action.selectionAfter;restoreSheet(s,snap);this.selection.restore(sel);NS.FormulaEvaluator.recalculate(this.session.book);this.session.markDirty();this.onChange?.({label:direction,rebuild:true})}
 undo(){return this.history.undo((a,d)=>this.applyHistory(a,d))}
 redo(){return this.history.redo((a,d)=>this.applyHistory(a,d))}
 commitValue(value,r=this.selection.active.r,c=this.selection.active.c){return this.mutate('Edit cell',()=>{const cell=this.ensureCell(r,c),parsed=parseInput(value);Object.assign(cell,parsed);delete cell.calculated;delete cell.calculatedRaw;this.selection.select(r,c,this.sheet(),false)})}
 formatSelection(mutator,label='Format cells'){return this.mutate(label,()=>{for(const k of this.selectedRefs()){const p=root.LocalXLSX.decodeRef(k),cell=this.ensureCell(p.r,p.c);mutator(cell);cell._styleDirty=true}}, {rebuild:false})}
 toggleFont(key){return this.formatSelection(cell=>{cell.style.font=cell.style.font||{};cell.style.font[key]=!cell.style.font[key]},'Toggle '+key)}
 setAlignment(value){return this.formatSelection(cell=>{cell.style.align=value},'Align '+value)}
 setFont(name){return this.formatSelection(cell=>{cell.style.font=cell.style.font||{};cell.style.font.name=name},'Set font')}
 setFontSize(size){return this.formatSelection(cell=>{cell.style.font=cell.style.font||{};cell.style.font.size=Number(size)||11},'Set font size')}
 toggleMerge(){const q=this.selection.range;if(q.r1===q.r2&&q.c1===q.c2)return false;return this.mutate('Merge cells',s=>{const existing=s.merges.findIndex(m=>{const x=root.LocalXLSX.decodeRange(m);return!(x.r2<q.r1||x.r1>q.r2||x.c2<q.c1||x.c1>q.c2)});if(existing>=0)s.merges.splice(existing,1);else s.merges.push(`${this.ref(q.r1,q.c1)}:${this.ref(q.r2,q.c2)}`)}, {rebuild:true})}
 clear(){return this.mutate('Clear cells',s=>{for(const k of this.selectedRefs()){const cell=s.cells.get(k);if(cell){cell.v='';cell.f='';cell.display='';delete cell.calculated;delete cell.calculatedRaw}}})}
 insertRow(){const at=this.selection.active.r+1;return this.mutate('Insert row',s=>{const next=new Map();for(const[k,cell]of s.cells){const p=root.LocalXLSX.decodeRef(k);next.set(this.ref(p.r>=at?p.r+1:p.r,p.c),cell)}s.cells=next;const h={};for(const[k,v]of Object.entries(s.heights||{})){const r=+k;h[r>=at?r+1:r]=v}s.heights=h;s.merges=(s.merges||[]).map(m=>{const q=root.LocalXLSX.decodeRange(m);if(q.r1>=at){q.r1++;q.r2++}else if(q.r2>=at)q.r2++;return`${this.ref(q.r1,q.c1)}:${this.ref(q.r2,q.c2)}`});s.maxR++;this.selection.select(at,this.selection.active.c,s,false)}, {rebuild:true})}
 insertColumn(){const at=this.selection.active.c+1;return this.mutate('Insert column',s=>{const next=new Map();for(const[k,cell]of s.cells){const p=root.LocalXLSX.decodeRef(k);next.set(this.ref(p.r,p.c>=at?p.c+1:p.c),cell)}s.cells=next;const w={};for(const[k,v]of Object.entries(s.widths||{})){const c=+k;w[c>=at?c+1:c]=v}s.widths=w;s.merges=(s.merges||[]).map(m=>{const q=root.LocalXLSX.decodeRange(m);if(q.c1>=at){q.c1++;q.c2++}else if(q.c2>=at)q.c2++;return`${this.ref(q.r1,q.c1)}:${this.ref(q.r2,q.c2)}`});s.maxC++;this.selection.select(this.selection.active.r,at,s,false)}, {rebuild:true})}
 deleteRows(){const q=this.selection.range,from=q.r1,count=q.r2-q.r1+1;return this.mutate('Delete rows',s=>{const next=new Map();for(const[k,cell]of s.cells){const p=root.LocalXLSX.decodeRef(k);if(p.r<from)next.set(k,cell);else if(p.r>q.r2)next.set(this.ref(p.r-count,p.c),cell)}s.cells=next;const h={};for(const[k,v]of Object.entries(s.heights||{})){const r=+k;if(r<from)h[r]=v;else if(r>q.r2)h[r-count]=v}s.heights=h;s.merges=(s.merges||[]).filter(m=>{const x=root.LocalXLSX.decodeRange(m);return x.r2<from||x.r1>q.r2}).map(m=>{const x=root.LocalXLSX.decodeRange(m);if(x.r1>q.r2){x.r1-=count;x.r2-=count}return`${this.ref(x.r1,x.c1)}:${this.ref(x.r2,x.c2)}`});s.maxR=Math.max(0,s.maxR-count);this.selection.select(Math.min(from,s.maxR),Math.min(this.selection.active.c,s.maxC),s,false)}, {rebuild:true})}
 deleteColumns(){const q=this.selection.range,from=q.c1,count=q.c2-q.c1+1;return this.mutate('Delete columns',s=>{const next=new Map();for(const[k,cell]of s.cells){const p=root.LocalXLSX.decodeRef(k);if(p.c<from)next.set(k,cell);else if(p.c>q.c2)next.set(this.ref(p.r,p.c-count),cell)}s.cells=next;const w={};for(const[k,v]of Object.entries(s.widths||{})){const c=+k;if(c<from)w[c]=v;else if(c>q.c2)w[c-count]=v}s.widths=w;s.merges=(s.merges||[]).filter(m=>{const x=root.LocalXLSX.decodeRange(m);return x.c2<from||x.c1>q.c2}).map(m=>{const x=root.LocalXLSX.decodeRange(m);if(x.c1>q.c2){x.c1-=count;x.c2-=count}return`${this.ref(x.r1,x.c1)}:${this.ref(x.r2,x.c2)}`});s.maxC=Math.max(0,s.maxC-count);this.selection.select(Math.min(this.selection.active.r,s.maxR),Math.min(from,s.maxC),s,false)}, {rebuild:true})}
 operation(kind,factor){const q=this.selection.range;if(['sum','average','min','max','count'].includes(kind)){const fn=kind.toUpperCase(),formula=`=${fn}(${this.ref(q.r1,q.c1)}:${this.ref(q.r2,q.c2)})`,r=q.r2+1,c=q.c1;this.sheet().maxR=Math.max(this.sheet().maxR,r);return this.commitValue(formula,r,c)}const f=kind==='percent'?100:Number(factor);if(!Number.isFinite(f)||f===0)return false;return this.mutate('Numeric operation',()=>{for(const k of this.selectedRefs()){const p=root.LocalXLSX.decodeRef(k),cell=this.ensureCell(p.r,p.c),raw=cell.calculated??cell.v,n=Number(raw);if(!Number.isFinite(n))continue;if(kind==='multiply')cell.v=n*f;else if(kind==='divide')cell.v=n/f;else if(kind==='percent'){cell.v=n/100;cell.style.numberFormat='0.00%';cell._styleDirty=true}cell.f='';cell.display=String(cell.v);delete cell.calculated;delete cell.calculatedRaw}})}
 resizeColumn(c,width){return this.mutate('Resize column',s=>{s.widths[c]=Math.max(28,Math.min(600,width))},{rebuild:false})}
 resizeRow(r,height){return this.mutate('Resize row',s=>{s.heights[r]=Math.max(14,Math.min(300,height))},{rebuild:false})}
}
NS.WorkbookEditor=WorkbookEditor;
})(globalThis);
