(function(root){'use strict';
const NS=root.InkDOS2Spreadsheets=root.InkDOS2Spreadsheets||{};
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v))}
function cloneCell(cell){return cell?clone(cell):null}
function snapshotSheet(sheet){return{cells:[...sheet.cells].map(([k,v])=>[k,cloneCell(v)]),merges:[...(sheet.merges||[])],widths:{...(sheet.widths||{})},heights:{...(sheet.heights||{})},maxR:sheet.maxR,maxC:sheet.maxC}}
function restoreSheet(sheet,s){sheet.cells=new Map(s.cells.map(([k,v])=>[k,cloneCell(v)]));sheet.merges=[...s.merges];sheet.widths={...s.widths};sheet.heights={...s.heights};sheet.maxR=s.maxR;sheet.maxC=s.maxC}
const CELL_OR_RANGE=/((?:'(?:[^']|'')+'|[A-Za-z_][A-Za-z0-9_. ]*)!)?(\$?)([A-Z]{1,3})(\$?)(\d+)(?::(\$?)([A-Z]{1,3})(\$?)(\d+))?/g;
function formulaSheetName(prefix){if(!prefix)return'';let s=prefix.slice(0,-1);if(s.startsWith("'")&&s.endsWith("'"))s=s.slice(1,-1).replace(/''/g,"'");return s}
function formulaColIndex(name){let c=0;for(const ch of String(name).toUpperCase())c=c*26+ch.charCodeAt(0)-64;return c-1}
function formulaColName(index){let n=index+1,out='';while(n>0){const r=(n-1)%26;out=String.fromCharCode(65+r)+out;n=Math.floor((n-1)/26)}return out}
function adjustFormulaIndex(index,change){const start=change.index,del=change.deleteCount||0,ins=change.insertCount||0;if(ins&&index>=start)return index+ins;if(del){const end=start+del-1;if(index>=start&&index<=end)return null;if(index>end)return index-del}return index}
function adjustFormulaRange(lo,hi,change){const start=change.index,del=change.deleteCount||0,ins=change.insertCount||0;if(ins)return[lo>=start?lo+ins:lo,hi>=start?hi+ins:hi];if(!del)return[lo,hi];const end=start+del-1;if(hi<start)return[lo,hi];if(lo>end)return[lo-del,hi-del];if(lo>=start&&hi<=end)return null;const nextLo=lo<start?lo:start,nextHi=hi>end?hi-del:start-1;return nextHi<nextLo?null:[nextLo,nextHi]}
function formulaCellText(colAbs,col,rowAbs,row){return`${colAbs||''}${formulaColName(col)}${rowAbs||''}${row+1}`}
function formulaApplies(prefix,currentSheet,targetSheet){if(prefix)return formulaSheetName(prefix).toLowerCase()===String(targetSheet.name||'').toLowerCase();return currentSheet===targetSheet}
function rewriteFormulaChunk(chunk,currentSheet,targetSheet,change){return chunk.replace(CELL_OR_RANGE,(full,prefix,cAbs1,col1,rAbs1,row1,cAbs2,col2,rAbs2,row2,offset,text)=>{const prev=offset>0?text[offset-1]:'',next=text[offset+full.length]||'';if(/[A-Za-z0-9_.\]]/.test(prev)||/[A-Za-z0-9_]/.test(next))return full;if(!prefix&&!col2&&next==='(')return full;if(!formulaApplies(prefix,currentSheet,targetSheet))return full;const axis=change.axis;if(!col2){let r=Number(row1)-1,c=formulaColIndex(col1);if(axis==='row')r=adjustFormulaIndex(r,change);else c=adjustFormulaIndex(c,change);if(r==null||c==null)return'#REF!';return`${prefix||''}${formulaCellText(cAbs1,c,rAbs1,r)}`}
 let r1=Number(row1)-1,c1=formulaColIndex(col1),r2=Number(row2)-1,c2=formulaColIndex(col2);if(axis==='row'){const adjusted=adjustFormulaRange(Math.min(r1,r2),Math.max(r1,r2),change);if(!adjusted)return'#REF!';if(r1<=r2)[r1,r2]=adjusted;else[r2,r1]=adjusted}else{const adjusted=adjustFormulaRange(Math.min(c1,c2),Math.max(c1,c2),change);if(!adjusted)return'#REF!';if(c1<=c2)[c1,c2]=adjusted;else[c2,c1]=adjusted}return`${prefix||''}${formulaCellText(cAbs1,c1,rAbs1,r1)}:${formulaCellText(cAbs2,c2,rAbs2,r2)}`})}
function rewriteFormula(formula,currentSheet,targetSheet,change){const text=String(formula||'');let out='',start=0,quoted=false;for(let i=0;i<text.length;i++){if(text[i]!=='"')continue;if(!quoted){out+=rewriteFormulaChunk(text.slice(start,i),currentSheet,targetSheet,change);start=i;quoted=true}else{out+=text.slice(start,i+1);start=i+1;quoted=false}}out+=quoted?text.slice(start):rewriteFormulaChunk(text.slice(start),currentSheet,targetSheet,change);return out}
function rewriteWorkbookFormulas(book,targetSheet,change){for(const sheet of book.sheets||[])for(const cell of sheet.cells?.values?.()||[]){if(!cell?.f)continue;const next=rewriteFormula(cell.f,sheet,targetSheet,change);if(next===cell.f)continue;cell.f=next;delete cell.calculated;delete cell.calculatedRaw}}
function snapshotExternalFormulas(book,targetSheet){const out=[];(book?.sheets||[]).forEach((sheet,index)=>{if(sheet===targetSheet)return;const formulas=[];for(const[ref,cell]of sheet.cells||[])if(cell?.f)formulas.push([ref,String(cell.f)]);out.push([index,formulas])});return out}
function restoreExternalFormulas(book,snapshot){for(const[index,formulas]of snapshot||[]){const sheet=book?.sheets?.[index];if(!sheet)continue;for(const[ref,formula]of formulas){const cell=sheet.cells?.get(ref);if(!cell)continue;cell.f=formula;delete cell.calculated;delete cell.calculatedRaw}}}
function parseInput(value){value=String(value??'');if(value.startsWith('='))return{v:'',f:value.slice(1),t:'n',display:value};const n=Number(value.replace(',','.'));if(value.trim()!==''&&Number.isFinite(n))return{v:n,f:'',t:'n',display:String(n)};return{v:value,f:'',t:'s',display:value}}
class WorkbookEditor{
 constructor({session,selection,history,onChange}={}){this.session=session;this.selection=selection;this.history=history;this.onChange=onChange}
 sheet(){return this.session.activeSheet()}
 ref(r=this.selection.active.r,c=this.selection.active.c){return root.LocalXLSX.encodeRef(r,c)}
 ensureCell(r=this.selection.active.r,c=this.selection.active.c){const s=this.sheet(),k=this.ref(r,c);let cell=s.cells.get(k);if(!cell){cell={v:'',f:'',styleId:0,style:{},t:'s',display:''};s.cells.set(k,cell)}cell.style=cell.style||{};cell.style.font=cell.style.font||{};cell.style.border=cell.style.border||{};return cell}
 selectedRefs(){const q=this.selection.range,out=[];for(let r=q.r1;r<=q.r2;r++)for(let c=q.c1;c<=q.c2;c++)out.push(this.ref(r,c));return out}
 mutate(label,fn,{rebuild=false,formulaHistory=false}={}){const s=this.sheet(),before=snapshotSheet(s),selectionBefore=this.selection.snapshot(),externalBefore=formulaHistory?snapshotExternalFormulas(this.session.book,s):null;fn(s);NS.FormulaEvaluator.recalculate(this.session.book);const after=snapshotSheet(s),selectionAfter=this.selection.snapshot(),externalAfter=formulaHistory?snapshotExternalFormulas(this.session.book,s):null;this.history.push({label,before,after,selectionBefore,selectionAfter,externalBefore,externalAfter});this.session.markDirty();this.onChange?.({label,rebuild});return true}
 applyHistory(action,direction){const s=this.sheet(),snap=direction==='undo'?action.before:action.after,sel=direction==='undo'?action.selectionBefore:action.selectionAfter,external=direction==='undo'?action.externalBefore:action.externalAfter;restoreSheet(s,snap);if(external)restoreExternalFormulas(this.session.book,external);this.selection.restore(sel);NS.FormulaEvaluator.recalculate(this.session.book);this.session.markDirty();this.onChange?.({label:direction,rebuild:true})}
 undo(){return this.history.undo((a,d)=>this.applyHistory(a,d))}
 redo(){return this.history.redo((a,d)=>this.applyHistory(a,d))}
 commitValue(value,r=this.selection.active.r,c=this.selection.active.c){return this.mutate('Edit cell',()=>{const cell=this.ensureCell(r,c),parsed=parseInput(value);Object.assign(cell,parsed);delete cell.calculated;delete cell.calculatedRaw;this.selection.select(r,c,this.sheet(),false)})}
 formatSelection(mutator,label='Format cells'){return this.mutate(label,()=>{for(const k of this.selectedRefs()){const p=root.LocalXLSX.decodeRef(k),cell=this.ensureCell(p.r,p.c);mutator(cell);cell._styleDirty=true}}, {rebuild:false})}
 toggleFont(key){return this.formatSelection(cell=>{cell.style.font=cell.style.font||{};cell.style.font[key]=!cell.style.font[key]},'Toggle '+key)}
 setAlignment(value){return this.formatSelection(cell=>{cell.style.align=value},'Align '+value)}
 setFont(name){return this.formatSelection(cell=>{cell.style.font=cell.style.font||{};cell.style.font.name=name},'Set font')}
 setFontSize(size){return this.formatSelection(cell=>{cell.style.font=cell.style.font||{};cell.style.font.size=Number(size)||11},'Set font size')}
 toggleMerge(){const q=this.selection.range;if(q.r1===q.r2&&q.c1===q.c2)return false;return this.mutate('Merge cells',s=>{const existing=s.merges.findIndex(m=>{const x=root.LocalXLSX.decodeRange(m);return!(x.r2<q.r1||x.r1>q.r2||x.c2<q.c1||x.c1>q.c2)});if(existing>=0)s.merges.splice(existing,1);else s.merges.push(`${this.ref(q.r1,q.c1)}:${this.ref(q.r2,q.c2)}`)}, {rebuild:true})}
 clear(){return this.mutate('Clear cells',s=>{for(const k of this.selectedRefs()){const cell=s.cells.get(k);if(cell){cell.v='';cell.f='';cell.display='';delete cell.calculated;delete cell.calculatedRaw}}})}
 insertRow(){const at=this.selection.active.r+1;return this.mutate('Insert row',s=>{const next=new Map();for(const[k,cell]of s.cells){const p=root.LocalXLSX.decodeRef(k);next.set(this.ref(p.r>=at?p.r+1:p.r,p.c),cell)}s.cells=next;const h={};for(const[k,v]of Object.entries(s.heights||{})){const r=+k;h[r>=at?r+1:r]=v}s.heights=h;s.merges=(s.merges||[]).map(m=>{const q=root.LocalXLSX.decodeRange(m);if(q.r1>=at){q.r1++;q.r2++}else if(q.r2>=at)q.r2++;return`${this.ref(q.r1,q.c1)}:${this.ref(q.r2,q.c2)}`});s.maxR++;rewriteWorkbookFormulas(this.session.book,s,{axis:'row',index:at,insertCount:1,deleteCount:0});this.selection.select(at,this.selection.active.c,s,false)}, {rebuild:true,formulaHistory:true})}
 insertColumn(){const at=this.selection.active.c+1;return this.mutate('Insert column',s=>{const next=new Map();for(const[k,cell]of s.cells){const p=root.LocalXLSX.decodeRef(k);next.set(this.ref(p.r,p.c>=at?p.c+1:p.c),cell)}s.cells=next;const w={};for(const[k,v]of Object.entries(s.widths||{})){const c=+k;w[c>=at?c+1:c]=v}s.widths=w;s.merges=(s.merges||[]).map(m=>{const q=root.LocalXLSX.decodeRange(m);if(q.c1>=at){q.c1++;q.c2++}else if(q.c2>=at)q.c2++;return`${this.ref(q.r1,q.c1)}:${this.ref(q.r2,q.c2)}`});s.maxC++;rewriteWorkbookFormulas(this.session.book,s,{axis:'column',index:at,insertCount:1,deleteCount:0});this.selection.select(this.selection.active.r,at,s,false)}, {rebuild:true,formulaHistory:true})}
 deleteRows(){const q=this.selection.range,from=q.r1,count=q.r2-q.r1+1;return this.mutate('Delete rows',s=>{const next=new Map();for(const[k,cell]of s.cells){const p=root.LocalXLSX.decodeRef(k);if(p.r<from)next.set(k,cell);else if(p.r>q.r2)next.set(this.ref(p.r-count,p.c),cell)}s.cells=next;const h={};for(const[k,v]of Object.entries(s.heights||{})){const r=+k;if(r<from)h[r]=v;else if(r>q.r2)h[r-count]=v}s.heights=h;s.merges=(s.merges||[]).filter(m=>{const x=root.LocalXLSX.decodeRange(m);return x.r2<from||x.r1>q.r2}).map(m=>{const x=root.LocalXLSX.decodeRange(m);if(x.r1>q.r2){x.r1-=count;x.r2-=count}return`${this.ref(x.r1,x.c1)}:${this.ref(x.r2,x.c2)}`});s.maxR=Math.max(0,s.maxR-count);rewriteWorkbookFormulas(this.session.book,s,{axis:'row',index:from,insertCount:0,deleteCount:count});this.selection.select(Math.min(from,s.maxR),Math.min(this.selection.active.c,s.maxC),s,false)}, {rebuild:true,formulaHistory:true})}
 deleteColumns(){const q=this.selection.range,from=q.c1,count=q.c2-q.c1+1;return this.mutate('Delete columns',s=>{const next=new Map();for(const[k,cell]of s.cells){const p=root.LocalXLSX.decodeRef(k);if(p.c<from)next.set(k,cell);else if(p.c>q.c2)next.set(this.ref(p.r,p.c-count),cell)}s.cells=next;const w={};for(const[k,v]of Object.entries(s.widths||{})){const c=+k;if(c<from)w[c]=v;else if(c>q.c2)w[c-count]=v}s.widths=w;s.merges=(s.merges||[]).filter(m=>{const x=root.LocalXLSX.decodeRange(m);return x.c2<from||x.c1>q.c2}).map(m=>{const x=root.LocalXLSX.decodeRange(m);if(x.c1>q.c2){x.c1-=count;x.c2-=count}return`${this.ref(x.r1,x.c1)}:${this.ref(x.r2,x.c2)}`});s.maxC=Math.max(0,s.maxC-count);rewriteWorkbookFormulas(this.session.book,s,{axis:'column',index:from,insertCount:0,deleteCount:count});this.selection.select(Math.min(this.selection.active.r,s.maxR),Math.min(from,s.maxC),s,false)}, {rebuild:true,formulaHistory:true})}
 operation(kind,factor){const q=this.selection.range;if(['sum','average','min','max','count'].includes(kind)){const fn=kind.toUpperCase(),formula=`=${fn}(${this.ref(q.r1,q.c1)}:${this.ref(q.r2,q.c2)})`,r=q.r2+1,c=q.c1;this.sheet().maxR=Math.max(this.sheet().maxR,r);return this.commitValue(formula,r,c)}const f=kind==='percent'?100:Number(factor);if(!Number.isFinite(f)||f===0)return false;return this.mutate('Numeric operation',()=>{for(const k of this.selectedRefs()){const p=root.LocalXLSX.decodeRef(k),cell=this.ensureCell(p.r,p.c),raw=cell.calculated??cell.v,n=Number(raw);if(!Number.isFinite(n))continue;if(kind==='multiply')cell.v=n*f;else if(kind==='divide')cell.v=n/f;else if(kind==='percent'){cell.v=n/100;cell.style.numberFormat='0.00%';cell._styleDirty=true}cell.f='';cell.display=String(cell.v);delete cell.calculated;delete cell.calculatedRaw}})}
 resizeColumn(c,width){return this.mutate('Resize column',s=>{s.widths[c]=Math.max(28,Math.min(600,width))},{rebuild:false})}
 resizeRow(r,height){return this.mutate('Resize row',s=>{s.heights[r]=Math.max(14,Math.min(300,height))},{rebuild:false})}
}
NS.WorkbookEditor=WorkbookEditor;
})(globalThis);
